---
title: <center>FW 680A4 <br> Wildlife Ecology Modeling <br> (Fall 2024)</center>
---


# Course Overview

## Instructor

**Name**:  [Brian D. Gerber](https://bgerber123.github.io/)

**Position/Affiliation** Research Scientist and Assistant Unit Leader at U.S. Geological Survey, [Colorado Cooperative Research Unit](https://www1.usgs.gov/coopunits/unit/Colorado) and Associate Professor in the Department of Fish, Wildlife, and Conservation Biology at Colorado State University. 

**Office:**  202A Wagar, Colorado Cooperative Research Unit

**Email:** brian.gerber@colostate.edu

**Office Hours:** TU 1:30pm - 2:30pm and by appointment


## Course Information

**Course Number:** FW 680A4 (Experimental Course)

**Fall 2024:** Tu 11am - 12:15 and Fr 10am - 1pm

**Credits:** 3

**Websites:**  [bgerber123.github.io/FW680A4/](/FW680A4/index.qmd) and [Canvas](https://colostate.instructure.com/).

**Schedule:** [Subject to Change](/FW680A4/schedule.qmd)

**Prerequisites:**  A basic statistics course is required. Being comfortable coding in the R programming language. See [here](/FW680A4/Rknowledge.qmd) for the type of R knowledge I am expecting. For learning R, see [R resources under 'Learning R' tab](/FW680A4/)).


**Text and Readings:** All lecture and course materials will be provided. 

**Computing:** A laptop will be necessary to work on coding during class periods.


## Course Description

Students will gain knowledge and skills focused on 1) modeling data to make inference/predictions on wildlife and their habitat, 2) understanding and communicating results, 3) evaluating modeling frameworks based on data and study goals, and 4) implementing models and report writing through the R programming language. The format will include lectures, discussions, in-class labs, out of class assigned labs, and readings. Students are strongly encouraged to have base-level knowledge of coding in R.

## Course Learning Objectives

Upon successful completion of this course students will: 

- develop a foundation of statistical thinking that includes principles of study design and modeling relevant to wildlife ecology and conservation

- be able to communicate statistical approaches and results through transparent and reproducible reporting

- be able to read and understand quantitative wildlife ecology literature

- be able to write code to fit and interpret complex statistical models relevant to wildlife ecology and conservation.  


## Assessment

Assessment Components  | Percentage of Grade
--------------------   | -------------------
Course Engagement      | 10%
Lab Assignments        | 40%
Online Discussion      | 10%
Quizzes                | 10%
Group Project          | 30%
 
Table 1: Grade breakdown by graded components

<br>

<br>


 Letter Grade         | Percentage Range
--------------------  | -------------------
A+                    | 100.00 to 96.67
A                     | 96.67 to 93.33
A-                    | 93.33 to 90.00
B+                    | 90.00 to 86.67
B                     | 86.67 to 83.33
B-                    | 83.33 to 80.00
C+                    | 80.00 to 76.67
C                     | 76.67 to 70.00
D                     | 70.00 to 60.00
F                     | 60.00 to 00.00

Table 1: Grade scheme from [CSU](https://canvas.colostate.edu/grading-schemes/)


## Student Experiences and Pedagogical Techniques

**In-class lectures:** Most class periods will include a lecture that will take 1/4 to 1/2 of the course period. Lectures will often incorporate brief instructor-led questions and short discussions.

**In-class student-led discussions:** Small groups (~2 students) will be assigned to co-lead discussions on assigned readings. These discussions will occur prior to any lecture for that class. This will provide students with an opportunity to communicate about the assigned readings content, raise questions for themselves and learn to elicit thoughts and questions from others. 

**In-class labs:** Every other class will include a lab. Students will be challenged in class to work individually or in groups to understand, develop and implement code to fit models.

**Out-of-class lab assignments:** Students will be encouraged to work together to finish the remainder of the labs that were started in-class. 

**Out-of-class reading:** Every other class will have an assigned reading. 

**Out-of-class discussion board:** Students will communicate on an online discussion board posted to Canvas about specific course prompts related to readings and lecture. 

**Out-of-class quizzes:** Short quizzes on Canvas will be used to gauge student comprehension of assigned reading and provide accountability for out-of-class preparation. 

**Group project:** A group project will be used as a final assessment of the student's integration of knowledge through the application of learned material. A group of 2-3 students will either 1) develop an independent research project (ideally connected to their graduate research topic), or 2) develops a short lecture along with a lab case-study that showcases a statistical application relevant to wildlife ecology and conservation.

