---
title: ""
---

## Wildlife Ecology Modeling (FW680A4)

<p><a href="CourseOverview.qmd">Course Overview</a></p>

<p><a href="schedule.qmd">Schedule (Subject to Change)</a></p>

<br>

::: {.panel-tabset}

### Weeks 

:::: {.columns}

::: {.column width="50%"}

<p><a href="week1.qmd">Week 1 (Aug 20, 23)</a></p>

<p><a href="week2.qmd">Week 2 (Aug 27, 30)</a></p>

<p><a href="week3.qmd">Week 3 (Sep 3, 6)</a></p>

<p><a href="week4.qmd">Week 4 (Sep 10, 12)</a></p>

<p><a href="week5.qmd">Week 5 (Sep 17, 20)</a></p>

<p><a href="week6.qmd">Week 6 (Sep 24, 27)</a></p>

<p><a href="week7.qmd">Week 7 (Oct 1, 4)</a></p>

<p><a style="pointer-events: none; cursor: default; color:#606060"href="week8.qmd">Week 8 (Oct 8, 11)</a></p>


:::

::: {.column width="50%"}

<p><a style="pointer-events: none; cursor: default; color:#606060"href="week9.qmd">Week 9 (Oct 15, 18)</a></p>

<p><a style="pointer-events: none; cursor: default; color:#606060"href="week10.qmd">Week 10 (Oct 22, 25)</a></p>

<p><a style="pointer-events: none; cursor: default; color:#606060"href="week11.qmd">Week 11 (Oct 29, Nov 1)</a></p>

<p><a style="pointer-events: none; cursor: default; color:#606060"href="week12.qmd">Week 12 (Nov 5, 8)</a></p>

<p><a style="pointer-events: none; cursor: default; color:#606060"href="week13.qmd">Week 13 (Nov 12, 15)</a></p>

<p><a style="pointer-events: none; cursor: default; color:#606060"href="week14.qmd">Week 14 (Nov 19, 22)</a></p>

<p style="color:#606060">Week 15 (Nov 26, 29): <b>No Classes</b></p>

<p><a style="pointer-events: none; cursor: default; color:#606060"href="week16.qmd">Week 16 (Dec 3, 6)</a></p>


:::

::::

### Software

Install the most recent versions of <a href="https://cran.r-project.org/">R</a> and <a href="https://www.rstudio.com/products/rstudio/download/">RStudio Desktop</a>.

Install the software program [JAGS](https://sourceforge.net/projects/mcmc-jags/files/).

<!-- <a href="https://github.com/">Github</a> ... still thinking about whether we will use -->

<!-- <br> -->

### Additionals

#### Notes
-   **To download lectures:** Go to lecture html. Click 'e'. This should connect all slides into one page. Right Click Mouse on page. Click 'Print". Choose printer "Adobe PDF"; might need Adobe Acrobat installed. 


#### Extras

- <a href="/classfiles/extras/Likelihood and MLE.r">Likelihood and MLE.r</a>

- <a href="/classfiles/extras/Matrix Algebra.r">Matrix Algebra.r</a>

- <a href="/classfiles/extras/Occupancy MaximumLikelihood.r">Occupancy Maximum Likelihood.r</a>


#### Labs

- **Brian's Deer lab**: <a href="/classfiles/deerlab/RI-Deer-Sampling_BDG.html">html</a> and
<a href="/classfiles/deerlab/RIDeerRmd.BDG.zip">Zip</a>.




### Co-lead Discussion

- Students will be grouped and assigned a topic (e.g., mark-recapture). 

- Each group should pick an application paper (ideally) or methods paper (if desired) that is published on the assigned topic for the class to read. 

- Please send the paper (pdf) to me via email **2 weeks** before the topic is listed on the <a href="schedule.qmd">Schedule</a>; I will then post the paper on the website under the class prior to the discussion date.

- The group should come prepared to lead the discussion on the paper for (20-25 minutes). Assign questions for us to focus on or come prepared with questions to lead the discussion. Generally focus on things like...

  - what is the statistical model
  - did the authors define it clearly or reference another paper
  - the type of data that is relevant
  - how the sampling was achieved
  - the inference/prediction that was sought
  - how the model was used to answer the fundamental research question
  - nuisances of issues of concern in the modeling or sampling
  - try and connect principles/stastistics in the paper to what we have been doing in the class


## Assigned Groups

**Species Distribution Model (10/8):** 		Libby Mojica, Travis Rainey		
**Mark Recapture (10/11):**		Alex Badeaux, Noel Clark, Elke Tukker		
**N mixture or Integrated Data Models (10/22):**	Sarah Gaulke, Sean Ingram		
**Animal Movement (10/25):**		Jeremy Alder, Becca Windell		
**Habitat Selection (11/1):**		Waverly Davis,  Lisa Roerk		
**Community Modeling (11/12):**		Cat Adams, Bijoya Paul		


### Project

-   Work individually or in a group of 2

-   Decide on whether you will work on a 1) research project or 2) develop a short lecture along with a lab-case study.


### Learning 

:::: {.columns}

::: {.column width="30%"}

#### **Learning R**

-   [Language of R](https://bgerber123.github.io/R1day/#/the-language-of-r)
-   [Prelude In R](http://preludeinr.com/r-basics/)
-   [Data Carpentry](https://datacarpentry.org/R-ecology-lesson/)
-   [Intro to R](https://intro2r.com/)
-   [Many Resources](https://paulvanderlaken.com/2017/08/10/r-resources-cheatsheets-tutorials-books)
-   [Our Coding Club](https://ourcodingclub.github.io/tutorials/intro-to-r/)
-   [SW Carpentry](http://swcarpentry.github.io/r-novice-inflammation/)
-   [Doser et al. Book](https://www.jeffdoser.com/files/for875/_book/)
-   [Intro to R for Biologists](https://melbournebioinformatics.github.io/r-intro-biologists/intro_r_biologists.html#R_for_Biologists_course)
-   [Introduction to R - tidyverse](https://bookdown.org/ansellbr/WEHI_tidyR_course_book/)
-   [R for Data Science (2e)](https://r4ds.hadley.nz/)
-   [Advanced R](https://adv-r.hadley.nz/index.html)
-   [Introduction to the R Language](https://bookdown.org/mcwimberly/gdswr-book/introduction-to-the-r-language.html#matrices-and-lists)
-   [Introduction to R](https://bookdown.org/palmjulia/r_intro_script/introduction.html)
-   [An Introduction to R for Research](https://bookdown.org/rwnahhas/IntroToR/)
-   [Introduction to Data Exploration ana Analysis with R](https://bookdown.org/mikemahoney218/IDEAR/)
-   [Working with Data in R](https://bookdown.org/ejvanholm/WorkingWithData/)

:::

::: {.column width="10%"}
<!-- empty column to create gap -->
:::

::: {.column width="60%"}

#### **Learning Stats/Modeling**

-   [An Introduction to Statistical Learning](https://www.statlearning.com/)
-   [The Elements of Statistical Learning](https://hastie.su.domains/ElemStatLearn/). [Download](https://hastie.su.domains/ElemStatLearn/printings/ESLII_print12_toc.pdf).
-   [Bayesian Data Analysis](http://www.stat.columbia.edu/~gelman/book/). [Download](http://www.stat.columbia.edu/~gelman/book/BDA3.pdf).
-   [Bayesian Models: A Statistical Primer for Ecologists](https://press.princeton.edu/books/hardcover/9780691159287/bayesian-models).
-   [Data Analysis Using Regression and Multilevel/Hierarchical](http://www.stat.columbia.edu/~gelman/arm/)
-   [Statistics for Spatio-Temporal Data ](https://www.amazon.com/Statistics-Spatio-Temporal-Data-Noel-Cressie/dp/0471692743). [Download](https://download.e-bookshelf.de/download/0004/0172/80/L-G-0004017280-0009119041.pdf)
-   [Spatio-Temporal Statistics with R](https://spacetimewithr.org/). [Download](https://spacetimewithr.org/download)
-   [A First Course in Bayesian Statistical Methods](https://pdhoff.github.io/book/)
-   [Bayesian Statistical Methods](https://bayessm.wordpress.ncsu.edu/)

#### **Ecological Statistics**
-   [Ecological Models and Data in R](https://ms.mcmaster.ca/~bolker/emdbook/book.pdf)
-   [Animal Movement: Statistical Models for Telemetry Data](https://www.amazon.com/Animal-Movement-Statistical-Models-Telemetry/dp/1032097183)
-   [Mixed Effects Models and Extensions in Ecology with R](https://www.highstat.com/index.php?view=article&id=17&catid=18)
-   [Applied hierarchical modeling in Ecology](https://www.mbr-pwrc.usgs.gov/pubanalysis/keryroylebook/)
-   [Hierarchical Modeling in Ecology Books and Code](https://www.mbr-pwrc.usgs.gov/pubanalysis/roylebook/index.html)
-   [Population Ecology in Practice](https://www.amazon.com/Population-Ecology-Practice-Brett-Sandercock/dp/0470674148). [Download](https://batrachos.com/sites/default/files/pictures/Eco_Books/Murray_Sandercock_2020.pdf)



#### **Computational Statistics**
-   [Computational Statistics](https://www.stat.colostate.edu/computationalstatistics/)
-   [Parameter Redundancy and Identifiability](https://www.routledge.com/Parameter-Redundancy-and-Identifiability/Cole/p/book/9780367493219)
-   [Bringing Bayesian Models to Life](https://www.amazon.com/Bringing-Bayesian-Chapman-Environmental-Statistics/dp/0367198487)


:::

::::



:::




