---
title: ""
---

## Week 16

### Day 1

#### [Today]{style="color:red;"}

##### Presentations

- Noel Clark

- Libby Mojica

- Sean Ingram

- Alex Badeaux


### Day 2 

#### [Today]{style="color:red;"}

##### Presentations

- Travis Rainey

- Bijoya Paul

- Waverly Davis

- Lisa Roerk

- Becca Windell

- Sarah Gaulke

- Cat Adams

- Jeremy Alder

- Elke Tukker


##### Class Wrap-up Discussion

1. Relative to where you were before the class started,

- rank your knowledge of statistics in wildlife ecology
- rank your comfort with statistics in wildlife ecology
- rank your interest with statistics in wildlife ecology
- rank your coding knowledge


2. What is one thing you learned that was useful to you?

3. What is something you would like to dive more into?

4. Rank the course difficulty relative to other graduate-level classes?

5. Rank the work load relative to other 3 credit graduate-level classes?

6. Regarding class organization, what do you recommend changing?

7. Regarding any aspect of the class, what do you think could be changed to improve your experience?

