---
title: "Integrated Data Model Lab"
author: "Name"
date: "Date"
output: html_document
---

<style type="text/css">

body, td {
   font-size: 16px;
}
code.r{
  font-size: 16px;
}
pre {
  font-size: 16px
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

In Chapter 20 of Kery and Kellner, 2024 they presented three data sets for the  Common Swift:

- Dataset 1: Counts
- Dataset 2: Zero-truncated Counts
- Dataset 3: Presence Absences

These data along with a standardized covariate (`selev`) can be found in the file `three.data.sets`; this loads an object called `data` which is a list of three elements, each corresponding to the above datasets. None of these datasets consider under-detection, i.e., detection probability. The authors of the book chapter make note of this issue. In lab, we fit separate models to each dataset - see files in the folder `2. Separate Models`. We then fit a joint data model or integrated species distribution model - see files in the folder `3. Integrated Model`. 
Following this, we reconsidered `Counts (Dataset 1)`, where instead we had replicated counts for each site, such that we can then account for detection probability. In the folder `4 N.Mixture Model`, we fit an N-mixture model to these replicated count data; these data are stored in the file `count.rep` (Dataset 1b). In the folder `5. Occupancy`, we reconsidered Presence Absences (Dataset 3) as replicated detection non-detection. We fit an occupancy model to these data to incorporate detection probability; these data are stored in the file `det.nondet` (Dataset 3b)

# Assignment

I would like you to fit an integrated data model that combines three datasets, one or two of which are the replicated counts (file `count.rep`) and/or the replicated detection non-detections (file `det.nondet`). The options are to combine data and fit a single model to one of these combinations: 

- Counts (Dataset 1), Zero-truncated Counts (Dataset 2), and det.nondet (Dataset 3b)
- count.rep (Dataset 1b), Zero-truncated Counts (Dataset 2), and Presence Absences (Dataset 3)
- count.rep (Dataset 1b), Zero-truncated Counts (Dataset 2), and det.nondet (Dataset 3b)

Our goal is to model the effect of the standardized covariate `selev` on the population abundance of Common Swifts (the covarite is provided for each dataset), and estimate a joint posterior of the intercept and slope. Essentially, you are fitting the same model done in folder `3. Integrated Model`, but now are accounting for detection probability with 1 or 2 of your datasets. For any detection probability models, estimate this as a constant parameter, i.e., do not include a covariate effect on detection probability. 


## Things to do

Create a R Markdown file that shows the model fitting code, JAGS model, and results, as specified here....

  - Modify the JAGS model from the folder ``3. Integrated Model` by replacing the likelihood portion of the submodel you want to remove and include the likelihood portion of the submodel you want to add (from the JAGS model in the folder `4 N.Mixture Model` or `5. Occupancy`).
  
  - Adapt the model fitting script from folder  ``3. Integrated Model` to load in the appropriate datasets and to fit your new integrated data model.
  
  - Evaluate posterior convergence by plotting parameter traceplots for `beta0` (intercept) and `beta1` (slope of selev) and derive the Gelman-Rubin convergence statistic (also known as $\hat{R}$).
  
  - Plot the posterior distributions of  `beta0` and `beta1`. 
  


