---
title: <center>FW670 <br> Wildlife Ecology Modeling <br> (Fall 2026)</center>
format: html
---
## Course Stuff
```{=html}
<title>Schedule</title>
<style type="text/css">

code.r{
  font-size: 30px;
}
</style>

<a href="/FW670/CourseOverview.qmd">Course Overview</a></p>
```

**Readings**: Come prepared to discuss the assigned reading on the next class after the readings were assigned. 

- What was interesting and useful? What did not make sense? What did you disagree with? What did you learn? <span style="color:red">Bring points to highlight and bring questions (make a list). Check each week's link to see if there are listed reading questions.</span>

**Labs**: are started in class on the day they are listed under and any relevant lab assignment is due one week later, unless otherwise stated.

## Schedule 

Week                              |	Day|	Date   | 	Lecture Topic                          | Assignments       |	   Readings                  |	Background Materials                           
--                                | -- | --------  |---------------------                  | ----------------  |--------------------------     |------------------                                  
<a href="/FW670/week1.qmd">1</a>  | Mo | 24-Aug	 | Class Intro                             | Discussion Post   | Zitomer et al. 2022; Wolcott et al. 2019  |                                     
&nbsp;                            |	Fr | 28-Aug	 | Big Picture                             | Lab 1: Sampling   | Betts et al. 2022; Dumelle et al. 2021; Williams and Brown 2019 | Shmueli 2010; Arif and MacNeil 2022
<a href="/FW670/week2.qmd">2</a>  |	Mo | 31-Aug	 | Probability Functions                   | Probability Quiz  | Kery and Kellner Ch. 2.0-2.4          |   Hobbs and Hooten Ch.3; Bolker Ch. 4   
&nbsp;                            | Fr | 4-Sep	 | Probability Functions                   | Lab 2: Simulation & Prob. Functions   |   Kery and Kellner Ch. 2.5-2.6              | 	Fieberg Ch. 10; Bolker Ch. 6    
<a href="/FW670/week3.qmd">3</a>  |	Mo | ~~7-Sep~~	 | Likelihood / Optimization           |                   | Dushoff et al. 2019; Fieberg, Ch. 1.10    |  Fieberg Ch. 1; Bolker Ch. 7; Zurr et al. Ch. 2   
&nbsp;                            |	Fr | 11-Sep	 | Regression                              | Lab 3: Regression |                               |                                
<a href="/FW670/week4.qmd">4</a>  |	Mo | 14-Sep	 | GLM I                                   |                   | Zurr and Iano, 2016           |                                
&nbsp;                            |	Fr | 18-Sep	 | GLM II                                  | Lab 4: GLM        | Fieberg, Ch. 8; Tredennick et al. 2021  |                                
<a href="/FW670/week5.qmd">5</a>  |	Mo | 21-Sep	 | Modeling Strategies                     |                   |                               | Gelman and Hill Ch. 11 and 12              
&nbsp;                            |	Fr | 25-Sep	 | Hierarchical Models / GLMM              | Lab 5: GLMM       | Kery and Kellner Ch. 2.7-2.10 |                                
<a href="/FW670/week6.qmd">6</a>  |	Mo | 28-Sep	 | Bayesian Inference                      |                   | Ellison 2004                  | Hobbs and Hooten Ch.5.;Fieberg Ch. 11 & 12 
&nbsp;                            |	Fr | 2-Oct	 | Bayesian Inference and Computation      | Lab 6: Bayes; <br>Bayes Quiz  |                   |  Kurz, 2023                                
<a href="/FW670/week7.qmd">7</a>  |	Mo | 5-Oct	 | Hierarchical Bayesian                   |                   |                               |                                            
&nbsp;                            |	Fr | 9-Oct	 | Hierarchical Bayesian                   | Lab  7; <br>Nothing to submit | Widmer et al 2021; Guillera-Arroita et al. 2015 | Soley-Guardia et al. 2024; Valavi et al. 2021 
<a href="/FW670/week8.qmd">8</a>  |	Mo | 12-Oct	 | Species Distribution Modeling           |                   | Kery and Schaub Ch 7          |                                             			
&nbsp;                            |	Fr | 16-Oct	 | Mark Recapture                          | Lab 8: CJS        | Royle et al. 2018             |                                             			
<a href="/FW670/week9.qmd">9</a>  |	Mo | 19-Oct	 | Spatial Capture Recapture               |                   | Kery and Schaub Ch 13         |                                            
&nbsp;                            |	Fr | 23-Oct	 | Hierarchical Bayesian Occupancy         | Lab 9:<br>HB Occu.| Zipkin and Saunders 2018; Zipkin et al. 2021; Powell and Gale Ch 18  |
<a href="/FW670/week10.qmd">10</a>| Mo | 26-Oct  | N-Mixture and Integrated Data Models    |                   | McCaffery et al. 2016; Kery and Kellner Ch20         |                                               
&nbsp;                            | Fr | 30-Oct	 | Integrated Data Models                  | Lab 10: ISDM      | Wittemyer et al. 2019; Huggler et al. 2022                               	
<a href="/FW670/week11.qmd">11</a>| Mo | 2-Nov	 | Animal Movement                         |                   |                               | Nathan et al 2008 and 2022; Signer et al 2018; and more  
&nbsp;                            | Fr | 6-Nov	 | Animal Movement                         | Lab 11: AMT; <br>Nothing to submit | Smith et al. 2022; Northrup et al. 2022|
<a href="/FW670/week12.qmd">12</a>| Mo | 9-Nov	 | Habitat Selection                       |                   | Draft guidance paper          |              
&nbsp;                            | Fr | 13-Nov	 | Habitat Selection                       | Lab 12: HabSel    | Wright et al 2020             |              
<a href="/FW670/week13.qmd">13</a>| Mo | 16-Nov	 | Community Modeling                      |                   |                               |              
&nbsp;                            | Fr | 20-Nov	 |                                         | Lab 13:           |                           |              
<a href="/FW670/week14.qmd">14</a>| Mo | 23-Nov	 | <span style="color:red">No Class</span> |                   |                               |              
&nbsp;                            | Fr | 27-Nov	 | <span style="color:red">No Class</span> |                   |                               |              
15                                | Mo | 30-Nov	 |  Group Project work|                    |                   |              
&nbsp;                            | Fr | 4-Dec	 | Group Project work  |                   |                   |              
<a href="/FW670/week16.qmd">16</a>| Mo | 3-Dec	 | Present Group Project                   |                   |                               |              
&nbsp;                            | Fr | 6-Dec	 | Present Group Project                   |                   |                               |              
