---
title: ""
---

## Week 7

### Day 1

#### [Today]{style="color:red;"}

-   Please bring your laptop today

-   Board work for statistical notation and JAGS syntax for Bayesian generalized linear models

- Download data: [Annamite Rabbit Data](/classfiles/hbayes/rabbit.occ.data.csv)

- Code example of fitting this model in <a href="/classfiles/hbayes/brms.fit.glm.r"> brms.fit.glm.r</a>

<!-- Note for Brian- today plan on writing the statistical notation for the Annamite rabbit model as a Bayesian GLM. Help write the 
the JAGS notation to fit this model and ask the students to write the code and fit this model. Examine convergence. Do this model in JAGS
and brms. JAGS they develop. brms run through the code -->

<!-- What  I did. 10/6/2026 - I started with the GLMM lab and explained the difference in notation with random intercept, random slope, and both. We talked about convergence issues of both and which one represented the hypothesis the most -->

-   Install R packages:

```{r, eval=FALSE, echo=TRUE}
# CRAN packages
install.packages(c("brms","bayesplot"))
```

#### [Assigned]{style="color:red;"}
 
 
### Day 2 (lab)

#### [Today]{style="color:red;"}

-   Discuss Project

<!-- - <a href="/classfiles/1hbayes/Bayesian non hierarchical model.pdf">Statistical Notation for Bayesian Logistic Regression Model for Annamite Rabbits</a> -->

-   Board work for statistical notation and JAGS syntax for hierarchical Bayesian generalized linear models

-   Fit models specified on the board

<!-- -   No lab to turn in next week. -->

<!-- -   Downloads: <a href="/classfiles/hbayes/Bayesian.Hierarchical.Model.zip">Bayesian Hierarchical Model Files</a> -->

<!-- Notes for today. Expand on the Bayesian GLM model. First, write the syntax with the same model but with extra variance. Write out syntax for the hierarchical Bayesian GLM with fixed intercept and random slope. Then do the syntax for random intercept and random slope. Ask students to fit each of these models. They need to turn them into JAGS syntax. 
-->

-   Lab: Submit a markdown report that describes the model and results for the model with a fixed intercept and random slopes for dist.human by protected area. The report should inlcude,
    - statistical notation and JAGS syntax notation 
    - traceplots with text visually assessing posterior convergence. 
    - plots showing the posterior distributions (histograms or density plots) for each parameter. 
    - a table of estimates of the difference between the slope for each protected area and the overall mean slope across protected areas; 
      include a point estimate (mean/median/mode) and measures of uncertainty, e.g., Bayesian credible intervals, for each.

- Download: [Annamite Rabbit Data](/classfiles/hbayes/rabbit.occ.data.csv)

#### [Assigned]{style="color:red;"}

-   Readings for next class:
    -   [Burn et al. 2011](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0024165)



<!-- -   Readings for next class: -->
<!--     -   <a href="/readings/">Student led discussion paper</a> -->
<!--     -   <a href="/readings/Guillera‐Arroita et al. 2015.pdf">Guillera‐Arroita et al. 2015</a> -->

<!-- - Background Reading (not required): -->
<!--   - <a href="/readings/Soley-Guardia et al. 2024.pdf">Soley-Guardia et al. 2024</a> -->
<!--   - <a href="/readings/Valavi et al. 2021.pdf"> Valavi et al. 2021 (assessment of modeling methods)</a>. -->
<!--   - <a href="/readings/Moudry et al. 2024.pdf"> Moudry et al. 2024 (data considerations)</a>. -->



