---
title: ""
---

## Week 12

### Day 1

#### [Today]{style="color:red;"}

##### Discussion led by Galen and Cristina

##### Discussion led by Ryan and Lindsay

#### [Assigned]{style="color:red;"}
-   Readings for next class: 
    - <a href="/readings/Royle et al 2018.pdf">Royle et al. 2018</a>

- Background Reading (not required):
  - <a href="/readings/Borchers and Marques 2017.pdf">Borchers and Marques 2017</a>
  - <a href="/readings/Royle et al 2011.pdf">Royle et al 2011</a>

 
### Day 2 (lab)

#### [Today]{style="color:red;"}

##### **In Class Discussion of Royle et al. 2018**

- How are SCR data different than a typical capture-recapture study?

- What is an 'activity center'?

- What makes this model 'spatial'? Think about this assumption. When will it be appropriate or not to assume?

- What are the two components that control 'detection probability'?

- If using a SCR model, how might your sampling strategy change?

- What is the exact meaning of abundance in this type of model?

#####

-   Downloads: <a href="/classfiles/scrlab/scrlabfiles.zip">Lab Files</a>


-   Install R packages:

```{r, eval=FALSE, echo=TRUE}
# CRAN packages
install.packages(c("secr","sf"))
```

#### [Assigned]{style="color:red;"}
<!-- - <a href="/readings/Wright et al 2020.pdf">Wright et al 2020</a> -->







