---
title: ""
---

## Week 8

### Day 1

#### [Today]{style="color:red;"}

-   Please bring your laptop today

##### **In Class Discussion  led by Maddie and Camilla** [(Link)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0024165)

**Overview of paper’s goals and questions:**

- How would you describe what the models are actually predicting for each site? And what is it NOT?

- What are the different hierarchies in this approach/models? 

- The authors mentioned a few times that their data was non-random - how come? 

- What are some potential biases in the PIKE data collection that were mentioned?

- Can the data tell us anything - not true random sample, uneven effort, heterogeneous resources? Or does Bayes account for all that uncertainty (as the authors expect)?

- Does this adequately address the question with important conservation implications on the line/is it appropriate? 


**Bonus Questions:**

- (Fun question) What’s one term/phrase the paper used that Brian has mentioned personally disliking?

- What were the main takeaways regarding poaching trends and factors influencing poaching the authors felt comfortable inferring from their model results? 

- How did they handle baseline differences in countries and sites within countries? 

- African / Asian data: Should the authors split out the analysis?

  <br>
 
##### **In Class: Simulating and fitting a Bayesian GLMM**

#### [Assigned]{style="color:red;"}
 -   Readings for next class:
     - <a href="/readings/Betts et al. 2022.pdf">Betts et al. 2022</a>
     - <a href="/readings/Betts et al. 2020.pdf">Betts et al. 2020</a>
     - <a href="/readings/Latif et al. 2024.pdf">Latif et al. 2024</a>

 
### Day 2 (lab)

#### [Today]{style="color:red;"}

- Brian is absent today.

- No lab assigned.

##### **In Class Discussion:** Dr. Quresh Latif, research scientist from [Bird Conservancy of the Rockies](https://www.birdconservancy.org/about-us/staff/), will be visiting (10am-11:30am) to lead a discussion on his paper <a href="/readings/Latif et al. 2024.pdf">Designing count-based studies in a world of hierarchical models</a>.

**Some questions to think about**:

- How do "hierarchical models place greater demands on data"?
- What exactly is a "sub-model"?
- The authors distinguish between ecological processes and observation processes. Why is it important to model these processes separately, and what problems arise when they are confounded?
- Under what conditions does detectability confound estimation of environmental relationships?
- What advantages and disadvantages are there between data from unmarked and marked populations?
- What influences one's choice of 'population metric'? For example, how should researchers choose between abundance, density, occupancy, or occupancy dynamics as the primary population metric for a study?
- How can poor sampling design affect the validity of a hierarchical model, even when the statistical model appropriately accounts for imperfect detection?

##### **In Class Discussion:** Dr. Mattew Betts, Professor from Oregon State University [Department of Forest Ecosystems & Society](https://directory.forestry.oregonstate.edu/people/betts-matthew), will be visiting (11:45am-12:45am) to lead a discussion on his papers <a href="/readings/Betts et al. 2022.pdf">When are hypotheses useful in ecology and evolution?</a> and <a href="/readings/Betts et al. 2020.pdf">Squeezed by a habitat split</a>.

**Some questions to think about**:

- What is a dynamic occupancy model? Specifically what is 'settlement' and 'vacancy' in terms of the model and ecological meaning and why is this fundamentally different than modeling occupancy?

- How did the authors test whether ocean conditions and old-forest loss worked together to affect murrelet occupancy?

- How could murrelet movement between sites affect the model’s estimates of colonization and vacancy?

- What are the advantages and disadvantages of using AICc to compare the different models in this study?

- How did the authors ensure paramters converged?

#### [Assigned]{style="color:red;"}
-   Following the discussion, post on the discussion board on  [canvas](https://colostate.instructure.com/courses/228738/discussion_topics/2507933).
-   Readings for next class: 
    -   <a href="/readings/Darrah et al. 2018.pdf">Darrah et al. 2018</a>
    - <a href="/readings/Kery and Schaub Ch13.pdf">Kery and Schaub Ch13 (sections 13.1 to 13.4)</a>



