---
title: ""
---

## Week 2

### Day 1

#### [Today]{style="color:red;"}

-   Lecture: <a href="/FW670/Probability.qmd">Probability</a>

-   Lecture Code: <a href="/FW670/probability.R">Probability.R</a>

##### **In Class Discussion Questions for Betts et al. 2022**

-   Is the use of hypotheses in the literature changing?
-   When are hypotheses useful?
-   When are hypotheses not useful?
  
##### **In Class Discussion Questions for Dumelle et al. 2021 and Williams & Brown 2019**

-   What are the attributes and foundations of design-based sampling/inference?
-   What are the attributes and foundations of model-based sampling/inference?
-   How do you use these two ideas?
-   Any concerns of using or not using these ideas?

#### [Assigned]{style="color:red;"}

- [Probabiltiy Quiz on Canvas](https://colostate.instructure.com/courses/193678/quizzes)

-   Readings for next class: 
    - <a href="/readings/Kery and Kellner Chapter 2.pdf">Kery and Kellner Chapter 2 (sections 2.0-2.4)</a>

- Background Reading (not required): 
  - <a href="/readings/HobbsHooten_Ch_3.pdf"> Hobbs & Hooten Ch. 3</a>.  Section 3.4.
  - <a href="/readings/Bolker 2007 Chapter 4.pdf"> Bolker 2007 Ch. 4</a>. 

  
### Day 2 (lab)

#### [Today]{style="color:red;"}

- Lecture: Continue with <a href="/FW670/Probability.qmd">Probability</a>

- Downloads: <a href="/classfiles/problab/week2files.zip">Files</a>

#### [Assigned]{style="color:red;"}

-   Readings for next class: 
    - <a href="/readings/Kery and Kellner Chapter 2.pdf">Kery and Kellner Chapter 2 (sections 2.5-2.6)</a>
    - <a href="/readings/Dushoff et al. 2019.pdf">Dushoff et al. 2019</a>
    - <a href="https://statistics4ecologists-v2.netlify.app/linreg#hypothesis-tests-and-p-values">Fieberg, Chapter 1.10</a>



```{r, eval=FALSE, echo=TRUE}
# To use code from Stats4Ecologists, you will need to install the package from GitHub,
# This requires devtools
  install.packages("devtools")
  devtools::install_github("jfieberg/Data4Ecologists")

# You may need a Personal Acces Token (PAT), If you know your token, you can enter it like this
  devtools::install_github("username/repo", auth_token = "your_token_here")

# To Generate a PAT
  usethis::create_github_token()
  gitcreds::gitcreds_set() # Choose #2 and "Replace these credentials", eventually copy/paste token (long string) from the Github website
```

- Background Reading on the Likelihood and Optimization (not required): 
  - [Bolker Ch. 6](/readings/Bolker 2007 Chapter 6.pdf) 
  - [Bolker Ch. 7](/readings/Bolker 2007 Chapter 7.pdf) 
  - [Fieberg Ch. 10](https://statistics4ecologists-v3.netlify.app/10-maximumlikelihood) 

 - Background Reading on regression (not required): 
  - [Fieberg, Ch. 1](https://statistics4ecologists-v2.netlify.app/linreg) 
  - [Zurr Ch. 2](/readings/Zurr et al Chapter 2.pdf)

