---
title: "Study Design / Simulation Assignment (Option 1)"
author: "Brian D. Gerber"
date: "2023-07-30"
output: html_document
---

<style type="text/css">
  body{
  font-size: 14pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### **Objective**: To evaluate study design tradeoffs between sample size and deer density. 

Evaluate random sampling designs with **3** sample sizes (10, 20, and 40) when the mean density of deer per square kilometer is 1 and 20. Make a sample size recommendation for each deer density, given the state wildlife agency is interested in minimizing costs while being highly certain (90%) that the total population estimate is within 10% of the true total population. Assume that each additional sample costs the same additional cost.


All Scenarios

-   Deer density is 1, sample size 1
-   Deer density is 1, sample size 2
-   Deer density is 1, sample size 3
-   Deer density is 20, sample size 1
-   Deer density is 20, sample size 2
-   Deer density is 20, sample size 3

### **Markdown**

Prepare a report (code and findings), using markdown that presents your findings using text and figures. 

#### Include

- A recommendation on the sample size you would suggest to go with and why. Provide evidence.

- Evaluate bias or relative bias of the mean estimator under all scenaiors. Explain your findings. Is it expected? Is it a concern?


#### Notes

You do not need to show all possible code. Show code that you think is essential for someone to understand your simulation study (e.g. no need to show plotting code). Try to avoid showing the same code in different places to keep the document from getting out of hand (i.e., long).

- **Suggestion 1**: For the markdown file, do not run the simulation every time you create/knit the document. Do the simulation, save the results, and load the results in the markdown file. You can include your code in the outputted markdown file by specifying eval=FALSE and echo=TRUE.

- **Suggestion 2**: Consider making an analysis script that outputs all your results into 1 or multiple files. Then use a plotting script to develop the plots you are interested. Then, start writing the markdown file that loads you results and plots only the things you want to show.

<br>
<br>

