---
title: ""
---

## Applied Sampling for Wildlife/Fish Studies (FW552)

<p><a href="Syllabus.qmd">Syllabus</a></p>

<p><a href="schedule.qmd">Schedule (Subject to Change)</a></p>

::: {.panel-tabset}


### Weeks 

:::: {.columns}

::: {.column width="50%"}

<p><a href="week1.qmd">Week 1 (Aug 25, 27)</a></p>

<p><a href="week2.qmd">Week 2 (Sep 1, 3)</a></p>

<p><a href="week3.qmd">Week 3 (Sep 8, 9)</a></p>

<p><a href="week4.qmd">Week 4 (Sep 15, 17)</a></p>

<p><a href="week5.qmd">Week 5 (Sep 22, 24)</a></p>

<p><a href="week6.qmd">Week 6 (Sep 29, Oct 1)</a></p>

<p><a href="week7.qmd">Week 7 (Oct 6, 8)</a></p>
<!-- <p>Week 7 (Oct 6, 8)</p> -->

<p><a href="week8.qmd">Week 8 (Oct 13, 15)</a>: <b>No Classes</b></p>

<!-- <p>Week 8 (Oct 13, 15)</p> -->
<!-- <p><a style="pointer-events: none; cursor: default; color:#606060"href="week8.qmd">Week 8 (Oct 8, 11)</a></p> -->

<p><a href="week9.qmd">Week 9 (Oct 20, 22)</a></p>
<!-- <p>Week 9 (Oct 20, 22)</p> -->



:::

::: {.column width="50%"}

<!-- <p><a href="week11.qmd">Week 10 (Oct 27, OCt 29)</a></p> -->
<p>Week 10 (Oct 27, Oct 29)</p>

<!-- <p><a href="week11.qmd">Week 11 (Nov 3, 5)</a></p> -->
<p>Week 11 (Nov 3, 5)</p>

<!-- <p><a href="week12.qmd">Week 12 (Nov 10, 12)</a></p> -->
<p>Week 12 (Nov 10, 12)</p>

<!-- <p><a href="week13.qmd">Week 13 (Nov 17, 19)</a></p> -->
<p>Week 13 (Nov 17, 19)</p>

<p><a href="week14.qmd">Week 14 (Nov 24, 26)</a>: <b>No Classes</b></p>
<!-- <p>Week 14 (Nov 24, 26)</p> -->

<!-- <p><a href="week15.qmd">Week 15 (Dec 1, 3)</a></p> -->
<p>Week 15 (Dec 1, 3)</p>

<p><a href="week16.qmd">Week 16 (Dec 8, 10)</a></p>
<!-- <p>Week 16 (Dec 8, 10)</p> -->

:::

::::

### Software

Install the most recent versions of <a href="https://cran.r-project.org/">R</a> and <a href="https://www.rstudio.com/products/rstudio/download/">RStudio Desktop</a>.

<!-- <a href="https://github.com/">Github</a> ... still thinking about whether we will use -->

<!-- <br> -->

### Additional

#### Notes
-   **To download lectures:** Go to lecture html. Click 'e'. This should connect all slides into one page. Right Click Mouse on page. Click 'Print". Choose printer "Adobe PDF"; might need Adobe Acrobat installed. 


#### Extras

- <a href="/classfiles552/ThompsonChapter3/CI_inclass_script.R">CI_inclass_script.R (for loop)</a>
- <a href="/classfiles552/ThompsonChapter3/CI_inclass_script_fn.R">CI_inclass_script_fn.R (function)</a>

#### Labs

<!-- ### Co-lead Discussion -->

<!-- - Students will be grouped and assigned a topic (e.g., mark-recapture).  -->

<!-- - Each group should pick an application paper (ideally) or methods paper (if desired) that is published on the assigned topic for the class to read.  -->

<!-- - Please send the paper (pdf) to me via email **2 weeks** before the topic is listed on the <a href="schedule.qmd">Schedule</a>; I will then post the paper on the website under the class prior to the discussion date. -->

<!-- - The group should come prepared to lead the discussion on the paper for (20-25 minutes). Assign questions for us to focus on or come prepared with questions to lead the discussion. Generally focus on things like... -->

<!--   - what is the statistical model -->
<!--   - did the authors define it clearly or reference another paper -->
<!--   - the type of data that is relevant -->
<!--   - how the sampling was achieved -->
<!--   - the inference/prediction that was sought -->
<!--   - how the model was used to answer the fundamental research question -->
<!--   - nuisances of issues of concern in the modeling or sampling -->
<!--   - try and connect principles/stastistics in the paper to what we have been doing in the class -->


<!-- ## Assigned Groups -->

<!-- **Species Distribution Model (10/8):** 		Libby Mojica, Travis Rainey		 -->
<!-- **Mark Recapture (10/11):**		Alex Badeaux, Noel Clark, Elke Tukker		 -->
<!-- **N mixture or Integrated Data Models (10/25):**	Sarah Gaulke, Sean Ingram		 -->
<!-- **Animal Movement (10/29):**		Jeremy Alder, Becca Windell		 -->
<!-- **Habitat Selection (11/5):**		Waverly Davis,  Lisa Roerk		 -->
<!-- **Community Modeling (11/12):**		Cat Adams, Bijoya Paul		 -->


<!-- ### Project -->

<!-- #### **Project Type** -->

<!-- Decide on whether you will work on a **1)** independent research project or **2)** develop a short lecture or lab case study on a statistical methodology. Research projects are individual, while a lecture/lab case study can be a team of 2-3 people.  -->

<!-- Once decided, individually (for a research project) or as a group (case study), email me a one paragraph synopsis of your plan and topic of choice. <span style="color:purple"><b>Please do this by October 25. </b></span> I will followup if I have any questions. -->

<!-- ##### **Independent Research Project** -->

<!-- Conduct a quantitative-focused project, such as a statistical analysis of data, or simulation based investigation. If you are unsure of whether your idea fits, come talk with me. If you want to use data from your graduate research, that would be great, but no need to use all of it or for exactly the purpose of your project. Simplifying the data and analysis is good and appropriate.  -->

<!-- *Objectives:* -->

<!-- - Write a report; this should be turned in <span style="color:purple"><b>December 6 (last day of classes).</b></span>  -->

<!-- - Present findings in class as an [ignite talk](https://www.ignitetalks.io/); i.e., a 5 minute long presentation with 20 slides and with the slides advancing automatically every 15 seconds. <span style="color:purple"><b>Presentations will be on December 3 and 6.</b></span>  -->

<!-- Prepare a report via R Markdown that generally follows the sections of 1) idea/hypothesis/setup, 2) data explanation, sampling methodology, and modeling, 3) results, and 4) summary/conclusions.  -->

<!-- In Canvas, please submit the compiled HTML, as well as all other files needed to knit this file. -->

<!-- This class is focused on  statistical models and model fitting, so make sure to emphasize the specifics of the statistical model that is being used and how it is being fit.  -->

<!-- This report does not have to be long, but it should be clear and well presented. Part of the grade will be your focus on communicating the data/model/results visually and via clear statistical language.  -->

<!-- ##### **Lecture/Lab Case Study ** -->

<!-- *Objective:* -->

<!-- - Create a lecture, R code lab, or hybrid centered around a quantitative approach relevant to wildlife ecology and conservation. -->

<!-- For example, 1) develop a lecture on a specific statistical model, 2) a lab walk through implementing the model and important nuances to consider, or 3) some mixture of these. -->

<!-- Aim for the lecture/lab to be around 25-30 minutes. <span style="color:purple"><b>Presentations will be on December 3 and 6</b></span>. Please submit the final materials on Canvas by <span style="color:purple"><b>December 6 (last day of classes).</b></span>  -->

<!-- Evaluation will be based on the clarity and organization of the materials presented and the preparedness of the instructors in engaging with the class.  -->

### Learning

:::: {.columns}

::: {.column width="30%"}

#### **Articles**

-   [Probability Does Not Exist](/readings/Prob.not.exist.pdf)
-   [Public Trust in Scientists](/readings/PublicDistrustScientists.pdf)

#### **Learning R**

-   [Language of R](https://bgerber123.github.io/R1day/#/the-language-of-r)
-   [Prelude In R](http://preludeinr.com/r-basics/)
-   [Data Carpentry](https://datacarpentry.org/R-ecology-lesson/)
-   [Intro to R](https://intro2r.com/)
-   [Many Resources](https://paulvanderlaken.com/2017/08/10/r-resources-cheatsheets-tutorials-books)
-   [Our Coding Club](https://ourcodingclub.github.io/tutorials/intro-to-r/)
-   [SW Carpentry](http://swcarpentry.github.io/r-novice-inflammation/)
-   [Doser et al. Book](https://www.jeffdoser.com/files/for875/_book/)
-   [Intro to R for Biologists](https://melbournebioinformatics.github.io/r-intro-biologists/intro_r_biologists.html#R_for_Biologists_course)
-   [Introduction to R - tidyverse](https://bookdown.org/ansellbr/WEHI_tidyR_course_book/)
-   [R for Data Science (2e)](https://r4ds.hadley.nz/)
-   [Advanced R](https://adv-r.hadley.nz/index.html)
-   [Introduction to the R Language](https://bookdown.org/mcwimberly/gdswr-book/introduction-to-the-r-language.html#matrices-and-lists)
-   [Introduction to R](https://bookdown.org/palmjulia/r_intro_script/introduction.html)
-   [An Introduction to R for Research](https://bookdown.org/rwnahhas/IntroToR/)
-   [Introduction to Data Exploration ana Analysis with R](https://bookdown.org/mikemahoney218/IDEAR/)
-   [Working with Data in R](https://bookdown.org/ejvanholm/WorkingWithData/)

:::

::: {.column width="10%"}
<!-- empty column to create gap -->
:::

::: {.column width="60%"}

#### **Learning Stats/Modeling**
-   [Probability Playground: Interactive Probability Distributions](https://www.acsu.buffalo.edu/~adamcunn/probability/probability.html)
-   [An Introduction to Statistical Learning](https://www.statlearning.com/)
-   [The Elements of Statistical Learning](https://hastie.su.domains/ElemStatLearn/). [Download](https://hastie.su.domains/ElemStatLearn/printings/ESLII_print12_toc.pdf).
-   [Bayesian Data Analysis](http://www.stat.columbia.edu/~gelman/book/). [Download](http://www.stat.columbia.edu/~gelman/book/BDA3.pdf).
-   [Bayesian Models: A Statistical Primer for Ecologists](https://press.princeton.edu/books/hardcover/9780691159287/bayesian-models).
-   [Data Analysis Using Regression and Multilevel/Hierarchical](http://www.stat.columbia.edu/~gelman/arm/)
-   [Statistics for Spatio-Temporal Data ](https://www.amazon.com/Statistics-Spatio-Temporal-Data-Noel-Cressie/dp/0471692743). [Download](https://download.e-bookshelf.de/download/0004/0172/80/L-G-0004017280-0009119041.pdf)
-   [Spatio-Temporal Statistics with R](https://spacetimewithr.org/). [Download](https://spacetimewithr.org/download)
-   [A First Course in Bayesian Statistical Methods](https://pdhoff.github.io/book/)
-   [Bayesian Statistical Methods](https://bayessm.wordpress.ncsu.edu/)

#### **Ecological Statistics**
-   [Ecological Models and Data in R](https://ms.mcmaster.ca/~bolker/emdbook/book.pdf)
-   [Animal Movement: Statistical Models for Telemetry Data](https://www.amazon.com/Animal-Movement-Statistical-Models-Telemetry/dp/1032097183)
-   [Mixed Effects Models and Extensions in Ecology with R](https://www.highstat.com/index.php?view=article&id=17&catid=18)
-   [Applied hierarchical modeling in Ecology](https://www.mbr-pwrc.usgs.gov/pubanalysis/keryroylebook/)
-   [Hierarchical Modeling in Ecology Books and Code](https://www.mbr-pwrc.usgs.gov/pubanalysis/roylebook/index.html)
-   [Population Ecology in Practice](https://www.amazon.com/Population-Ecology-Practice-Brett-Sandercock/dp/0470674148). [Download](https://batrachos.com/sites/default/files/pictures/Eco_Books/Murray_Sandercock_2020.pdf)



#### **Computational Statistics**
-   [Computational Statistics](https://www.stat.colostate.edu/computationalstatistics/)
-   [Parameter Redundancy and Identifiability](https://www.routledge.com/Parameter-Redundancy-and-Identifiability/Cole/p/book/9780367493219)
-   [Bringing Bayesian Models to Life](https://www.amazon.com/Bringing-Bayesian-Chapman-Environmental-Statistics/dp/0367198487)


:::

::::

:::




