---
  title: "Mid-term Exercise of Discovery"
---

## Interview 

#### Goal 
  - **Each student should reach out to a scientist in their field (not an advisor, not another student)**
  - if you say it is for a class, how could they refuse
  - context to provide: I am taking a 'Sampling' class and learning about inference, sampling variation, power analysis, and different sampling strategies. I was hoping to ask you a few questions how or if you use some of these concepts in your work. Ask for 30 minutes of their time.
  - Take notes.
  
  
#### Questions

- [Sampling question]{style="color:#078BCD;"}
  - do you use setup sampling frames before sampling? Do you use simple random sampling? What about more involved sampling, like cluster, adaptive cluster, stratified, or systematic? In what study and how did this help make inference?

- [Science Communication question]{style="color:#078BCD;"}
  - it is hard to communicate what a confidence interval. How do you communicate how people should think about them, for students but also for non-scientists?

- [Power analysis question]{style="color:#078BCD;"}
  - what are some ways you have done power analyses to guide your sample size questions for a given research question?
  
- [Wild card question]{style="color:#078BCD;"}  
  - you make one up. Something relevant to what you are learning in class
  - OR, ask whether they primarily use design- or model-based inference and why
  
  
#### Write-up

- write a discussion post on what you found out
  
#### Why do this

  - gain experience talking about these important topics 
  - connect with a (new) scientist in your field or department or program
  - make connections between class material and scientific practice
  - justify your time spent in this class (?)

  