---
title: ""
---

## Week 10

### [Day 1]{style="color:red;"}

#### **In Class**

- Lecture: <a href="/FW552/Ratio.qmd">Ratio Estimators</a> 
- Lecture Code: <a href="/FW552/Ratio.R">Ratio.R</a>

#### **Assigned**

A colleague collected data at two sites (study 1 and study 2). They are interested in the mean number of beetles in each plot. A sample size of n = 10 plots were randomly sampled from a sampling frame of N = 100 at each site. The colleague was also able to use GIS data products to classify the ground cover (auxiliary information) at all plots/units in the population to which they sampled. They asked you to help them estimate the population mean abundance and variance of beetles for each site. Use your knowledge of ratio estimators that makes use of auxillary information; secondly, use your knowledge of sample averages and variances from SRS that don't use auxiliary information. Compare the estimated mean and variances for both ways for each site. Please summarize your findings and your intuition as to why there are differences by method.

- [Data Download for Homework](../classfiles552/ThompsonChapter7/BeetleCover.Study.zip)

- **Due 1 week**: [Canvas Assignment](https://colostate.instructure.com/courses/212614/assignments/2900121)
- **Due Next Class**: Read <a href="/readings552/Collins2007.pdf">Collins 2007</a>
- **Please bring a laptop to next class**

### [Day 2]{style="color:red;"}

#### **In Class**

- **Please bring a laptop to class**

- *In Class Discussion of Collins 2007*

- *In class Exercise: Evaluate the benefit of the ratio estimator compared to a sample average. Compare the sampling distribution variance/standard deviation for both estimators as the correlation b/w x and y change.*

#### **Assigned** 

- **Due 1 week**: [Canvas Quiz 5 Assignment](https://colostate.instructure.com/courses/212614/assignments/2900121)

- **Due Next Class**: Read <a href="/readings552/nonresponse bias.pdf">Berg 2010</a>

- - **Please bring a laptop to next class**