---
title: ""
---

## Week 1

### [Day 1]{style="color:red;"}

#### **In Class**

-   Lecture: <a href="/FW552/Introduction.qmd">Introduction</a>

#### **Assigned | Due Next Class**

  - Read <a href="/readings552/Hankin Chapter 2.pdf">Hankin Chapter 2</a>
  - Read <a href="/readings552/Gerber et al. 2012.pdf">Gerber et al. 2012</a> 
  - [Discussion Post on Canvas](https://colostate.instructure.com/courses/212614/discussion_topics/2205317)


- **Please bring a laptop next class** with [R](https://www.r-project.org/) and [RStudio](https://posit.co/download/rstudio-desktop/) installed.

<hr style="border:2px solid gray">

### [Day 2]{style="color:red;"}

#### **In Class**

*In Class Discussion Questions of Gerber et al. 2012*

Apply your learning from Hankin Ch.2 (Basics Concepts) to Gerber et al. 2012

 - What was the target population?

 - What was the sampling frame?
 
 - What was the sampling selection method of the sample units? It might be useful to think of a fundamental sample unit and subsample units.
 
 - How would you characterize the generality of scientific learning from this study? Would you apply the knowledge gained to other individuals of the species?

*R and RMarkdown*

- Lecture: <a href="/FW552/IntroR.qmd">Intro to R</a>; <a href="/FW552/IntroR.R">Download R code</a>

- Markdown: <a href="/classfiles552/Name_HW_template.Rmd">Name_HW_template.Rmd</a>

#### **Assigned**

- **Due Next Class:** Read <a href="/readings552/Hankin Chapter 1.pdf">Hankin Chapter 1 </a>(sections 1.0. 1.1, and 1.5)
- **Due Next Class:** Read <a href="/readings552/Thompson Chapter 10.pdf">Thompson Chapter 10 </a> (sections 10.1 and 10.3) 
- **No specific due date / nothing to submit:** Walk through <a href="/classfiles552/R.Fundamentals.zip">Three scripts on R Fundamentals </a>. For additional help, see links under the `Learning` tab on <a href="https://bgerber123.github.io/FW552/">class website</a>. 



#### **Background Readings (not required)**

  - <a href="/readings552/Dumelle et al. 2022.pdf">Dumelle et al. 2022 </a> 
  - <a href="/readings552/Gregoire2011.pdf">Gregoire2011 </a> 


