---
title: ""
---

## Week 5

### Day 1

#### [Today]{style="color:red;"}

##### **In Class Discussion Questions for Fieberg, Ch. 8 and Tredennick et al. 2021**

- Summarize exploration, inference/explain, and prediction (Table 8.1) or Table 2

- What is stepwise selection? How does it perform?

- Why fit only one model? Drawbacks? How to decide on how many variables?

- What is AIC? 

- What is Regularization using penalization?

- "Model selection is the Black Hole of Statistics". What do you think?

- Covariate selection vs. model selection?

##### **In-Class Group Questions**

<a href="/classfiles/variableCombs/VariableCombs.Rmd">Variable Combinations</a>

#### [Assigned]{style="color:red;"}

- Background Reading (not required):
  - <a href="/readings/Gelman and Hill Chapters 11 and 12.pdf"> Gelman and Hill Ch. 11 and 12</a>.




<!-- #### [Assigned]{style="color:red;"} -->

<!-- -   Readings for next class:  -->
<!--     - <a href="/readings/Zurr and Iano 2016.pdf">Zurr and Iano, 2016</a> -->





### Day 2 (lab)

#### [Today]{style="color:red;"}

-   Lecture: <a href="/FW680A4/hierarchical.qmd">Hierarchical Models</a>

-   Downloads: <a href="/classfiles/glmmlab/week5files.zip">Files</a>

-   Install R packages:

```{r, eval=FALSE, echo=TRUE}
# CRAN packages
install.packages(c("glmmTMB","broom.mixed","lme4"))
```

#### [Assigned]{style="color:red;"}

  - <a href="/readings/Kery and Kellner Chapter 2.pdf"> Kery and Kellner Ch. 2, sections 2.7-2.10</a>.

