---
title: ""
---

## Week 12

### [Day 1]{style="color:red;"}

#### **In Class**

- Reading Discussion (Marshall and Book Chapter)
- Design an experiment to test whether a change in hunting season length increases harvest, hunter satisfaction, and decreases illegal poaching? Outline the essential design and sampling elements, how data will be collected, and list any uncontrolled factors.

*Discussion points*

- What is Marshall's main point on **inadequate** designs? Think of an example from your field.

#### **Assigned**

These papers are pretty short. Read Artelle before Mawdlsey.

- <a href="/readings552/Artelle et al 2018.pdf">Artelle et al 2018</a>
- <a href="/readings552/Mawdsley et al 2018.pdf">Mawdsley et al 2018</a>
- <a href="/readings552/Zeller et al 2024.pdf">Zeller et al 2024</a>


### [Day 2]{style="color:red;"}

#### **In Class**

- Reading Discussions 

*Discussion Items for Artelle/Mawdsley*

- Come with an opinion! on whether you think North American wildlife mgmt includes the "hallmarks of science"
- Identify the design and sampling elements

*Discussion Items for Zeller et al. 2024*

- Identify the essential design and sampling elements
- Were there control variables?
- How generalizable are the results?
- Do the results matter and if so, to who?

#### **Assigned** 

- **Due Next Class**: Read <a href="/readings552/Hone et al 2023.pdf">Hone et al 2023 </a>
