---
title: "Sex-segregated range use by black-and-white ruffed lemurs (Varecia variegata) in Ranomafana National Park, Madagascar"
type: "article"
author: "Andrea L Baden, Jelisa Oliveras, Brian D Gerber"
year: "2020"
publication: "Folia Primatologica"
doi: "https://doi.org/10.1159/000510965"
download: "../publications/Baden et al. 2020"
toc: false
categories:
  - mammal
  - Madagascar
  - home range
  - journal article
---

## Citation 

> Baden, A. L., Oliveras, J., & Gerber, B. D. (2020). Sex-segregated range use by black-and-white ruffed lemurs (Varecia variegata) in Ranomafana National Park, Madagascar. *Folia Primatologica*, 92(1), 12-34.

## Abstract

Ranging behavior is one important strategy by which nonhuman primates obtain access to resources critical to their biological maintenance and reproductive success. As most primates live in permanent social groups, their members must balance the benefits of group living with the costs of intragroup competition for resources. However, some taxa live in more spatiotemporally flexible social groups, whose members modify patterns of association and range use as a method to mitigate these costs. Here, we describe the range use of one such taxon, the black-and-white ruffed lemur (Varecia variegata), at an undisturbed primary rain forest site in Ranomafana National Park, Madagascar, and characterize sex differences in annual home range area, overlap, and daily distances traveled. Moreover, we characterize seasonal variability in range use and ask whether ranging behaviors can be explained by either climatic or reproductive seasonality. We found that females used significantly larger home ranges than males, though sexes shared equal and moderate levels of home range overlap. Overall, range use did not vary across seasons, although within sexes, male range use varied significantly with climate. Moreover, daily path length was best predicted by day length, female reproductive state, and sex, but was unrelated to climate variables. While the patterns of range use and spatial association presented here share some similarities with “bisexually bonded” community models described for chimpanzees, we argue that ruffed lemurs best conform to a “nuclear neighborhood” community model wherein nuclear (core) groups share the highest levels of home range overlap, and where these groups cluster spatially into adjacent “neighborhoods” within the larger, communally defended territory.