---
title: "Aggregating three sources of long-term trends of swallowsand martins to identify priority conservation areas in the GreatLakes region"
type: "article"
author: "Belotti, MC, Gerber, BD,  Zhao, W, Deng, Y, Simons, V, Perez, G, Kelly, J, Maji, S, Sheldon, D, and Horton, K"
year: "2025"
publication: "Journal of Applied Ecology"
doi: "https://doi.org/10.1111/1365-2664.70240"
download: "../publications/Belotti et al. 2025.pdf"
toc: false
categories:
  - avian
  - Bayesian
  - monitoring
  - journal article
  - species distribution
---

## Citation 

> Belotti, M. C. T. D., Gerber, B. D., Zhao, W., Deng, Y., Simons, V. F., Perez, G., Kelly, J. F., Maji, S., Sheldon, D., & Horton, K. G. (2025). Aggregating three sources of long-term trends of swallows and martins to identify priority conservation areas in the Great Lakes region. Journal of Applied Ecology, 00, e70240. https://doi.org/10.1111/1365-2664.70240

## Abstract

Long-term monitoring of bird populations across scales is important in evaluating conservation targets and creating effective conservation strategies. For nearly six decades, the Breeding Bird Survey (BBS) has served as the primary broad-scaled source of relative abundance trends of swallows and martins in North America. Recently, however, it has become possible to obtain breeding population trends using semi-structured eBird community science data. Moreover, weather surveillance radar data of swallow and martin roosting populations yield a third complementary source of trend information. Using results from these three approaches, we propose a novel method of spatially combining estimates of percent change per year into a probability of directional agreement and/or disagreement that describes (1) the direction of the trend within a given region, (2) the amount of evidence associated with the estimate and (3) how much uncertainty surrounds it. We focus our efforts on an area of high Hirundinidae concentration in the North American Great Lakes region and predict trends from 2012 to 2022. We found a high probability of agreement between all three sources about observed declines in swallow and martin trends in the region surrounding Lake Ontario and to the west of Lake Michigan. Focusing future research on these regions could improve our understanding of these declines and help build more targeted conservation initiatives.
Synthesis and applications. Our data integration methodology allows managers to identify regions that accumulate evidence of concerning trends across multiple wildlife monitoring schemes. These regions can thus be prioritized in conservation and management efforts. This approach can be generalized to other sources of long-term monitoring data of different species, at different stages of their annual cycle, in any geographic location.