---
title: "Forest degradation drives widespread avian habitat and population declines"
type: "article"
author: "Matthew G Betts, Zhiqiang Yang, Adam S Hadley, Adam C Smith, JosC)e S Rousseau, Joseph M Northrup, Joseph J Nocera, Noel Gorelick, Brian D Gerber"
year: "2022"
publication: "Nature Ecology & Evolution"
doi: "https://doi.org/10.1038/s41559-022-01737-8"
download: "../publications/Betts et al 2022.pdf"
toc: false
categories:
  - forest management
  - Bayesian
  - avian
  - monitoring
  - species distribution
  - journal article
---

## Citation 

> Betts, M.G., Yang, Z., Hadley, A.S. et al. Forest degradation drives widespread avian habitat and population declines. *Nat Ecol Evol* 6, 709.


## Abstract

In many regions of the world, forest management has reduced old forest and simplified forest structure and composition. We hypothesized that such forest degradation has resulted in long-term habitat loss for forest-associated bird species of eastern Canada (130,017???km2) which, in turn, has caused bird-population declines. Despite little change in overall forest cover, we found substantial reductions in old forest as a result of frequent clear-cutting and a broad-scale transformation to intensified forestry. Back-cast species distribution models revealed that breeding habitat loss occurred for 66% of the 54 most common species from 1985 to 2020 and was strongly associated with reduction in old age classes. Using a long-term, independent dataset, we found that habitat amount predicted population size for 94% of species, and habitat loss was associated with population declines for old-forest species. Forest degradation may therefore be a primary cause of biodiversity decline in managed forest landscapes.