---
title: "Squeezed by a habitat split: Warm ocean conditions and old‐forest loss interact to reduce long‐term occupancy of a threatened seabird"
type: "article"
author: "Matthew G Betts, Joseph M Northrup, Jennifer A Bailey Guerrero, Lindsay J Adrean, S Kim Nelson, Jennifer L Fisher, Brian D Gerber, Marie‐Sophie Garcia‐Heras, Zhiqiang Yang, Daniel D Roby, James W Rivers"
year: "2020"
publication: "Conservation Letters"
doi: "https://doi.org/10.1111/conl.12745"
download: "../publications/Betts et al 2020.pdf"
toc: false
categories:
  - avian
  - occupancy
  - climate
  - forest management
  - journal article
---

## Citation 

> Betts MG, Northrup JM, Guerrero JAB, et al. Squeezed by a habitat split: Warm ocean conditions and old-forest loss interact to reduce long-term occupancy of a threatened seabird. *Conservation Letters*. 2020; 13:e12745. https://doi.org/10.1111/conl.12745

## Abstract

Theory predicts that species requiring multiple habitat types simultaneously should have heightened sensitivity to anthropogenic pressures, yet tests of this prediction are especially rare. We tested whether breeding site occupancy of the threatened marbled murrelet (Brachyramphus marmoratus) was driven by the synergistic effects of nesting habitat loss in forests, and changing ocean conditions. We paired 70,700 murrelet surveys at 19,837 sites across 20 years from the Oregon Coast Range with annual data on the extent of old forest and biophysical ocean conditions. Dynamic occupancy models indicated that local murrelet colonization rates were strongly reduced during warm ocean conditions with low prey availability. Landscapes that contained more old forest and were closer to the ocean showed reduced rates of local extinction. Given predictions of accelerated ocean warming and increased global timber demand, our results suggest murrelets may continue to be imperiled by deterioration of the two habitats upon which they depend.