---
title: "Modeling co-occurrence between toxic prey and naïve predators in an incipient invasion"
type: "article"
author: "Kerry Brown, Zach Farris, Gabriel Yesuf, Brian Gerber, Fidisoa Rasambainarivo, Sarah Karpanty, Marcella Kelly, Jean Claude Razafimahaimodison, Eileen Larney, Patricia Wright, Steig Johnson"
year: "2016"
publication: "Biodiversity and Conservation"
doi: "https://doi.org/10.1007/s10531-016-1198-3"
download: "../publications/Brown et al. 2016.pdf"
toc: false
categories:
  - mammal
  - journal article
---

## Citation 

> Brown, K.A., Farris, Z.J., Yesuf, G. et al. Modeling co-occurrence between toxic prey and naïve predators in an incipient invasion. *Biodivers Conserv* 25, 2723–2741 (2016). https://doi.org/10.1007/s10531-016-1198-3

## Abstract

Biological invasions can represent important threats to endemic species, including those within the invaders’ food webs. The Asian common toad (Duttaphrynus melanostictus) was introduced to Madagascar in 2011. This introduction presents a potentially dangerous prey item to a relatively naïve, highly diverse endemic carnivore fauna. Using a multivariate niche modeling approach (background test), we assessed the predicted niche overlap between D. melanostictus and six endemic carnivores in eastern Madagascar. The overlap between this potential prey and predators was assessed on four environmental niche axes: temperature, precipitation, vegetation cover and elevation. Our results showed a mixture of niche overlap and divergence between D. melanostictus and the six carnivores for environmental axes tested. There was significant overlap with five of the carnivores on temperature and NDVI axes. On the precipitation axis, there was significant overlap between D. melanostictus with two species. Our results suggested that wide-ranging, locally rare carnivores may overlap extensively with D. melanostictus. The six carnivores that inhabit the eastern rainforest of Madagascar will likely share multiple, niche axes with this novel potential prey item. Species that eat the non-native common toad and are susceptible to its toxins are at conservation risk because their populations may not be robust enough to adapt quickly to this threat. We advocate closely monitoring these emerging interactions and suggest a preemptive conservation strategy for carnivores potentially at risk.