---
title: "Mammal responses to global changes in human activity vary by trophic group and landscape"
type: "article"
author: "Burton, A.C., Beirne, C., Gaynor, K.M. et al. "
year: "2024"
publication: "Nature Ecology and Evolution"
doi: "https://doi.org/10.1038/s41559-024-02363-2"
download: "../publications/Burton et al. 2024.pdf"
toc: false
categories:
  - camera trapping
  - mammal
  - journal article
---

## Citation 

> Burton et al. (2024). SNAPSHOT USA 2021: Mammal responses to global changes in human activity vary by trophic group and landscape. *Nature Ecology and Evolution*, 8, 924–935, https://doi.org/10.1038/s41559-024-02363-2.
.

## Abstract

Wildlife must adapt to human presence to survive in the Anthropocene, so it is critical to understand species responses to humans in different contexts. We used camera trapping as a lens to view mammal responses to changes in human activity during the COVID-19 pandemic. Across 163 species sampled in 102 projects around the world, changes in the amount and timing of animal activity varied widely. Under higher human activity, mammals were less active in undeveloped areas but unexpectedly more active in developed areas while exhibiting greater nocturnality. Carnivores were most sensitive, showing the strongest decreases in activity and greatest increases in nocturnality. Wildlife managers must consider how habituation and uneven sensitivity across species may cause fundamental differences in human–wildlife interactions along gradients of human influence.