---
title: "High individual variability in space use by translocated, imperiled New England cottontail (Sylvilagus transitionalis)"
type: "article"
author: "Wales Carter, Thomas J. McGreevy, Bill Buffum, Roland J. Duhaime, Nicholas T. Ernst, Dylan Ferreira, Thomas P. Husband, Brian C. Tefft, Andrea M. Petrullo, and Brian D. Gerber"
year: "2025"
publication: "Canadian Journal of Zoology"
doi: "https://doi.org/10.1139/cjz-2024-0170"
download: "../publications/Carter et al. 2025.pdf"
toc: false
categories:
  - habitat selection
  - forest management
  - home range
  - mammal
  - survival
  - journal article
---

## Citation 

> Carter, W, McGreevy, TJ, Buffum, B, Duhaime, RJ, Ernst, NT, Ferreira, D, Husband, TP, Tefft,BC, Petrullo, AM, and Gerber, BD. High individual variability in space use by translocated, imperiled New England cottontail (Sylvilagus transitionalis). Canadian Journal of Zoology.  https://doi.org/10.1139/cjz-2024-0170

## Abstract

Translocations are an established element of restoration plans for threatened species, but success in establishing new populations is often limited, highlighting the need for careful evaluation of translocation efforts. Variation among individuals may contribute to poorly placed translocations, particularly when there is variation in the spatial ecology of target species. As a test of this we investigated the spatial ecology of imperiled New England cottontail (Sylvilagus transitionalis Bangs, 1895) in Rhode Island, USA. We combined telemetry data with remotely-sensed vegetation data to evaluate the home ranges, resource selection, and survival of translocated cottontails at three sites, including one where we also tracked resident cottontails. Despite instances of alignment among individuals, we found a wide span of home range estimates and high individual variability on resource selection. Both of these results suggest that population-level inferences of translocated individuals may fail to capture important aspects of animal ecology at the individual level. Further, we found lower survival compared to residents at one of our sites and literature values for other resident populations. Our results suggest that there are benefits to considering variation among individuals when designing management plans to support translocations.