---
title: "High Similarity in Winter Diet between Imperiled New England Cottontail and Invasive Eastern Cottontail"
type: "article"
author: "Wales A Carter, Thomas J McGreevy Jr, Brian D Gerber, Amy E Mayer, Mary E Sullivan, Brian C Tefft, Thomas P Husband"
year: "2023"
publication: "Journal of Fish and Wildlife Management"
doi: "https://doi.org/10.3996/JFWM-22-015"
download: "../publications/Carter et al. 2023.pdf"
toc: false
categories:
  - journal article
  - mammal
---

## Citation 

> Carter, W. A., McGreevy Jr, T. J., Gerber, B. D., Mayer, A. E., Sullivan, M. E., Tefft, B. C., & Husband, T. P. (2023). High Similarity in Winter Diet between Imperiled New England Cottontail and Invasive Eastern Cottontail. *Journal of Fish and Wildlife Management*, 14(1), 62-74.

## Abstract

Ongoing declines in the imperiled New England cottontail Sylvilagus transitionalis have coincided with the introduction and expansion of the closely related eastern cottontail Sylvilagus floridanus. These paired population trends have led to the inference of competition between the two species. Competition between native and introduced species has often involved overlapping use of food resources, but limited effort has been spent to analyze the diets of New England cottontail and eastern cottontail and to evaluate the potential for resource competition. We used microhistologic analysis of fecal pellets to assess the winter diets of both species and we compared diet composition with available plant communities to evaluate their preferences for dietary items across southern New England and southeastern New York. We found no differences in diets between New England cottontail and eastern cottontail, although diets did differ between regions within the study area. Diet preferences also were consistent between the species and largely excluded nonnative plant genera. Our results demonstrate that these species are generalist herbivores and that there is high potential for competition for food resources in the winter between them, although the present lack of diet partitioning may indicate the presence of other factors limiting competition. This study highlights the need for careful evaluation of interactions between native and nonnative species, a prerequisite for developing conservation plans that appropriately account for interspecific competition.