---
title: "Elevated potential for intraspecific competition in territorial carnivores occupying fragmented landscapes"
type: "article"
author: "Pranav Chanchani, Brian D Gerber, Barry R Noon"
year: "2018"
publication: "Biological Conservation"
doi: "https://doi.org/10.1016/j.biocon.2018.08.017"
download: "../publications/Chanchani et al. 2018.pdf"
toc: false
categories:
  - forest management
  - Bayesian
  - survival
  - mammal
  - population
  - occupancy
  - journal article
---

## Citation 

> Wampole, E.M., Farris, Z.J., Razafy, P. and Gerber, B.D. (2023), Forest carnivores living on the edge with invasive predators. *Anim. Conserv.* https://doi.org/10.1111/acv.12926

## Abstract

The distribution of mammals is determined by a suite of endogenous and exogenous factors. In territorial, polygynous species like tigers (Panthera tigris), males often center their space-use around female territories, repelling competitors from these areas. Competition among males for females leads to increased mortality of both sexes and infanticide of unrelated cubs, which can lead to population declines. We hypothesized that increased territorial overlap among adult male tigers and elevated levels of inter and intra-sex competition would be manifest in populations with male-biased adult sex ratios (ASR). We also assessed whether inter-sex variation in adult survival or degree of habitat connectivity resulted in skewed ASR. We evaluated these hypotheses using camera trap data from three tiger populations occupying habitat patches with varying levels of connectivity and ASRs. Data were analyzed using multi-state occupancy models, where states were defined as habitat use by one or more male tigers in sites with and without female use. As predicted, in populations with male-biased or even ASR we found evidence for increased spatial overlap between male tigers, particularly pronounced in areas adjacent to female territories. Given parity in adult survival, habitat fragmentation likely caused male-biased ASR. Our results suggest that the persistence of small tiger populations in habitat patches with male-biased ASR may be significantly compromised by behavior-mediated endogenous demographic processes that are often overlooked. In habitat fragments with pronounced male biased ASR, population recovery of territorial carnivores may require timely supplementation of individuals to compensate for population losses from intraspecific competition.