---
title: "Day and night foraging of Red Knots (Calidris canutus) during spring stopover in Virginia, USA"
type: "article"
author: "Jonathan B Cohen, Brian D Gerber, Sarah M Karpanty, James D Fraser, Barry R Truitt"
year: "2011"
publication: "Waterbirds"
doi: "https://doi.org/10.1675/063.034.0309"
download: "../publications/Cohen et al 2011.pdf"
toc: false
categories:
  - avian
  - diel ecology
  - journal article
---

## Citation 

> Cohen, J. B., Gerber, B. D., Karpanty, S. M., Fraser, J. D., & Truitt, B. R. (2011). Day and night foraging of Red Knots (Calidris canutus) during spring stopover in Virginia, USA. *Waterbirds*, 34(3), 352-356.

## Abstract

Long-jump migrant shorebirds have brief windows during spring stopover to acquire the energy needed to complete migration. Red Knots (Calidris canutus) refueling on Horseshoe Crab (Limulus polyphemus) eggs in Delaware Bay can meet their energy needs foraging only by day. In nearby Virginia, thousands of Red Knots stop over, but primarily low-quality, hard-shelled prey are available. One tactic Red Knots may use to meet their energy demands with such prey might be to extend their foraging time by feeding at night. To estimate the length of the foraging day in Virginia, daylight feeding was studied during three spring stopover periods (2008 to 2010), and night feeding was studied in 2010. Red Knots foraged 76 ± 3 SE% of the time in 2008 and 2009 combined, and 59 ± 3% of the time in 2010, during 3-minute observations. In 2010, Red Knots foraged 51 ± 7% of the time during a continuous 7-h daytime observation and 77 ± 5% of the time during a continuous 8-h night time observation on the same island. Given constraints on energy intake, night foraging by Red Knots in Virginia may be necessary for birds to attain sufficient mass to complete migration.