---
title: "A model to inform management actions as a response to chytridiomycosis-associated decline"
type: "article"
author: "Sarah J Converse, Larissa L Bailey, Brittany A Mosher, W Chris Funk, Brian D Gerber, Erin Muths"
year: "2017"
publication: "EcoHealth"
doi: "https://doi.org/10.1007/s10393-016-1117-9"
download: "../publications/Converse et al 2017.pdf"
toc: false
categories:
  - amphibian
  - disease
  - decision making
  - occupancy
  - journal article
---

## Citation 

> Converse, S. J., Bailey, L. L., Mosher, B. A., Funk, W. C., Gerber, B. D., & Muths, E. (2017). A model to inform management actions as a response to chytridiomycosis-associated decline. *EcoHealth*, 14, 144-155. https://doi.org/10.1007/s10393-016-1117-9

## Abstract

Decision-analytic models provide forecasts of how systems of interest will respond to management. These models can be parameterized using empirical data, but sometimes require information elicited from experts. When evaluating the effects of disease in species translocation programs, expert judgment is likely to play a role because complete empirical information will rarely be available. We illustrate development of a decision-analytic model built to inform decision-making regarding translocations and other management actions for the boreal toad (Anaxyrus boreas boreas), a species with declines linked to chytridiomycosis caused by Batrachochytrium dendrobatidis (Bd). Using the model, we explored the management implications of major uncertainties in this system, including whether there is a genetic basis for resistance to pathogenic infection by Bd, how translocation can best be implemented, and the effectiveness of efforts to reduce the spread of Bd. Our modeling exercise suggested that while selection for resistance to pathogenic infection by Bd could increase numbers of sites occupied by toads, and translocations could increase the rate of toad recovery, efforts to reduce the spread of Bd may have little effect. We emphasize the need to continue developing and parameterizing models necessary to assess management actions for combating chytridiomycosis-associated declines.