---
title: "Contrasting effects of climate change on seasonal survival of a hibernating mammal"
type: "article"
author: "Line S Cordes, Daniel T Blumstein, Kenneth B Armitage, Paul J CaraDonna, Dylan Z Childs, Brian D Gerber, Julien GA Martin, Madan K Oli, Arpat Ozgul"
year: "2020"
publication: "Proceedings of the National Academy of Sciences"
doi: "https://doi.org/10.1073/pnas.1918584117"
download: "../publications/Cordes et al 2020.pdf"
toc: false
categories:
  - mammal
  - mark-recapture
  - climate
  - journal article
---

## Citation 

> Cordes, L. S., Blumstein, D. T., Armitage, K. B., CaraDonna, P. J., Childs, D. Z., Gerber, B. D., ... & Ozgul, A. (2020). Contrasting effects of climate change on seasonal survival of a hibernating mammal. *Proceedings of the National Academy of Sciences*, 117(30), 18119-18126.

## Abstract

Climate change is altering the seasonal environmental conditions to which animals have adapted, but the outcome may differ between seasons for a particular species. Demographic responses therefore need disentangling on a seasonal basis to make accurate forecasts. Our study shows that climate change is causing seasonally divergent demographic responses in a hibernating mammal. Continued climate change will likely have a positive effect on summer survival but a negative effect on winter survival. This potentially has wide-ranging consequences across other species occupying temperate to more extreme arctic and alpine habitats, which are also where the most rapid changes in climate are observed.