---
title: "Muskrat occurrence in Rhode Island shows little evidence of land use change driving declines"
type: "article"
author: "John G. Crockett, Charles Brown, Brian D. Gerber"
year: "2024"
publication: "Journal of Wildlife Management"
doi: "https://doi.org/10.1002/jwmg.22668"
download: "../publications/Crockett et al. 2024.pdf"
materials: "https://zenodo.org/doi/10.5281/zenodo.12208226"
toc: false
categories:
  - mammal
  - Bayesian
  - forest management
  - occupancy
  - journal article
  - monitoring
  - species distribution
---

## Citation 

> Crockett, J. G., C. Brown, and B. D. Gerber. 2024. Muskrat occurrence in Rhode Island shows little evidence of land use change driving declines. *Journal of Wildlife Management* e22668. https://doi.org/10.1002/jwmg.22668

## Abstract

Muskrat (Ondatra zibethicus) populations have been in apparent decline across their native range in North America for decades. Several hypotheses exist for the causes of these declines, including loss of wetlands. We used time-to-detection data from 925 surveys from 276 sites across Rhode Island, USA, between 2021–2023 to fit an occupancy model that related the probability of muskrat occupancy at a site to land cover classification. We found that muskrat occupancy was higher in areas with more open water, urban land cover, or a second-order or larger stream, and lower in areas with salt water. We estimated changes in wetland area throughout Rhode Island using the National Land Cover Database classifications from 2001 and 2019 and found a net loss in wetland cover of 219 ha. We calculated the distance between wetland patches in each of these periods and found that patches were closer together than the dispersal distance of muskrats, suggesting isolation is unlikely to be driving muskrat declines. Additionally, when we used our model to predict changes in muskrat occupancy between 2001 and 2019, both mean and median predicted occupancy changed by <0.005. These results indicate that muskrat declines are not driven by habitat loss, and suggest future research is needed that focuses on other hypothesized mechanisms of muskrat declines such as disease, declining habitat quality, predation, and competition.