---
title: "Integrated species distribution model using historical data shows decline in a common semi-aquatic mammal"
type: "article"
author: "John G. Crockett, Charles Brown, Brian D. Gerber"
year: "2025"
publication: "Animal Conservation"
doi: "https://doi.org/10.1111/acv.70036"
download: "../publications/Crockett et al. 2025.pdf"
materials: "https://doi.org/10.5281/zenodo.14827223"
toc: false
categories:
  - mammal
  - Bayesian
  - occupancy
  - journal article
  - monitoring
  - species distribution
---

## Citation 

> Crockett, J. G., C. Brown, and B. D. Gerber. 2025. Integrated species distribution model using historical data shows decline in a common semi-aquatic mammal. *Animal Conservation* 1–15. https://doi.org/10.1111/acv.70036.

## Abstract

Effective conservation requires an understanding of drivers of a species' distribution as well as long-term changes in their dis-tribution. In recent decades, advances in data collection and analysis have allowed researchers to integrate a wide range ofinformation to model species distributions, particularly by allowing presence-only data and detection-nondetection data to beformally combined in integrated species distribution models (ISDMs). However, these models are rarely used to investigate long-term trends, which are important in evaluating a species' status. Here, we use historical presence-only data of river otters (Lontracanadensis; 366 latrine locations from 1999 to 2007 and 105 locations of road-killed individuals recorded from 1999 to 2020) and919 detection-nondetection surveys from 230 sites between 2021 and 2023 to understand the current distribution of river ottersin Rhode Island, USA, as well as the changes in river otter distribution over the past two decades. We found that river otters werestrongly associated with key habitat features such as streams and water, positively associated with urban areas, and tolerant ofsome contaminants, such as lead. Furthermore, despite uncertainties in historical river otter occurrence, we found clear sup-porting evidence that river otter intensity of use had declined from 1999 to 2023. This decline occurred despite being protectedfrom harvest and in contrast to range expansions in other parts of the northeastern USA throughout the second half of the 20thcentury. Our results suggest the utility of this approach to detect declines in species for which historical data are available anda need for better understanding the cause of river otter declines. Where monitoring consists of opportunistically collected data,species conservation could benefit by continuing to collect these data as well as introducing designed surveys, as this would allowbetter integration of data types, improving trend estimation and reducing the amount of (typically more expensive) designedsurveys needed.