---
title: "Rapidly declining body size in an insectivorous bat is associated with increased precipitation and decreased survival"
type: "article"
author: "Christina M Davy, Valerie von Zuben, Piia M Kukka, Brian D Gerber, Brian G Slough, Thomas S Jung"
year: "2022"
publication: "Ecological Applications"
doi: "https://doi.org/10.1002/eap.2639"
download: "../publications/Davy et al. 2022.pdf"
toc: false
categories:
  - mark recapture
  - mammal
  - survival
  - journal article
---

## Citation 

> Davy, Christina M., Valerie von Zuben, Piia M. Kukka, Brian D. Gerber, Brian G. Slough, and Thomas S. Jung. 2022. “Rapidly Declining Body Size in an Insectivorous Bat is Associated with Increased Precipitation and Decreased Survival.” *Ecological Applications* 32(7): e2639. https://doi.org/10.1002/eap.2639

## Abstract

Reduced food availability is implicated in declines in avian aerial insectivores, but the effect of nutritional stress on mammalian aerial insectivores is unclear. Unlike birds, insectivorous bats provision their young through lactation, which might protect nursing juveniles when prey availability is low but could increase the energetic burden on lactating females. We analyzed a 15-year capture–mark–recapture data set from 5312 individual little brown myotis (Myotis lucifugus) captured at 11 maternity colonies in northwestern Canada, to test the hypothesis that nutritional stress is impacting these mammalian aerial insectivores. We used long-bone (forearm [FA]) length as a proxy for relative access to nutrition during development, and body mass as a proxy for access to nutrition prior to capture. Average FA length and body mass both decreased significantly over the study period in adult females and juveniles, suggesting decreased access to nutrition. Effect sizes were very small, similar to those reported for declining body size in avian aerial insectivores. Declines in juvenile body mass were only observed in individuals captured in late summer when they were foraging independently, supporting our hypothesis that lactation provides some protection to nursing young during periods of nutritional stress. Potential drivers of the decline in bat size include one or both of (1) declining insect (prey) abundance, and (2) declining prey availability. Echolocating insectivorous bats cannot forage effectively during rainfall, which is increasing in our study area. The body mass of captured adult females and juveniles in our study was lower, on average, after periods of high rainfall, and higher after warmer-than-average periods. Finally, survival models revealed a positive association between FA length and survival, suggesting a fitness consequence to declines in body size. Our study area has not yet been impacted by bat white-nose syndrome (WNS), but research elsewhere has suggested that fatter bats are more likely to survive infection. We found evidence for WNS-independent shifts in the body size of little brown myotis, which can inform studies investigating population responses to WNS. More broadly, the cumulative effects of multiple stressors (e.g., disease, nutritional stress, climate change, and other pressures) on mammalian aerial insectivores require urgent attention.