---
title: "Mammal responses to global changes in human activity vary by trophic group and landscape"
type: "article"
author: "Nicole D. DeFelice, Maureen M. Durkin, Peter Paton, and Brian D. Gerber"
year: "2024"
publication: "Journal of Field Ornithology"
doi: "https://doi.org/10.5751/JFO-00557-950406"
download: "../publications/DeFelice et al. 2024.pdf"
toc: false
categories:
  - camera trapping
  - avian
  - mammal
  - journal article
---

## Citation 

> DeFelice et al. (2024). Odor swamping did not deter mammalian predators from depredating shorebird nests on beaches. *Journal of Field Ornithology*, 95, 4,6, https://doi.org/10.5751/JFO-00557-950406.
.

## Abstract

Reducing the risk of declines to the threatened population of Piping Plovers (Charadrius melodus) along the Atlantic coast USA, is a priority for U.S. state and federal agencies. One of plover biologists’ key management goals is to reduce nest predation rates. We evaluated a novel non-lethal technique to deter mammalian nest predators by deploying chemically extracted bird odors at scent stations on beaches where Piping Plovers nest. Our goal was to decrease mammalian predator’s interest in plover nests by providing unrewarded bird odor at scent stations placed across the landscape. We conducted fieldwork at Trustom Pond National Wildlife Refuge (NWR) and Ninigret NWR and Conservation Area in Rhode Island, USA. The primary mammalian nest predators were coyote (Canis latrans), red fox (Vulpes vulpes), striped skunk (Mephitis mephitis), and Virginia opossum (Didelphis virginianus). From late March through early June (2022–2023), we applied the bird odors extracted from waterfowl and gulls on the beaches at scent stations every three days. We monitored scent stations with trail cameras to record the frequency of predator visits and length of time predators spent at scent stations. Overall, there was high interspecific and annual variation in the number of detections and the length of time mammalian predators spent at scent stations. Total site-level coyote detections declined during the study period at both sites in 2022, but not in 2023; no other species showed potential habituation to scent stations. Odors extracted from waterfowl were more effective in attracting predators, in particular those derived directly from uropygial glands. Overall, we did not document a decline in Piping Plover nest predation rates when we deployed scent stations compared to the two previous years at both sites. This non-lethal technique was not effective at deterring mammalian nest predators at beaches in Rhode Island, USA.