---
title: "When the wild things are: Defining mammalian diel activity and plasticity"
type: "article"
author: "Devarajan, K, Fidino, M, Farris, Z, 214 amazing authors, Gerber, BD. "
year: "2025"
publication: "Science Advances"
doi: "https://www.science.org/doi/10.1126/sciadv.ado3843"
download: "../publications/Devarajan et al 2025.pdf"
toc: false
categories:
  - camera trapping
  - mammal
  - diel ecology
  - Bayesian
  - journal article
---

## Citation 

> Devarajan et al. (2025). When the wild things are: Defining mammalian diel activity and plasticity. *Science Advances*, 11, eado3843, https://www.science.org/doi/10.1126/sciadv.ado3843.

## Abstract

Circadian rhythms are a mechanism by which species adapt to environmental variability and fundamental to understanding species behavior. However, we lack data and a standardized framework to accurately assess and compare temporal activity for species during rapid ecological change. Through a global network representing 38 countries, we leveraged 8.9 million mammalian observations to create a library of 14,587 standardized diel activity estimates for 445 species. We found that less than half the species’ estimates were in agreement with diel classifications from the reference literature and that species commonly used more than one diel classification. Species diel activity was highly plastic when exposed to anthropogenic change. Furthermore, body size and distributional extent were strongly associated with whether a species is diurnal or nocturnal. Our findings provide essential knowledge of species behavior in an era of rapid global change and suggest the need for a new, quantitative framework that defines diel activity logically and consistently while capturing species plasticity.