---
title: "Power Pole Density Informs Spatial Prioritization for Mitigating Avian Electrocution"
type: "article"
author: "James F. Dwyer, Rick E. Harness, Brian D. Gerber, Melissa A. Landon, Paul Petersen, Daryl D. Austin, Brian Woodbridge, Gary E. Williams, Duncan Eccleston"
year: "2016"
publication: "Journal of Wildlife Management"
doi: "https://doi.org/10.1002/jwmg.1048"
download: "../publications/Dwyer et al 2016.pdf"
toc: false
categories:
  - avian
  - prediction 
  - journal article
---

## Citation 

> Dwyer, J.F., Harness, R.E., Gerber, B.D., Landon, M.A., Petersen, P., Austin, D.D., Woodbridge, B., Williams, G.E. and Eccleston, D. (2016), Power pole density informs spatial prioritization for mitigating avian electrocution. *Jour. Wild. Mgmt.*, 80: 634-642. https://doi.org/10.1002/jwmg.1048

## Abstract

Raptor and corvid electrocutions cause continental conservation concerns for breeding, migrating, and wintering birds. Although concerns are widespread, mitigation is implemented primarily at local scales of individual electric utilities. By not considering landscape-scale patterns, conservation strategies may fail to focus mitigation where efforts are needed most. To enable resource managers to consider electrocution risk at larger scales, we developed a regional model of distribution power pole (pole) density in a grid of 1-km2 cells throughout Colorado and Wyoming. To do so, we obtained data on pole locations from a sample of electric utilities covering 31% of Colorado and Wyoming, and developed a predictive model of poles throughout the remainder of the 2 states. Pole density was influenced by road lengths, number of oil and gas wells, slope, development, and land cover. Poles were densest in areas with high road lengths, high numbers of wells, and relatively flat terrain, and in areas developed for agriculture or human residences. When model predictions are viewed together with species-specific habitat maps, locations where high pole densities overlap habitat suggest areas where mitigating electrocution risk could be prioritized. Communication between resource managers and local utilities could then clarify the poles that caused the highest risk to raptors from electrocution. Thus, the model provides a framework for systematic spatial prioritization in support of regional conservation planning to minimize electrocution of raptors and corvids. © 2016 The Wildlife Society.