---
title: "Power pole density and avian electrocution risk in the western United States"
type: "article"
author: "James F Dwyer, Brian D Gerber, Paul Petersen, William E Armstrong, Richard E Harness"
year: "2020"
publication: "Journal of Raptor Research"
doi: "https://doi.org/10.3356/0892-1016-54.2.93"
download: "../publications/Dwyer et al 2020.pdf"
toc: false
categories:
  - avian
  - journal article
  - prediction
---

## Citation 

> James F. Dwyer, Brian D. Gerber, Paul Petersen, William E. Armstrong, Richard E. Harness; Power Pole Density and Avian Electrocution Risk in the Western United States. *Journal of Raptor Research* 2020; 54 (2): 93–109. doi: https://doi.org/10.3356/0892-1016-54.2.93

## Abstract

Avian electrocutions on power poles affect raptor populations globally. Mitigation strategies in the USA are typically bottom-up, combining risk assessments for individual poles into a utility-specific avian protection plan. This approach is usually reactive, relying on incidental documentation of electrocutions for initiation, and can allow uncoordinated mitigation strategies among adjacent utilities. A top-down strategy may help solve both problems if maps identifying where distribution power poles occur were available for comparison to range maps for species at risk of electrocution. Range maps exist but pole location data are rarely publicly available in the USA. Pole-density models were previously created for Colorado and Wyoming, the Great Basin, and the Columbia Plateau because pole density can serve as a surrogate for electrocution risk. We used each of these models to predict pole densities throughout four additional areas: the Northwestern Plains, Southwestern Plains, Southwestern Plateaus, and parts of New Mexico not included in other modeled areas. We also applied the Colorado and Wyoming model to portions of the Uinta Basin and Wyoming Basin projecting from Colorado and Wyoming into Idaho and Utah. The Colorado and Wyoming model fit all areas better than other models, except parts of New Mexico not included in other modeled areas, where the Great Basin model fit best. Our model predictions facilitate assessment of pole density across much (2,573,746 km2) of the western USA. To assess whether the models are useful in predicting electrocutions, we compared predicted pole densities throughout White Sands Missile Range to locations of 59 avian electrocutions. Electrocutions occurred at low rates in cells with low predicted pole densities, and at higher rates in cells with moderate and high predicted pole densities. Because the models do not include species-specific information, they have the potential to be applicable to the conservation of a wide variety of species.