---
title: "When carnivores roam: temporal patterns and overlap among Madagascar's native and exotic carnivores"
type: "article"
author: "Zach Farris, Brian Gerber, Sarah Karpanty, Asia Murphy, Vonjy Andrianjakarivelo, Felix Ratelolahy, Marcella Kelly"
year: "2015"
publication: "Journal of Zoology"
doi: "https://doi.org/10.1111/jzo.12216"
download: "../publications/Farris et al 2015.pdf"
toc: false
categories:
  - mammal
  - Madagascar
  - diel ecology
  - camera trapping
  - invasive predators
  - journal article
---

## Citation 

> Farris, Z.J., Gerber, B.D., Karpanty, S., Murphy, A., Andrianjakarivelo, V., Ratelolahy, F. and Kelly, M.J. (2015), Activity patterns of Madagascar's carnivore community. *J Zool*, 296: 45-57. https://doi.org/10.1111/jzo.12216

## Abstract

Madagascar's Eupleridae carnivores are perhaps the least studied and most threatened family of Carnivora. Investigating potential direct and indirect competition among these native species and sympatric exotic carnivores is necessary to better direct conservation actions. From 2008 to 2013, we photographically surveyed a diverse rainforest landscape, comparing six native and three exotic carnivores' activity patterns throughout the diel cycle. We used hierarchical Bayesian Poisson analysis to describe the activity patterns of Madagascar's carnivore community, assessed effects of season and site on temporal activity patterns, and estimated coefficients of overlap between carnivore pairings to assess effects of body size and ecological niche on temporal overlap among native and exotic carnivores. We observed changes in temporal activity patterns across seasons particularly during the austral summer (hot–dry season) for four native and two exotic carnivores, including evidence of fossa Cryptoprocta ferox altering their temporal activity during their mating season (hot–dry season). We found evidence of high overlap between natives and exotics indicating the potential for increased interactions and competition. The greatest overlap in temporal activity occurred between both ring-tail Galidia elegans and brown-tail vontsira Salanoia concolor and exotic dogs Canis familiaris. Cr. ferox, falanouc Eupleres goudotii and spotted fanaloka Fossa fossana also overlapped in activity with the nocturnal, exotic Indian civet Viverricula indica. Cr. ferox avoided humans and Ca. familiaris across all seasons. Unexpectedly, carnivore body size and ecological niche were not important predictors of temporal overlap. Previous research has shown these native and exotic carnivores overlap spatially and these new findings of temporal overlap among native and exotic carnivores add urgency to the need to manage exotic carnivores across Madagascar.