---
title: "Exploring and interpreting spatiotemporal interactions between native and invasive carnivores across a gradient of rainforest degradation"
type: "article"
author: "Zach J Farris, Brian D Gerber, Sarah Karpanty, Asia Murphy, Erin Wampole, Felix Ratelolahy, Marcella J Kelly"
year: "2020"
publication: "Biological Invasions"
doi: "https://doi.org/10.1007/s10530-020-02237-1"
download: "../publications/Farris et al 2020.pdf"
toc: false
categories:
  - mammal
  - diel ecology
  - occupancy
  - camera trapping
  - journal article
---

## Citation 

> Farris, Z.J., Gerber, B.D., Karpanty, S. et al. Exploring and interpreting spatiotemporal interactions between native and invasive carnivores across a gradient of rainforest degradation. *Biol Invasions* 22, 2033–2047 (2020). https://doi.org/10.1007/s10530-020-02237-1

## Abstract

Studies of elusive carnivores often rely on passive sampling when investigating either spatial or temporal interactions. However, inference on behavioral mechanisms are usually lacking. We present an analysis that combines previously published spatial co-occurrence estimates and temporal kernel density estimates to explore spatiotemporal interspecific interactions. We do so by deriving a spatiotemporal value (STV) that is a relative measure of potential interaction in both niche dimensions, across a gradient of degradation, for rainforest carnivore pairs in Madagascar. We also use a conceptual framework to provide insight into the potential behavioral mechanisms of habitat selection. Of the six native and three invasive carnivores, we estimate the spatiotemporal interactions for twelve pairings, which range from no spatial/temporal relationship (n = 5) to spatiotemporal aggregation or segregation (n = 7). We visualized these spatiotemporal interactions along a fragmentation gradient and demonstrate that these interactions are not static, as STV overlap increases with increasing anthropogenic disturbance. Of the three invasive carnivores (free-ranging dogs Canis familiaris, cats Felis species, and small Indian civets Viverricula indica) the latter had the highest number of spatial occurrence (n = 4) and spatiotemporal overlap (n = 4) relationships with native carnivores. Our results highlight the potential for increasing direct and indirect interactions between native and invasive species as forest degradation and invasive predators increase. Our approach allows us to better understand adaptive behaviors, plasticity in temporal activity, community assemblage, and to develop targeted conservation strategies to manage ecological communities in rapidly changing ecosystems.