---
title: "Threats to a rainforest carnivore community: A multi-year assessment of occupancy and co-occurrence in Madagascar"
type: "article"
author: "Zach J. Farris, Brian D Gerber, Kim Valenta, Radoniaina Rafaliarison, Jean Claude Razafimahaimodison, Eileen Larney, Tsiky Rajaonarivelo, Zoavina Randriana, Patricia C. Wright, Colin A Chapman"
year: "2017"
publication: "Biological Conservation"
doi: "https://doi.org/10.1016/j.biocon.2017.04.010"
download: "../publications/Farris et al 2017.pdf"
toc: false
categories:
  - mammal
  - occupancy
  - camera trapping
  - invasive predator
  - journal article
---

## Citation 

> Seymour, A.S., Tarrant, M.R., Gerber, B.D., Sharp, A., Woollam, J. and Cox, R. (2017), Effects of El Niño on the population dynamics of the Malay civet east of the Wallace line. *J Zool*, 303: 120-128. https://doi.org/10.1111/jzo.12469

## Abstract

Protected areas (PA) aim to eliminate many of the threats that species face on the greater landscape. In the last three decades, PA's have expanded considerably; however, quantitative assessments of how well they have mitigated threats to habitat and biodiversity are very limited. Habitat bordering PA's and the wildlife that use it are threatened by a wide-range of anthropogenic pressures (e.g., edge effects, fragmentation, and introduced predators) and this situation is particularly acute for low-density, poorly studied carnivore communities. From 2010 to 2015, we photographically sampled within (contiguous forest) and bordering (degraded, fragmented forest) a UNESCO World Heritage rainforest PA in Madagascar - Ranomafana National Park (RNP). We investigated the effects of invasive predators, local people presence, and habitat quality on the endemic rainforest carnivore community using static, dynamic, and co-occurrence models. We found native carnivores to be absent or have a low probability of occurrence in degraded forest bordering the PA, while local people and dogs (Canis familiaris) had high occurrence. Madagascar's largest endemic carnivore, the fosa (Cryptoprocta ferox) and the much smaller ring-tailed vontsira (Galidia elegans), occurrence in RNP declined rapidly over six years; their strong co-occurrence with dogs suggests interspecific competition, direct aggression/mortality, or disease as the cause. We highlight the dangers posed to biodiversity, particularly carnivores, from anthropogenic pressures bordering PA's and present recommendations to address increased human and dog activity, including programs to control dogs and their impact on biodiversity.