---
title: "Spatio‐temporal overlap between a native and an exotic carnivore in Madagascar: evidence of spatial exclusion"
type: "article"
author: "Zach J Farris, Brian D Gerber, Sarah Karpanty, Felix Ratelolahy, Vonjy Andrianjakarivelo, Marcella J Kelly"
year: "2022"
publication: "Small Carnivores: Evolution, Ecology, Behaviour, and Conservation"
doi: "https://doi.org/10.1002/9781118943274.ch13"
download: "../publications/Farris et al. 2022.pdf"
toc: false
categories:
  - camera trapping
  - mammal
  - diel ecology
  - occupancy
  - book chapter
---

## Citation 

> Farris, Z. J., Gerber, B. D., Karpanty, S., Ratelolahy, F., Andrianjakarivelo, V., & Kelly, M. J. (2022). Spatio‐temporal overlap between a native and an exotic carnivore in Madagascar: evidence of spatial exclusion. *Small Carnivores: Evolution, Ecology, Behaviour, and Conservation*, 259-274.

## Abstract

The exclusion or local extirpation of native species by exotic or introduced carnivores is a burgeoning issue for conservation. Exotic carnivores may indeed present a serious threat as they have the potential to negatively influence and/or interact with native wildlife via exploitative or interference competition, intraguild predation and/or transmission of pathogens. So far, studies investigating co-occurrence have failed to include both a spatial and temporal component which is likely to lead to improper inference. Here, we used a novel approach to investigate the relationship between native and exotic carnivores across both space and time and provide insight on the spatial exclusion of the native spotted fanaloka, Fossa fossana (listed as Vulnerable by the IUCN), by the exotic small Indian civet, Viverricula indica , across Madagascar's eastern rainforest ecosystem. We combined both spatial (single-species and two-species occupancy analyses) and temporal (kernel density estimation) analyses to investigate potential spatio-temporal interactions across the landscape, comparing degraded and non-degraded forests. We found that the exotic Indian civet negatively influenced spotted fanaloka occupancy, which resulted in a strong decrease in occupancy across degraded forests. Further, spotted fanaloka occupancy decreased by 40% at sites where Indian civet were present, resulting in a strong lack of co-occurrence between these two species. Finally, we recorded strong spatio-temporal overlap during the nocturnal time period within degraded, patchy forests. As a result, we suggest that this reveals evidence of spatial exclusion of the spotted fanaloka. This novel approach provides a unique investigation across both space and time – allowing us to identify more accurately the precise locations where co-occurring carnivores are potentially interacting – and has wide-ranging implications for conservation managers working to address the negative impacts of exotic species on native wildlife.