---
title: "Microclimate mediates the strength and direction of avianbiotic interactions"
type: "article"
author: "Sarah Frey, Brian D. Gerber, Adam S. Hadley, Kankyu Kim, Madison Sutton, Nina C. Ferrari, and Matthew G. Betts"
year: "2026"
publication: "Ecography"
doi: "http://doi.org/10.1002/ecog.08313"
download: "../publications/Frey et al. 2026.pdf"
toc: false
categories:
  - avian
  - occupancy
  - climate
  - forest management
  - journal article
---

## Citation 

> Frey, S, Gerber, BD, Hadley, AS, Kim, H, Sutton, M, Ferrari, NC, and Betts, MG. Microclimate mediates the strength and direction of avian biotic interactions: a test of the stress-gradient hypothesis. *Ecography*. 2026; e08313. http://doi.org/10.1002/ecog.08313

## Abstract

Theory predicts that the strength and direction of species interactions can shift frombeing competitive in benign environments toward being facilitative in stressful envi-ronments. However, the environmental context dependency of species interactions hasrarely been tested in animal communities. We capitalized on a 15-year, landscape-scaledataset, collected annually in a relatively stable old-growth forest environment, to testthe long-held hypothesis that the strength and direction of species interactions mightbe mediated by climatic conditions. It is generally accepted that competitive and facili-tative interactions drive the distributions of many species, but are rarely included inclimate envelope models, and may partly explain poor predictive performance of spe-cies distribution models in the face of climate change. Using multi-species dynamicoccupancy models applied to long-term data, we tested whether annual settlementby bird species could affect either the persistence or settlement by other phylogeneti-cally related species, and whether these interactions are mediated by microclimate. Wefound that species interactions were influenced by microclimate for a high proportionof species pairs (80%). Related species pairs more often showed settlement dynamicsthat were indicative of attraction rather than repulsion (55 versus 30%, respectively).In some cases, competitive interactions in colder microclimates flipped to becomefacilitative in warmer ones (15%) and vice versa (5%). Furthermore, species pairsthat were closely related were more likely to exhibit competitive relationships along atleast part of the microclimatic gradient. Our results highlight the importance of usinglong-term data to incorporate competitive and facilitative interactions into species dis-tribution models, and support the notion that the strength and direction of speciesinteractions can be dependent on microclimatic conditions.