---
title: "Mammals adjust diel activity across gradients of urbanization"
type: "article"
author: "Travis Gallo, Mason Fidino, Brian Gerber, et al."
year: "2022"
publication: "Elife"
doi: "https://doi.org/10.7554/eLife.74756"
download: "../publications/Gallo et al 2022.pdf"
toc: false
categories:
  - diel ecology
  - mammal
  - camera trapping
  - journal article
---

## Citation 

> Gallo, Travis, Mason Fidino, Brian Gerber, Adam A. Ahlers, Julia L. Angstmann, Max Amaya, David Drake et al. Mammals adjust diel activity across gradients of urbanization. *Elife*, 11 (2022), e74756.https://doi.org/10.7554/eLife.74756    

## Abstract

Time is a fundamental component of ecological processes. How animal behavior changes over time has been explored through well-known ecological theories like niche partitioning and predator–prey dynamics. Yet, changes in animal behavior within the shorter 24-hr light–dark cycle have largely gone unstudied. Understanding if an animal can adjust their temporal activity to mitigate or adapt to environmental change has become a recent topic of discussion and is important for effective wildlife management and conservation. While spatial habitat is a fundamental consideration in wildlife management and conservation, temporal habitat is often ignored. We formulated a temporal resource selection model to quantify the diel behavior of 8 mammal species across 10 US cities. We found high variability in diel activity patterns within and among species and species-specific correlations between diel activity and human population density, impervious land cover, available greenspace, vegetation cover, and mean daily temperature. We also found that some species may modulate temporal behaviors to manage both natural and anthropogenic risks. Our results highlight the complexity with which temporal activity patterns interact with local environmental characteristics, and suggest that urban mammals may use time along the 24-hr cycle to reduce risk, adapt, and therefore persist, and in some cases thrive, in human-dominated ecosystems.