---
title: "Fisher activity patterns show potential for behavioral adaptations to human modified landscapes"
type: "article"
author: "Laken S. Ganoe, Amy E. Mayer, Charles Brown, Brian D. Gerber"
year: "2024"
publication: "Global Ecology and Conservation"
doi: "https://doi.org/10.1016/j.gecco.2024.e03225"
download: "../publications/Ganoe et al. 2024b.pdf"
toc: false
categories:
  - mammal
  - forest management
  - diel ecology
  - climate
  - journal article
---

## Citation 

> Ganoe, L.S., Mayer, A. E., Brown, C., and Gerber, B. D.. 2024. Fisher activity patterns show potential for behavioral adaptations to human modified landscapes. *Global Ecology and Conservation* e03225. https://doi.org/10.1016/j.gecco.2024.e03225

## Abstract

Animals alter their diel activity in response to physiological constraints and ecological conditions. Fisher (Pekania pennanti) activity is known to vary through the diel cycle and change in response to cold stress and generally through both the climatic and biological seasons. However, less is known whether thermoregulatory effects impact fisher activity in milder climates and in areas of high human disturbance. We focused on two distinct research objectives to understand the 1) physiological constraints, and 2) ecological components of fisher activity in a highly disturbed landscape with a relatively mild climate. We used accelerometer data from 34 individual live-captured fisher in Rhode Island, USA from 2021 to 2023. We found that fisher activity patterns were primarily driven by diel cycle with higher activity levels at night than during the day. We did not observe any physiological influence of ambient temperature on fisher activity; daily minimum temperatures did not constrain fisher activity in the colder months, nor did daily maximum temperatures in warmer months. We did find that female activity levels differed by breeding status with non-pregnant females having higher activity levels than pregnant females. Considering ecological components, we found fisher decreased activity levels in higher road density areas during warmer months that coincide with higher traffic volumes. For fisher living in areas with lower road densities, we saw higher activity in the breeding season and summer than in winter. In contrast, fisher living in areas with high road densities had lower activity in the breeding season and summer than in winter. We conclude that fisher largely do not shift their activity to mitigate thermoregulatory costs in areas where temperatures do not reach extremes for extended periods of time. However, our findings suggest that behavioral shifts in activity are impacted by human disturbance and fisher minimize activity in risky areas.
