---
title: "Individuality, diel time, and landscape context shape space-use of an elusive carnivore in a risky environment"
type: "article"
author: "Laken S. Ganoe, Joseph M. Northrup, Amy E. Mayer, Charles Brown, and Brian D. Gerber"
year: "2025"
publication: "Landscape Ecology"
doi: " https://doi.org/10.1007/s10980-025-02089-x"
download: "../publications/Ganoe et al. 2025.pdf"
toc: false
categories:
  - mammal
  - habitat selection
  - diel ecology
  - journal article
---

## Citation 

> Ganoe, L.S., Northrup, J.M., Mayer, A.E. et al. Individuality, diel time, and landscape context shape space-use of an elusive carnivore in a risky environment. Landsc Ecol 40, 81 (2025). https://doi.org/10.1007/s10980-025-02089-x

## Abstract
**Context**
Individual animal’s perception of risk can alter how it navigates a landscape altered by anthropogenic and natural disturbances. As perception depends on experience, we should expect habitat selection to be context dependent and individualistic.

**Objectives**
We hypothesized that: (i) fine-scale habitat selection of fisher (Pekania pennanti) in a human dominated landscape is driven by multiple interacting spatio-temporal factors; and (ii) an individual’s response to these factors depend on their exposure to anthropogenic disturbance within their home range (i.e., functional response).

**Methods**
We used fine-scale GPS location data of fisher in step-selection functions to make inference on the effects of human development, habitat loss, and road risk on fisher habitat selection.

**Results**
We found fisher habitat selection is individualistic, spatio-temporally dependent and a function of their exposure to anthropogenic disturbance in their home range. Fisher selected areas of lower road risk more frequently relative to availability, particularly during daylight hours. Higher road risk areas were only used more frequently when they were available at night. With a higher human land use in their home ranges fisher selected space near roads at night only, however when the extent of human use in their home range was lower, they selected areas further from roads at all times.

**Conclusions**
Our study shows how individual variability allows fisher to adapt their diel activity to utilize resources in areas of high human land use. This further emphasizes the importance of accounting for individuality and multiple interacting spatio-temporal factors in habitat selection, particularly in highly human modified landscapes.