---
title: "Extreme site fidelity as an optimal strategy in an unpredictable and homogeneous environment"
type: "article"
author: "Brian D. Gerber, Mevin B. Hooten, Christopher P. Peck, Mindy B Rice, James H. Gammonley, Anthony D. Apa, Amy J. Davis"
year: "2019"
publication: "Functional Ecology"
doi: "https://doi.org/10.1111/1365-2435.13390"
download: "../publications/Gerber et al 2019.pdf"
toc: false
categories:
  - mammal
  - journal article
---

## Citation 

> Gerber BD, Hooten MB, Peck CP, et al. Extreme site fidelity as an optimal strategy in an unpredictable and homogeneous environment. *Funct Ecol.* 2019; 33: 1695–1707. https://doi.org/10.1111/1365-2435.13390

## Abstract

Animal site fidelity structures space use, population demography and ultimately gene flow. Understanding the adaptive selection for site fidelity patterns provides a mechanistic understanding to both spatial and population processes. This can be achieved by linking space use with environmental variability (spatial and temporal) and demographic parameters. However, rarely is the environmental context that drives the selection for site fidelity behaviour fully considered.
We use ecological theory to understand whether the spatial and temporal variability in breeding site quality can explain the site fidelity behaviour and demographic patterns of Gunnison sage-grouse (Centrocercus minimus). We examined female site fidelity patterns across multiple spatial scales: proximity of consecutive year nest locations, space-use overlap within and across the breeding and brooding seasons, and fidelity to a breeding patch. We also examined the spatial and temporal variability in nest, chick, juvenile and adult survival.

We found Gunnison sage-grouse to be site faithful to their breeding patch, area of use within the patch and generally where they nest, suggesting an “Always Stay” site fidelity strategy. This is an optimal evolutionary strategy when site quality is unpredictable. Further, we found limited spatial variability in survival within age groups, suggesting little demographic benefit to moving among patches. We suggest Gunnison sage-grouse site fidelity is driven by the unpredictability of predation in a relatively homogeneous environment, the lack of benefits and likely costs to moving across landscape patches and leaving known lek and breeding/brooding areas.

Space use and demography are commonly studied separately. More so, site fidelity patterns are rarely framed in the context of ecological theory, beyond questions related to the win-stay:lose-switch rule. To move beyond describing patterns and understand the adaptive selection driving species movements and their demographic consequences require integrating movement, demography and environmental variability in a synthetic framework.
Site fidelity theory provides a coherent framework to simultaneously investigate the spatial and population ecology of animal populations. Using it to frame ecological questions will lead to a more mechanistic understanding of animal movement, spatial population structuring and meta-population dynamics.