---
title: "Evaluating the potential biases in carnivore capture–recapture studies associated with the use of lure and varying density estimation techniques using photographic-sampling data of the Malagasy civet"
type: "article"
author: "Brian D Gerber, Sarah M Karpanty, Marcella J Kelly"
year: "2011"
publication: "Population Ecology"
doi: "https://doi.org/10.1007/s10144-011-0276-3"
download: "../publications/Gerber et al 2011.pdf"
toc: false
categories:
  - mammal
  - Madagascar
  - mark recapture
  - population
  - journal article
---

## Citation 

> Gerber, B.D., Karpanty, S.M. & Kelly, M.J. Evaluating the potential biases in carnivore capture–recapture studies associated with the use of lure and varying density estimation techniques using photographic-sampling data of the Malagasy civet. *Popul Ecol* 54, 43–54 (2012). https://doi.org/10.1007/s10144-011-0276-3

## Abstract

Estimating density of elusive carnivores with capture–recapture analyses is increasingly common. However, providing unbiased and precise estimates is still a challenge due to uncertainties arising from the use of (1) bait or lure to attract animals to the detection device and (2) ad hoc boundary-strip methods to compensate for edge effects in area estimation. We used photographic-sampling data of the Malagasy civet Fossa fossana collected with and without lure to assess the effects of lure and to compare the use of four density estimators which varied in methods of area estimation. The use of lure did not affect permanent immigration or emigration, abundance and density estimation, maximum movement distances, or temporal activity patterns of Malagasy civets, but did provide more precise population estimates by increasing the number of recaptures. The spatially-explicit capture–recapture (SECR) model density estimates ±SE were the least precise as they incorporate spatial variation, but consistent with each other (Maximum likelihood-SECR = 1.38 ± 0.18, Bayesian-SECR = 1.24 ± 0.17 civets/km2), whereas estimates relying on boundary-strip methods to estimate effective trapping area did not incorporate spatial variation, varied greatly and were generally larger than SECR model estimates. Estimating carnivore density with ad hoc boundary-strip methods can lead to overestimation and/or increased uncertainty as they do not incorporate spatial variation. This may lead to inaction or poor management decisions which may jeopardize at-risk populations. In contrast, SECR models free researchers from making subjective decisions associated with boundary-strip methods and they estimate density directly, providing more comparable and valuable population estimates.