---
title: "Improving spatial predictions of animal resource selection to guide conservation decision making"
type: "article"
author: "Brian D Gerber, Joseph M Northrup"
year: "2020"
publication: "Ecology"
doi: "https://doi.org/10.1002/ecy.2953"
download: "../publications/GerberNorthrup2020.pdf"
toc: false
categories:
  - habitat selection
  - mammal
  - journal article
---

## Citation 

> Gerber, B. D., and J. M. Northrup. 2020. Improving spatial predictions of animal resource selection to guide conservation decision making. *Ecology* 101(3):e02953. 10.1002/ecy.2953

## Abstract

Resource selection is often studied by ecologists interested in the environmental drivers of animal space use and movement. These studies commonly produce spatial predictions, which are of considerable utility to resource managers making habitat and population management decisions. It is thus paramount that predictions from resource selection studies are accurate. We evaluated model building and fitting strategies for optimizing resource selection function predictions in a use-availability framework. We did so by simulating low- and high-intensity spatial sampling data that respectively predicted study area and movement-based resource selection. We compared one of the most commonly used forms of statistical regularization, Akaike's Information Criterion (AIC), with the lesser used least absolute shrinkage and selection operator (LASSO). LASSO predictions were less variable and more accurate than AIC and were often best when considering additive and interacting variables. We explicitly demonstrate the predictive equivalence using the logistic and Poisson likelihoods and how it is lost when the available sample is too small. Regardless of modeling approach, interpreting the sign of coefficients as a measure of selection can be misleading when optimizing for prediction.