---
title: "An assessment of carnivore relative abundance and density in the eastern rainforests of Madagascar using remotely-triggered camera traps"
type: "article"
author: "Brian Gerber, Sarah M Karpanty, Charles Crawford, Mary Kotschwar, Johnny Randrianantenaina"
year: "2010"
publication: "Oryx"
doi: "https://doi:10.1017/S0030605309991037"
download: "../publications/Gerber et al 2010.pdf"
toc: false
categories:
  - mammal
  - Madagascar
  - mark recapture
  - abundance
  - journal article
---

## Citation 

> Gerber B, Karpanty SM, Crawford C, Kotschwar M, Randrianantenaina J. An assessment of carnivore relative abundance and density in the eastern rainforests of Madagascar using remotely-triggered camera traps. *Oryx*. 2010;44(2):219-222. doi:10.1017/S0030605309991037

## Abstract

Despite major efforts to understand and conserve Madagascar’s unique biodiversity, relatively little is known about the island’s carnivore populations. We therefore deployed 43 camera-trap stations in Ranomafana National Park, Madagascar during June–August 2007 to evaluate the efficacy of this method for studying Malagasy carnivores and to estimate the relative abundance and density of carnivores in the eastern rainforest. A total of 755 camera-trap nights provided 1,605 photographs of four endemic carnivore species (fossa Cryptoprocta ferox, Malagasy civet Fossa fossana, ring-tailed mongoose Galidia elegans and broad-striped mongoose Galidictus fasciata), the exotic Indian civet Viverricula indica and the domestic dog Canis familiaris. We identified 38 individual F. fossana and 10 individual C. ferox. We estimated density using both capture-recapture analyses, with a buffer of full mean-maximum-distance-moved, and a spatially-explicit maximum-likelihood method (F. fossana: 3.03 and 2.23 km-2, respectively; C. ferox: 0.15 and 0.17 km-2, respectively). Our estimated densities of C. ferox in rainforest are lower than published estimates for conspecifics in the western dry forests. Within Ranomafana National Park species richness of native carnivores did not vary among trail systems located in secondary, selectively-logged and undisturbed forest. These results provide the first assessment of carnivore population parameters using camera-traps in the eastern rainforests of Madagascar.