---
title: "Considering transient population dynamics in the conservation of slow life-history species: An application to the sandhill crane"
type: "article"
author: "Brian Gerber, William Kendall"
year: "2016"
publication: "Biological Conservation"
doi: "https://doi.org/10.1016/j.biocon.2016.06.014"
download: "../publications/GerberKendall2016.pdf"
toc: false
categories:
  - avian
  - population 
  - journal article
---

## Citation 

> Gerber, B. D., & Kendall, W. L. (2016). Considering transient population dynamics in the conservation of slow life-history species: an application to the sandhill crane. *Biological Conservation*, 200, 228-239. https://doi.org/10.1016/j.biocon.2016.06.014

## Abstract

The importance of transient dynamics of structured populations is increasingly recognized in ecology, yet these implications are not largely considered in conservation practices. We investigate transient and long-term population dynamics to demonstrate the process and utility of incorporating transient dynamics into conservation research and to better understand the population management of slow life-history species; these species can be theoretically highly sensitive to short- and long-term transient effects. We are specifically interested in the effects of anthropogenic removal of individuals from populations, such as caused by harvest, poaching, translocation, or incidental take. We use the sandhill crane (Grus canadensis) as an exemplar species; it is long-lived, has low reproduction, late maturity, and multiple populations are subject to sport harvest. We found sandhill cranes to have extremely high potential, but low likelihood for transient dynamics, even when the population is being harvested. The typically low population growth rate of slow life-history species appears to buffer against many perturbations causing large transient effects. Transient dynamics will dominate population trajectories of these species when stage structures are highly biased towards the younger and non-reproducing individuals, a situation that may be rare in established populations of long-lived animals. However, short-term transient population growth can be highly sensitive to vital rates that are relatively insensitive under equilibrium, suggesting that stage structure should be known if perturbation analysis is used to identify effective conservation strategies. For populations of slow life-history species that are not prone to large perturbations to their most productive individuals, population growth may be approximated by equilibrium dynamics.