---
title: "Spatial Ecology of the Endangered Milne-Edwards’ Sifaka (Propithecus edwardsi): Do Logging and Season Affect Home Range and Daily Ranging Patterns?"
type: "article"
author: "Brian D Gerber, Summer Arrigo-Nelson, Sarah M Karpanty, Mary Kotschwar, Patricia C Wright"
year: "2012"
publication: "International Journal of Primatology"
doi: "https://doi.org/10.1007/s10764-011-9576-x"
download: "../publications/Gerber et al 2012c.pdf"
toc: false
categories:
  - mammal
  - Madagascar
  - journal article
---

## Citation 

> Gerber, B.D., Arrigo-Nelson, S., Karpanty, S.M. et al. Spatial Ecology of the Endangered Milne-Edwards’ Sifaka (Propithecus edwardsi): Do Logging and Season Affect Home Range and Daily Ranging Patterns?. *Int J Primatol* 33, 305–321 (2012). https://doi.org/10.1007/s10764-011-9576-x

## Abstract

Primates often live in human-altered habitats; Malagasy lemurs are no exception. It is important to understand if habitat alteration affects primates’ space use patterns across multiple spatial and temporal scales, as this drives population density. We quantified the daily, seasonal, and annual space-use of seven groups of Milne-Edwards’ sifaka (Propithecus edwardsi) living in unlogged and logged rain forest in Ranomafana National Park, Madagascar between December 2002 and November 2003. Concurrent data showed that sifakas consumed higher quality foods in the unlogged than in logged forests; thus we explored how space use patterns were related to energy use strategies. Sifaka groups in the logged rain forest traveled 7–13% less per day than groups in the unlogged rain forest, despite their larger home ranges (median: 46.12 and 23.52 ha, in the logged and unlogged forests, respectively). Sifakas may thus use an energy-minimizing strategy at the scale of the individual day but an energy-maximizing strategy at the annual home range scale. Sifakas exhibited fidelity to the home range across seasons, but their core area of use shifted considerably with season. We found no difference in population density between sites. However, given the interannual variability in sifaka foods, a multiyear study is needed to assess if energy strategies observed in this study are consistent across longer time periods. Our findings suggest that lemurs may persist in logged habitats by altering spatial use patterns; future work should attempt to quantify the threshold level of forest regeneration from logging that will allow lemurs to persist at similar densities as in unlogged forest.