---
title: "The impact of forest logging and fragmentation on carnivore species composition, density and occupancy in Madagascar's rainforests"
type: "article"
author: "Brian D. Gerber, Sarah M. Karpanty, Johny Randrianantenaina"
year: "2012"
publication: "Oryx"
doi: "https://doi:10.1017/S0030605311001116"
download: "../publications/Gerber et al 2012.pdf"
toc: false
categories:
  - mammal
  - Madagascar
  - abundance
  - mark recapture
  - journal article
---

## Citation 

> Gerber BD, Karpanty SM, Randrianantenaina J. The impact of forest logging and fragmentation on carnivore species composition, density and occupancy in Madagascar's rainforests. *Oryx*. 2012;46(3):414-422. doi:10.1017/S0030605311001116

## Abstract

Forest carnivores are threatened globally by logging and forest fragmentation yet we know relatively little about how such change affects predator populations. This is especially true in Madagascar, where carnivores have not been extensively studied. To understand better the effects of logging and fragmentation on Malagasy carnivores we evaluated species composition, density of fossa Cryptoprocta ferox and Malagasy civet Fossa fossana, and carnivore occupancy in central-eastern Madagascar. We photographically-sampled carnivores in two contiguous (primary and selectively-logged) and two fragmented rainforests (fragments <2.5 and >15 km from intact forest). Species composition varied, with more native carnivores in the contiguous than fragmented rainforests. F. fossana was absent from fragmented rainforests and at a lower density in selectively-logged than in primary rainforest (mean 1.38±SE 0.22 and 3.19±SE 0.55 individuals km−2, respectively). C. ferox was detected in fragments <2.5 km from forest and had similar densities in primary and selectively-logged forests (0.12±SE 0.05 and 0.09±SE 0.04 adults km−2, respectively) but was absent in fragments >15 km from forest. We identified only two protected areas in Madagascar that may maintain >300 adult C. ferox. Occupancy of broad-striped mongoose Galidictis fasciata was positively related to fragment size whereas occupancy of ring-tailed mongoose Galidia elegans elegans was negatively associated with increasing exotic wild cat (Felis spp.) activity at a camera site. Degraded rainforest fragments are difficult environments for Malagasy carnivores to occupy; there is a need to prioritize the reconnection and maintenance of contiguous forest tracts.