---
title: "Activity patterns of carnivores in the rain forests of Madagascar: implications for species coexistence"
type: "article"
author: "Brian D. Gerber, Sarah M. Karpanty, Johny Randrianantenaina"
year: "2012"
publication: "Journal of Mammalogy"
doi: "https://doi.org/10.1644/11-MAMM-A-265.1"
download: "../publications/Gerber et al 2012b.pdf"
toc: false
categories:
  - mammal
  - Madagascar
  - diel ecology
  - journal article
---

## Citation 

> Brian D. Gerber, Sarah M. Karpanty, Johny Randrianantenaina, Activity patterns of carnivores in the rain forests of Madagascar: implications for species coexistence, *Journal of Mammalogy*, Volume 93, Issue 3, 2012, Pages 667–676, https://doi.org/10.1644/11-MAMM-A-265.1

## Abstract

Temporal partitioning of activity among sympatric species can be an important mechanism for species coexistence. Further, if exotic and native species overlap temporally, there is potential for direct competition and antagonism, which may lead to native species extirpation. We 1st assessed if ecologically similar native carnivores of Madagascar demonstrated activity pattern overlap and then explored whether overlap in activity might lead to negative impacts of exotic carnivores on native carnivores. We used photographic sampling to quantify the temporal activity patterns of carnivores at 4 study sites. The activity of the 2 smaller-bodied native species, Galidia elegans and Galidictis fasciata, overlapped minimally; these 2 carnivores share a similar generalist diet, which may drive their divergent temporal activity. In contrast, the medium-sized native species, Fossa fossana and Eupleres goudotii, were both highly nocturnal; these 2 species appear segregated in their diets. The largest native carnivore, Cryptoprocta ferox, selectively used crepuscular hours, but overall was cathemeral; it was notably absent or basically so at sites where dogs were most abundant and active throughout the diel cycle. We found G. elegans to shift from preferred activity periods in the presence of dogs and the exotic Viverricula indica. Our results suggest that the presence and activity of exotic carnivores can negatively impact native carnivores in fragmented rain forests.