---
title: "Differential impacts of spruce beetle outbreaks on snowshoe hares and red squirrels in the southern Rocky Mountains"
type: "article"
author: "Jacob S Ivan, Eric S Newkirk, Brian D Gerber"
year: "2023"
publication: "Forest Ecology and Management"
doi: "https://doi.org/10.1016/j.foreco.2023.121147"
download: "../publications/Ivan et al. 2023.pdf"
toc: false
categories:
  - forest management
  - mark recapture
  - population
  - Bayesian
  - mammal
  - journal article
---

## Citation 

> Ivan, J. S., Newkirk, E. S., & Gerber, B. D. (2023). Differential impacts of spruce beetle outbreaks on snowshoe hares and red squirrels in the southern Rocky Mountains. *Forest Ecology and Management*, 544, 121147.

## Abstract

Spruce beetles (Dendroctonus rufipennis) have impacted millions of acres of Engelmann spruce (Picea engelmannii) – subalpine fir (Abies lasiocarpa) forest in North America over the past decade, resulting in the most extensive outbreak in recorded history. This dramatic alteration of forest composition and structure has precipitated numerous changes to forest ecology and ecosystem services. Among the least studied of these changes are impacts to wild mammals, including snowshoe hares (Lepus americanus) and red squirrels (Tamiasciurus hudsonicus). We sampled a chronosequence of spruce-fir stands along a gradient of ‘years elapsed since spruce beetle outbreak’ (YSO) in order to estimate impacts to abundance of these two species in the southern Rocky Mountains. Snowshoe hare abundance was not related to YSO, at least in the first decade post-outbreak. Instead, hare abundance during this period was positively related to horizontal cover, especially that due to stem density of small diameter subalpine fir. Notably, snowshoe hare abundance was negatively related to stem density of small diameter Engelmann spruce, suggesting that elements of horizontal cover may not be uniformly beneficial to hares. Hare abundance was also negatively related to ground cover, which could help explain the lack of relationship to YSO, assuming reduction in overstory canopy would lead to increases in ground cover. Red squirrel abundance was negatively related to YSO and outbreak severity (i.e., basal area of large diameter dead trees). This was likely due to diminished cone crops in impacted areas, which red squirrels cache and rely on heavily to sustain them through the winter. Basal area of remaining large live fir trees was not related to squirrel abundance, suggesting that regeneration of spruce and associated cone crops may be necessary for recovery of red squirrels, which may take several decades.