---
title: "White light reduces flight height of birds in low-density migration corridor"
type: "article"
author: "Miguel F. Jimenez, Carrie Ann Adams, Carolyn S. Burt, Brian D. Gerber, Jeremy White, Riana Zinn, Kyle G. Horton"
year: "2026"
publication: "Journal of Wildlife Management"
doi: "https://doi.org/10.1002/jwmg.70279"
download: "../publications/Jimenez et al.pdf"
toc: false
categories:
  - avian
  - journal article
---

## Citation 

> Jimenez, M. F., C. A. Adams, C. S. Burt, B. D. Gerber, J. White, R. Zinn, and K. G. Horton. 2026. White light reduces flight height of birds in low-density migration corridor. Journal of Wildlife Management e70279. https://doi.org/10.1002/jwmg.70279

## Abstract

Artificial light at night (ALAN) has been shown to influence the behavior of migratory birds, yet how different light spectra modulate these effects remains unclear. We conducted a field experiment for 31 nights at a remote site in northern Colorado, USA, using 2 800-W light-emitting diode (LED) floodlights with white, red, amber, and blue lighting treatments during fall migration in 2023 and 2024. Using a vertical-looking radar system, we quantified avian in-flight responses in migration traffic rate, flight height, and flight direction between paired control periods with no light and periods with lighting treatments. Although we found no effects of our treatments on migration traffic rate and weak effects on flight direction, we found that broad-spectrum white light with emissions across a 400–600 nm spectrum reduced mean avian flight height by an estimated 22.57 m (±10.53 SE) compared to dark periods, and this response was stronger than red and blue lighting treatments. Our ability to detect behavior changes from a point source in a rural, low-density migration system supports the notion that the effects of artificial light at night on bird behavior may be more pervasive than is often recognized, and that this varies by ALAN spectra. Beyond providing insight into avian orientation and in-flight behavior, our results have implications for future research, the conservation management of artificial light at night, and lighting designs that minimize effects on migratory birds.