---
title: "Climate, food and humans predict communities of mammals inthe United States"
type: "article"
author: "Kays, R., Snider, M. H., Hess, G., Cove, M. V., Jensen, A., Shamon, H., McShea, W. J., Rooney, B., Allen, M. L., Pekins, C. E., Wilmers, C. C., Pendergast, M. E., Green, A. M., Suraci, J., Leslie, M. S., Nasrallah, S., Farkas, D., Jordan, M., Grigione, M., … Parsons, A."
year: "2024"
publication: "Diversity and Distributions"
doi: "https://doi.org/10.1111/ddi.13900"
download: "../publications/Kays et al 2024.pdf"
toc: false
categories:
  - mammal
  - climate
  - population
  - journal article
---

## Citation 

> Kays, R., Snider, M. H., Hess, G., Cove, M. V., Jensen, A., Shamon, H., McShea, W. J., Rooney, B., Allen, M. L., Pekins, C. E., Wilmers, C. C., Pendergast, M. E., Green, A. M., Suraci, J., Leslie, M. S., Nasrallah, S., Farkas, D., Jordan, M., Grigione, M., … Parsons, A. (2024). Climate, food and humans predict communities of mammals in the United States. Diversity and Distributions, 00, e13900. https://doi.org/10.1111/ddi.13900

## Abstract

Aim
The assembly of species into communities and ecoregions is the result of interacting factors that affect plant and animal distribution and abundance at biogeographic scales. Here, we empirically derive ecoregions for mammals to test whether human disturbance has become more important than climate and habitat resources in structuring communities.

Location
Conterminous United States.

Time Period
2010–2021.

Major Taxa Studied
Twenty-five species of mammals.

Methods
We analysed data from 25 mammal species recorded by camera traps at 6645 locations across the conterminous United States in a joint modelling framework to estimate relative abundance of each species. We then used a clustering analysis to describe 8 broad and 16 narrow mammal communities.

Results
Climate was the most important predictor of mammal abundance overall, while human population density and agriculture were less important, with mixed effects across species. Seed production by forests also predicted mammal abundance, especially hard-mast tree species. The mammal community maps are similar to those of plants, with an east–west split driven by different dominant species of deer and squirrels. Communities vary along gradients of temperature in the east and precipitation in the west. Most fine-scale mammal community boundaries aligned with established plant ecoregions and were distinguished by the presence of regional specialists or shifts in relative abundance of widespread species. Maps of potential ecosystem services provided by these communities suggest high herbivory in the Rocky Mountains and eastern forests, high invertebrate predation in the subtropical south and greater predation pressure on large vertebrates in the west.

Main Conclusions
Our results highlight the importance of climate to modern mammals and suggest that climate change will have strong impacts on these communities. Our new empirical approach to recognizing ecoregions has potential to be applied to expanded communities of mammals or other taxa.