---
title: "Assessing carnivore distribution from local knowledge across a human‐dominated landscape in central‐southeastern M adagascar"
type: "article"
author: "Mary Kotschwar Logan, Brian D Gerber, Sarah M Karpanty, S Justin, FN Rabenahy"
year: "2015"
publication: "Animal Conservation"
doi: "https://doi.org/10.1111/acv.12137"
download: "../publications/Kotschwar  et al 2015.pdf"
toc: false
categories:
  - mammal
  - Madagascar
  - occupancy
  - journal article
---

## Citation 

> Kotschwar Logan, M., Gerber, B.D., Karpanty, S.M., Justin, S. and Rabenahy, F.N. (2015), Local ecological knowledge of Madagascar's carnivores. *Anim Conserv*, 18: 82-91. https://doi.org/10.1111/acv.12137

## Abstract

Carnivores are often sensitive to habitat loss and fragmentation, both of which are widespread in Madagascar. Clearing of forests has led to a dramatic increase in highly disturbed, open vegetation communities dominated by humans. In Madagascar's increasingly disturbed landscape, long-term persistence of native carnivores may be tied to their ability to occupy or traverse these disturbed areas. However, how Malagasy carnivores are distributed in this landscape and how they interact with humans are unknown, as past research has concentrated on populations within continuous and fragmented forests. We investigated local ecological knowledge of carnivores using semi-structured interviews in communities 0 to 20 km from the western edge of continuous rainforest in central-southeastern Madagascar. Responses from 182 interviews in 17 different communities indicated distinct distribution patterns for two native and two exotic carnivore species, suggesting a range of tolerances to the human-dominated landscape. The largest extant native carnivore, the fossa Cryptoprocta ferox, does not persist in much of this landscape; they were only observed in communities < 5 km from the continuous forest within the last five years. In contrast, the ring-tailed mongoose Galidia elegans was observed by most communities (82%), but was observed by a higher proportion of interviewees from communities in close proximity to continuous forest. The exotic small Indian civet Viverricula indica was ubiquitous, while the exotic/feral cat (Felis sp.) was observed by a higher proportion of interviewees in communities farther from continuous forest. Over 20% of interviewees had experienced loss of poultry to wild carnivores in the last year and negative perceptions of carnivores were common. We found the human-dominated landscape to provide little conservation value to native carnivores, emphasizing the need for adequate protected areas and increased engagement of local communities to sustain Madagascar's carnivore species. This information is critical to multitaxon conservation planning in Madagascar.