---
title: "Forest structure and seasonally inundated grassland shape tropical mammal communities under moderate disturbance"
type: "article"
author: "Juliana Masseloux, Quy Tan Le, Jessica Burr, Brian D Gerber"
year: "2022"
publication: "Ecosphere"
doi: "https://doi.org/10.1002/ecs2.3999"
download: "../publications/Wampole et al. 2022.pdf"
toc: false
categories:
  - occupancy
  - Bayesian
  - mammal
  - forest management
  - camera trapping
  - journal article
---

## Citation 

> Masseloux, Juliana, Quy Tan Le, Jessica Burr, and Brian D. Gerber. 2022. “ Forest Structure and Seasonally Inundated Grassland Shape Tropical Mammal Communities under Moderate Disturbance.” *Ecosphere* 13(3): e3999. https://doi.org/10.1002/ecs2.3999

## Abstract

Tropical biodiversity is threatened globally by anthropogenic disturbances, particularly forest degradation and overhunting. Where large mammals have been extirpated, smaller bodied “mesomammals” may play an important ecological role (e.g., as seed dispersers). However, these species are disproportionally affected by overhunting for wildlife trade markets and are routinely understudied as they tend to be rare, cryptic, and nocturnal. Few studies have examined spatiotemporal responses to anthropogenic disturbance by mesomammals at the community level, which may identify imbalances within an ecosystem that could threaten species persistence. We deployed camera traps throughout Cat Tien National Park (i.e., Nam Cat Tien area), southern Vietnam, to (1) identify long-term changes in terrestrial mesomammal richness and (2) evaluate the effects of forest structure and anthropogenic disturbance on an 18-species mesomammal community within a historically disturbed tropical forest using hierarchical Bayesian community occupancy models. We found that site occupancy was driven by the interaction between distance to seasonally inundated grassland and absolute forest cover (basal area per hectare). This may be due to the combination of intact forest benefits (refuge from predators and hunters, denning sites) and early successional grassland resources (forage quality), as well as high levels of tolerance for disturbed forest among the largely generalist mesomammal community of Nam Cat Tien. We found no negative effects of current anthropogenic factors at the community level. However, we did find that four disturbance-tolerant small carnivores have been extirpated since the 1990s and continued human presence in the park suggests that hunting and snaring remain an acute threat to native mesomammals. Without continued efforts to address the unsustainable harvest of wildlife, Southeast Asian's remaining mesomammals are at risk of extirpation despite resilience to moderate levels of disturbance.