---
title: "Rhode Island wildlife camera trap survey 2018 to 2023"
type: "article"
author: "Mayer, AE, Ganoe, LS,  Brown, C, Rezendes, K, Burr, J, Wampole, EM, Rivera, K, Paton, E, Stift, A, Krista, N, Carey, AE, Hughes, A, Kostisin, T, Healey , R, McGreevy Jr, TJ, and Gerber, BD"
year: "2025"
publication: "Ecology"
doi: "https://doi.org/10.1002/ecy.70094"
download: "../publications/Mayer et al 2025.pdf"
toc: false
categories:
  - data
  - camera trapping
  - mammal
  - journal article
---

## Citation 

> Mayer et al. (2025). Rhode Island wildlife camera trap survey 2018 to 2023. *Ecology*, 106: e70094, https://doi.org/10.1002/ecy.70094.


## Abstract

Monitoring wildlife populations through the collection of abundance and distribution data across climatic seasons and multiple years is critical to understanding wildlife spatiotemporal dynamics. This is especially important in landscapes faced with natural and anthropogenic disturbances, which include the state of Rhode Island, USA. Rhode Island is the second most densely populated state in the United States, yet the landscape remains highly forested. Similar to many areas in the region, land cover change and conversion to non-habitat cover types continue to be an issue as a result of increased anthropogenic disturbance, in addition to recent natural disturbance including forest structural changes from the spongy moth caterpillar (Lymantria dispar). These changes in land cover types and landscape patterns have the potential to positively or negatively affect wildlife communities, and thus, it is increasingly important to monitor wildlife populations. Camera traps provide an efficient way to inventory and monitor a large spatial area and record detections of a wide variety of terrestrial vertebrates. We began surveying the state of Rhode Island as part of a focal study on bobcats (Lynx rufus, 2018–2020) and later fishers (Pekania pennanti, 2020–2023) while documenting all species of terrestrial vertebrates detected at camera survey locations. We placed cameras in areas with land cover appropriate for the original target species—primarily forests and forested wetlands—and avoided placing cameras directly along hiking trails or roads. The state was divided into two sections—west and east—to maximize study area coverage with limited equipment. Cameras were deployed for at least six weeks in each survey period and section. In total, we monitored 249 survey sites in the state over 12 survey periods (six winter seasons, five summer seasons, and one spring season). We collected 244,013 unique detections from 39 terrestrial vertebrate species (25 mammal species, 13 bird species, and non-personnel humans) throughout the study. These data provide spatial and temporal detection information that is useful for investigating the changes in wildlife populations over time and varying degrees of development through analyses including single species, multi-species, dynamic, and diel occupancy modeling. Results of these analyses can be used to understand how a changing landscape impacts wildlife species. The data are openly available for reuse, and please cite this data paper when these data are used in other materials.