---
title: "Transient persistence of bobcat (Lynx rufus) occurrence throughout a human‐dominated landscape"
type: "article"
author: "Amy E Mayer, Thomas J McGreevy Jr, Charles Brown, Laken S Ganoe, Brian D Gerber"
year: "2022"
publication: "Population Ecology"
doi: "https://doi.org/10.1002/1438-390X.12123"
download: "../publications/Mayer et al 2022.pdf"
toc: false
categories:
  - mammal
  - occupancy
  - journal article
---

## Citation 

> Mayer, A. E., McGreevy, T. J. Jr, Brown, C., Ganoe, L. S., & Gerber, B. D. (2022). Transient persistence of bobcat (Lynx rufus) occurrence throughout a human-dominated landscape. *Population Ecology*, 64(4), 323–335. https://doi.org/10.1002/1438-390X.12123

## Abstract

Human developments have detrimental effects on wildlife populations globally with carnivores being particularly sensitive. The bobcat (Lynx rufus) is often considered an adaptable mesocarnivore that occurs throughout varied landcover types within its wide distribution and may be less susceptible to the negative effects of development. Our objectives were to investigate the landscape occupancy dynamics of bobcats in a highly developed and densely populated region of the northeastern United States to evaluate the sensitivity of bobcat occurrence to natural and anthropogenic landscape features. We established a large-scale camera trapping survey throughout Rhode Island, USA, sampling from 2018 to 2020. Using dynamic occupancy models, we found initial site occupancy was positively influenced by the amount of forested wetland habitat, while increasing road density and shrub cover negatively influenced the probability of site colonization. Surprisingly, we found no hypothesized variables to influence site-level extirpation probability, or any seasonal effects on dynamic parameters. Lastly, we found that forest cover and road density negatively influenced the probability of detection. The probability of occupancy was high, >0.8, throughout much of the study area (49%), but we also found relatively high site transients, with the probability a site would change occurrence status from season to season at ≈0.27 in the majority of the study area (70%). Our results show that although bobcats can persist in human-dominated landscapes, they require contiguous natural areas to do so. Future expansion of road infrastructure may reduce habitat connectivity and increase road mortalities, thus jeopardizing the population.