---
title: "Diel activity structures the occurrence of a mammal community in a human‐dominated landscape"
type: "article"
author: "Amy E Mayer, Laken S Ganoe, Charles Brown, Brian D Gerber"
year: "2023"
publication: "Ecology and Evolution"
doi: "https://doi.org/10.1002/ece3.10684"
materials: "https://doi.org/10.5281/zenodo.8240191"
download: "../publications/Mayer et al. 2023.pdf"
toc: false
categories:
  - diel ecology
  - camera trapping
  - Bayesian
  - occupancy
  - journal article
---

## Citation 

> Mayer, A. E., Ganoe, L. S., Brown, C., & Gerber, B. D. (2023). Diel activity structures the occurrence of a mammal community in a human-dominated landscape. *Ecology and Evolution*, 13, e10684. https://doi.org/10.1002/ece3.10684

## Abstract

Anthropogenic developments alter the environment and resources available to wildlife communities. In response to these real or perceived threats from this development, species may adjust their spatial occurrence. Additionally, wildlife species may adjust when in diel time (24-h light–dark cycle) they occupy sites on the landscape to adapt to changing conditions. However, many wildlife studies only focus on where a species does and does not occur, ignoring how species may shift their diel activity at sites to mitigate threats. We used a multi-state diel occupancy modeling framework to investigate how a community of mammals (mesocarnivores, urban-adapted omnivores, and herbivore/small mammals) respond to differing levels of anthropogenic development and forest cover across two climatic seasons. We collected camera trap data at 240 survey locations across the summer and winter of 2021–2022. We modeled multi-state diel occupancy for 14 mammal species with extent of development/forest and season hypothesized to influence diel occupancy and season hypothesized to influence the probability of detection. We found that all species displayed heterogeneity in both diel occupancy and detection either by extent of development/forest and or season. Within the mesocarnivore species group, coyote and red fox were less sensitive to development and had higher occupancy probability at these sites in general but used them more during the night, while more sensitive mesocarnivores including fisher and bobcat occupied the day state only when there was increasing forest cover. Our results highlight the importance of incorporating diel activity in habitat modeling to better understand the relationship between a species and its landscape, particularly in a region that is vulnerable to increased anthropogenic pressure.
