---
title: "Population genetics and spatial ecology of bobcats (Lynx rufus) in a landscape with a high density of humans in New England"
type: "article"
author: "Amy E Mayer, Thomas J McGreevy Jr, Mary E Sullivan, Charles Brown, Thomas P Husband, Brian D Gerber"
year: "2021"
publication: "Northeastern Naturalist"
doi: "https://doi.org/10.1656/045.028.0401"
download: "../publications/Mayer et al 2021.pdf"
toc: false
categories:
  - habitat selection
  - home range
  - population
  - mammal
  - journal article
---

## Citation 

> Mayer, A. E., McGreevy Jr, T. J., Sullivan, M. E., Brown, C., Husband, T. P., & Gerber, B. D. (2021). Population genetics and spatial ecology of bobcats (Lynx rufus) in a landscape with a high density of humans in New England. *Northeastern Naturalist*, 28(4), 408-429.

## Abstract

Lynx rufus (Bobcat) is a wide-ranging and highly adaptable predator whose populations are increasing throughout much of its natural range including in the New England states, yet there are only limited empirical ecological studies there. How Bobcats are responding to the unique modern landscape of southern New England with its highly forested landscape coupled with high density of humans is unknown. This lack of spatial and population ecological information impedes evaluating recovery and management objectives and identifying necessary management actions. Our objectives were to better understand the spatial and population structure of Bobcats in Rhode Island. We specifically examined space use, resource selection, and population genetics. We trapped Bobcats across 5 field seasons from April 2015 to March 2019, totaling 2232 trap nights. We captured 8 Bobcats, equipped GPS collars to a subset (n = 3), and collected locations for 4 to 9 months. We used GPS locations to estimate annual and seasonal home-range size and individual-level seasonal resource selection within the home range for each individual. Further, we used tissue samples collected from trapped individuals and opportunistically collected roadkill (n = 30) to examine the population genetic structure and effective population size of Bobcats in the state. We found the mean winter and summer home-range sizes were 219.3 km2 and 51.7 km2, respectively. Bobcats selected for forested wetland habitats and were associated with areas closer to wetlands and young forests, according to resource-selection models. They also selected for areas with higher road densities, yet avoided developed areas. We found that Bobcats in Rhode Island are part of 1 genetic population and estimated their effective population size to be 82 individuals (95% CI: 44–329). Our study highlights the importance of examining a widely distributed species at a local scale in order to employ evidence-based management practices.