---
title: "Habitat selection of non-breeding American black ducks in an urban estuary"
type: "article"
author: "Mezebish Quinn, T., P. W. Paton, B. D. Gerber, J. E. Kilburn, and S. R. McWilliams"
year: "2024"
publication: "Journal of Wildlife Management"
doi: "https://doi.org/10.1002/jwmg.22649"
download: "..//publications/Mezebish Quinn et al 2024.pdf"
toc: false
categories:
  - avian
  - habitat selection
  - journal article
---

## Citation 

> Mezebish Quinn, T., P. W. Paton, B. D. Gerber, J. E. Kilburn, and S. R. McWilliams. 2024. Habitat selection of non-breeding American black ducks in an urban estuary. Journal of Wildlife Management e22649. https://doi.org/10.1002/jwmg.22649

## Abstract

Shellfish aquaculture is a globally expanding industry, including in urban estuaries that support non-breeding waterfowl. The effects of shellfish aquaculture on the spatial distribution of non-breeding waterfowl, however, are poorly understood and depend on the ecology of waterfowl and cultivated shellfish species. We investigated how proximity to shellfish aquaculture influenced habitat selection and movement patterns of American black ducks (Anas rubripes) during the non-breeding season (~Oct–May) in 2020–2023 in Rhode Island, USA. The extent to which proximity to aquaculture influenced habitat selection of black ducks depended on factors specific to individuals' primary non-breeding sites, although proximity to aquaculture did not have biologically meaningful influences on black duck movement rates across all sites. Black ducks across sites consistently selected for areas better suited for aquaculture (i.e., areas of potential future development) relative to areas poorly suited for aquaculture (i.e., areas less likely to be developed). The continued expansion of aquaculture into preferred black duck habitats will increase black duck interactions with aquaculture and therefore should be considered in the decision-making process for siting future aquaculture leases. Future studies should quantify the extent to which continued expansion of aquaculture in those preferred coastal habitats directly influences black ducks.