---
title: "Making the most of sparse data to estimate density of a rare and threatened species: a case study with the fosa, a little‐studied Malagasy carnivore"
type: "article"
author: "Asia Murphy, Brian D Gerber, Zach J Farris, Sarah Karpanty, Felix Ratelolahy, Marcella J Kelly"
year: "2019"
publication: "Animal Conservation"
doi: "https://doi.org/10.1111/acv.12420"
download: "../publications/Murphy et al 2019.pdf"
toc: false
categories:
  - mammal
  - journal article
---

## Citation 

> Murphy, A., Gerber, B.D., Farris, Z.J., Karpanty, S., Ratelolahy, F. and Kelly, M.J. (2018), Making the most of sparse data to estimate density of a rare and threatened species: a case study with the fosa, a little-studied Malagasy carnivore. *Anim Conserv*, 21: 496-504. https://doi.org/10.1111/acv.12420

## Abstract

Sparse detections in camera trap surveys commonly hinder density estimation for threatened species. By combining detections across multiple surveys, or using informative priors in Bayesian model fitting, researchers can improve parameter estimation from sparse capture–recapture data. Using a spatial mark–resight model that incorporates site-level heterogeneity in the spatial scale parameter via a hierarchical process and prior information, we estimated the density of a threatened carnivore (fosa, Cryptoprocta ferox) from multiple sparse datasets collected during extensive camera trapping surveys in northeastern Madagascar (2008–2015). Our objectives were to estimate density for six sites, examine the response of fosa density and movement to habitat degradation, monitor annual density trends across 7 years at two sites, and estimate fosa abundance in the Makira–Masoala protected area complex. We obtained a mean of 16.1 (se = 0.52; range = 2–49) fosa detections and three observers identified a mean of 3.62 (se = 0.09; range = 1–8) marked individuals per survey. Fosa daily baseline encounter rate was very low (λ0 = 0.004; 0.003–0.006) and density/movement estimates were similar across forest types. Density estimates at resurveyed sites suggested annual variability in density, with estimates trending lower during the final surveys [e.g. D = 0.39 (0.14–1.11) versus 0.08 (0.05–0.31) individuals per km2]. We estimated fosa abundance across the Makira–Masoala region to be 1061 (95% HPDI: 596–1780) adult individuals. On the basis of our estimate and the size of the region, we believe Makira–Masoala harbors a significant portion of the global fosa population. The conservation and management of rare species is commonly limited due to lack of population estimates. By combining detections across surveys, we overcame estimation issues and obtained valuable information on a threatened carnivore, allowing us to better assess its status and prioritize conservation actions. We advocate for practical use of sparse datasets for such data-deficient species.