---
title: "Behavioral and demographic responses of mule deer to energy development on winter range"
type: "article"
author: "Joseph M Northrup, Charles R Anderson Jr, Brian D Gerber, George Wittemyer"
year: "2021"
publication: "Wildlife Monographs"
doi: "https://doi.org/10.1002/wmon.1060"
download: "../publications/Northrup et al. 2021.pdf"
toc: false
categories:
  - survival
  - habitat selection
  - mammal
  - journal article
---

## Citation 

> Northrup, J.M., Anderson, C.R., Jr., Gerber, B.D. and Wittemyer, G. (2021), Behavioral and Demographic Responses of Mule Deer to Energy Development on Winter Range. *Wild. Mon.*, 208: 1-37. https://doi.org/10.1002/wmon.1060

## Abstract

Anthropogenic habitat modification is a major driver of global biodiversity loss. In North America, one of the primary sources of habitat modification over the last 2 decades has been exploration for and production of oil and natural gas (hydrocarbon development), which has led to demographic and behavioral impacts to numerous wildlife species. Developing effective measures to mitigate these impacts has become a critical task for wildlife managers and conservation practitioners. However, this task has been hindered by the difficulties involved in identifying and isolating factors driving population responses. Current research on responses of wildlife to development predominantly quantifies behavior, but it is not always clear how these responses scale to demography and population dynamics. Concomitant assessments of behavior and population-level processes are needed to gain the mechanistic understanding required to develop effective mitigation approaches. We simultaneously assessed the demographic and behavioral responses of a mule deer population to natural gas development on winter range in the Piceance Basin of Colorado, USA, from 2008 to 2015. Notably, this was the period when development declined from high levels of active drilling to only production phase activity (i.e., no drilling). We focused our data collection on 2 contiguous mule deer winter range study areas that experienced starkly different levels of hydrocarbon development within the Piceance Basin.

We assessed mule deer behavioral responses to a range of development features with varying levels of associated human activity by examining habitat selection patterns of nearly 400 individual adult female mule deer. Concurrently, we assessed the demographic and physiological effects of natural gas development by comparing annual adult female and overwinter fawn (6-month-old animals) survival, December fawn mass, adult female late and early winter body fat, age, pregnancy rates, fetal counts, and lactation rates in December between the 2 study areas. Strong differences in habitat selection between the 2 study areas were apparent. Deer in the less-developed study area avoided development during the day and night, and selected habitat presumed to be used for foraging. Deer in the heavily developed study area selected habitat presumed to be used for thermal and security cover to a greater degree. Deer faced with higher densities of development avoided areas with more well pads during the day and responded neutrally or selected for these areas at night. Deer in both study areas showed a strong reduction in use of areas around well pads that were being drilled, which is the phase of energy development associated with the greatest amount of human presence, vehicle traffic, noise, and artificial light. Despite divergent habitat selection patterns, we found no effects of development on individual condition or reproduction and found no differences in any of the physiological or vital rate parameters measured at the population level. However, deer density and annual increases in density were higher in the low-development area. Thus, the recorded behavioral alterations did not appear to be associated with demographic or physiological costs measured at the individual level, possibly because populations are below winter range carrying capacity. Differences in population density between the 2 areas may be a result of a population decline prior to our study (when development was initiated) or area-specific differences in habitat quality, juvenile dispersal, or neonatal or juvenile survival; however, we lack the required data to contrast evidence for these mechanisms.

Given our results, it appears that deer can adjust to relatively high densities of well pads in the production phase (the period with markedly lower human activity on the landscape), provided there is sufficient vegetative and topographic cover afforded to them and populations are below carrying capacity. The strong reaction to wells in the drilling phase of development suggests mitigation efforts should focus on this activity and stage of development. Many of the wells in this area were directionally drilled from multiple-well pads, leading to a reduced footprint of disturbance, but were still related to strong behavioral responses. Our results also indicate the likely value of mitigation efforts focusing on reducing human activity (i.e., vehicle traffic, light, and noise). In combination, these findings indicate that attention should be paid to the spatial configuration of the final development footprint to ensure adequate cover. In our study system, minimizing the road network through landscape-level development planning would be valuable (i.e., exploring a maximum road density criteria). Lastly, our study highlights the importance of concomitant assessments of behavior and demography to provide a comprehensive understanding of how wildlife respond to habitat modification.