---
title: "Applying a hierarchical Bayesian framework to reveal howfear and animal ownership drive human's valuation of andinteractions with coyotes"
type: "article"
author: "Kimberly Rivera, Carlos Garcia-Quijano, Virginie Sonnet, and Brian D Gerber"
year: "2024"
publication: "Conservation Science and Practice"
doi: "https://doi.org/10.1111/csp2.13177"
download: "../publications/Rivera et al. 2024.pdf"
toc: false
categories:
  - mammal
  - camera trapping
  - Bayesian
  - journal article
---

## Citation 

> Rivera, K., Garcia-Quijano, C., Sonnet, V., & Gerber, B. D. (2024). Applying a hierarchical Bayesian framework to reveal how fear and animal ownership drive human's valuation of and interactions with coyotes. Conservation Science and Practice, e13177. https://doi.org/10.1111/csp2.13177

## Abstract

Human dimensions research is valuable to managing human-wildlife interactions, especially in urban environments where such interactions are common. Survey data, which commonly contain Likert scales and questions, are useful in this field; however, these data can be difficult to analyze with formal modeling approaches. We demonstrate one approach, based on hierarchical Bayesian ordinal regression, to evaluate human-coyote relationships in Rhode Island, USA. We implemented a survey to collect demographic and sociocultural characteristics of Rhode Island residents and information related to their knowledge of and experiences with coyotes. Our objectives were to assess how these characteristics affected respondents' valuation of and interactions (sightings and incidents) with coyotes. We analyzed 980 surveys from October to December 2020. We found that respondents who had fear of coyotes or experienced an incident between an owned animal and coyote, had the lowest valuation of coyotes. The same demographic of respondents also reported the highest sightings of and incidents with coyote. These results indicate that fearful residents, in addition to pet and livestock owners, are priority targets for disseminating information or programming about coyotes. Our analyses and findings demonstrate how Bayesian ordinal regression can provide clear and appropriate inference from survey data on how groups of people vary in their relationship with wildlife. These results are important in effectively and efficiently allocating resources towards mitigation, education, and management of human-wildlife interactions.