---
title: "Assessment of the threatened carnivore community in the recently expanded rainforest protected area Anjanaharibe-Sud Special Reserve, Madagascar"
type: "article"
author: "Patrick H Ross, Erik Patel, Barry Ferguson, Rojo Nandrianina Ravelijaona, Guy Irenel Raoloniana, Erin Wampole, Brian D Gerber, Zach J Farris"
year: "2020"
publication: "Endangered Species Research"
doi: "https://doi.org/10.3354/esr01055"
download: "../publications/Ross et al. 2020.pdf"
toc: false
categories:
  - mammal
  - Madagascar
  - occupancy
  - camera trapping
  - journal article
---

## Citation 

> Ross PH, Patel E, Ferguson B, Ravelijaona RN and others (2020) Assessment of the threatened carnivore community in the recently expanded rainforest protected area Anjanaharibe-Sud Special Reserve, Madagascar. *Endang Species Res* 43:89-98. https://doi.org/10.3354/esr01055

## Abstract

Madagascar is an island nation renowned for its biodiversity and species endemism, yet it is still largely understudied despite intense anthropogenic threats including forest loss and edge effects. Anjanaharibe-Sud Special Reserve is a recently expanded rainforest protected area that is lacking detailed surveys and assessments of the native carnivore community of the endemic family Eupleridae. To identify which terrestrial carnivores occupy the reserve and what anthropogenic disturbances and factors best explain their occurrence patterns, we deployed 35 motion-activated cameras to detect native and introduced carnivores. From November 2018 to February 2019, we collected 2918 unique capture events (all species) and confirmed the presence of 5 euplerids: Galidia elegans, Galidictis fasciata, Eupleres goudotii, Fossa fossana, and Cryptoprocta ferox. These results extend the known range of E. goudotii and G. fasciata. In the reserve, F. fossana and G. elegans were the most common and widespread native carnivores, while E. goudotii was the rarest. We highlight the negative impact of edge effects on G. fasciata and F. fossana and the threat posed by the free-ranging non-native carnivore C. familiaris. This study represents the first detailed survey and occurrence estimates of the carnivore community of this protected area, allowing comparison with other protected areas in Madagascar. Our empirical findings show that anthropogenic disturbance negatively impacts carnivore existence within the Anjanaharibe-Sud Special Reserve and provide important management recommendations for protecting the carnivore community and the co-occurring wildlife living within this area.