---
title: "A biogeographical perspective on the variation in mouse lemur density throughout Madagascar"
type: "article"
author: "Casey M Setash, Sarah Zohdy, Brian D Gerber, Caitlin J Karanewsky"
year: "2017"
publication: "Mammal Review"
doi: "https://doi.org/10.1111/mam.12093"
download: "../publications/Setash et al. 2017.pdf"
toc: false
categories:
  - mammal
  - review
  - abundance
  - Bayesian
  - journal article
---

## Citation 

> Setash, C.M., Zohdy, S., Gerber, B.D. and Karanewsky, C.J. (2017), A biogeographical perspective on the variation in mouse lemur density throughout Madagascar. *Mam Rev*, 47: 212-229. https://doi.org/10.1111/mam.12093

## Abstract

Madagascar is home to the smallest primates in the world, the mouse lemurs (Microcebus species). Twenty-four species of mouse lemur are currently recognised and are found in variable ecosystems, from dry forests and spiny deserts to humid forests. Due to their widespread distribution and the large number of sympatric species, mouse lemurs can be used as a model to understand the linkages among species richness, population density, and habitat. As all lemurs are threatened by habitat loss and fragmentation, this information can also be used to inform conservation management.
We hypothesise that on an island-wide scale, we will find higher population densities in western dry forests than in eastern humid forests because the western dry forests exhibit lower species richness, more sympatric habitat use, and lower resource stability than the eastern humid forests.
We conducted a literature review of population density estimates of known mouse lemur species, and used those data to conduct a meta-analysis and estimate overall average population density by geographic region.

Our findings suggest that mouse lemur species living in western dry forest generally exhibit higher densities than those in eastern humid forests. This may be partly explained by higher habitat fragmentation in western dry forests, where species co-occur, but is likely to be a function of the magnitude and variability in seasonally available resources in each forest type. Higher seasonality results in less constant food availability and lower levels of environmental predictability, fostering species capable of coping with environmental change and maintaining high densities throughout periods of resource paucity.

Our study highlights the importance of conducting Microcebus population density research that adheres to standardised methodological approaches. We point to the need for population density estimates for several species for which data are lacking. Such knowledge is important to assess the conservation status of these species, but also to enhance our ability to identify the macro-biogeographical and local ecological drivers of interspecific and intraspecific variability in population density.