---
title: "Preventing global extinction of the Javan rhino: tsunami risk and future conservation direction"
type: "article"
author: "Ridwan Setiawan, Brian D Gerber, Ujang Mamat Rahmat, Daryan Daryan, Asep Yayus Firdaus, Mohammad Haryono, Kurnia Okhtavia Khairani, Yuyun Kurniawan, Barney Long, Arnaud Lyet, Muhiban Muhiban, Rois Mahmud, Aom Muhtarom, Elisabet Purastuti, Widodo S Ramono, Dadan Subrata, Sunarto Sunarto"
year: "2018"
publication: "Conservation Letters"
doi: "https://doi.org/10.1111/conl.12366"
download: "../publications/Setiawan et al 2018.pdf"
toc: false
categories:
  - mammal
  - mark recapture
  - population
  - journal article
---

## Citation 

> Setiawan, R., Gerber, B.D., Rahmat, U.M., Daryan, D., Firdaus, A.Y., Haryono, M., Khairani, K.O., Kurniawan, Y., Long, B., Lyet, A., Muhiban, M., Mahmud, R., Muhtarom, A., Purastuti, E., Ramono, W.S., Subrata, D. and Sunarto, S. (2018), Preventing Global Extinction of the Javan Rhino: Tsunami Risk and Future Conservation Direction. *Conservation Letters*, 11: e12366. https://doi.org/10.1111/conl.12366

## Abstract

The Javan rhino (Rhinoceros sondaicus) is one of the most threatened mammals on Earth. The only remaining individuals live as part of a small population isolated in a single protected area, Ujung Kulon National Park, Java, Indonesia. Despite almost a century of studies, little is known about the factors that affect Javan rhino demography and distribution. National park officials require such information to identify conservation strategies and track the success and failures of these efforts; translocating selected individuals to establish a second population has been considered, but the risks must be weighed. We show that the 2013 global population of Javan rhinos was 62 individuals, which is likely near the site's carrying capacity. Our analysis of rhino distribution indicates that tsunamis are a significant risk to the species in Ujung Kulon, justifying the risks of establishing additional populations. Continued individual-based monitoring is needed to guide future translocation decisions.