---
title: "Effects of El Niño on the population dynamics of the Malay civet east of the Wallace line"
type: "article"
author: "Adrian Seymour, Mark Tarrant, Brian Gerber, Alex Sharp, Jamie Woollam, Ruth Cox"
year: "2017"
publication: "Journal of Zoology"
doi: "https://doi.org/10.1111/jzo.12469"
download: "../publications/Seymour et al. 2017.pdf"
toc: false
categories:
  - mammal
  - climate
  - survival
  - mark recapture
  - abundance
  - journal article
---

## Citation 

> Seymour, A.S., Tarrant, M.R., Gerber, B.D., Sharp, A., Woollam, J. and Cox, R. (2017), Effects of El Niño on the population dynamics of the Malay civet east of the Wallace line. *J Zool*, 303: 120-128. https://doi.org/10.1111/jzo.12469

## Abstract

The effect of climate on the population dynamics of rainforest vertebrates is known only for a limited subset of species and study locations. To extend this knowledge, we carried out an 8-year population study of a Viverrid (Malay civet Viverra tangalunga) in the Wallacea biogeographical region (Buton Island, Sulawesi). Civets were trapped annually from 2003 to 2010, during which there were four weak to moderate El Niño events and one moderate La Niña event. In Indonesia, El Niño events are associated with drier than normal conditions, while La Niña is associated with wetter conditions. The number of individuals captured was strongly correlated with the 12-month summed Southern Oscillation Index (SOI) prior to trapping, with significantly fewer individuals caught in years with lower summed SOI (i.e. stronger El Niño conditions). Adult civet body mass was significantly higher in El Niño years; mean adult male and female body masses were 10.6% and 4.0% greater in El Niño years. There was support for a 1-year time lagged effect of El Niño on the apparent survival (1 – probability of disappearing from the study site due to death or emigration) of male (but not female) civets, which was approximately 50% higher in the year following El Niño events. Using spatially explicit capture–mark–recapture models, we were unable to detect any significant change in civet density between years, which was estimated as 1.36 ± 0.14 (se) individuals km−2. We suggest that increased apparent survival of males observed in the year after El Niño events was brought about by reduced dispersal (possibly associated with a change in mating tactic) rather than reduced mortality.