---
title: "SNAPSHOT USA 2021: A third coordinated national cameratrap survey of the United States"
type: "article"
author: "Shamon, Hila, Roi Maor, Michael V. Cove, Roland Kays, Jessie Adley, et al."
year: "2024"
publication: "Ecology"
doi: "https://doi.org/10.1002/ecy.4318"
download: "../publications/Shamon et al. 2024.pdf"
toc: false
categories:
  - data
  - camera trapping
  - mammal
  - journal article
---

## Citation 

> Shamon et al. (2024). SNAPSHOT USA 2021: A third coordinated national cameratrap survey of the United States. *Ecology*, e4318, https://doi.org/10.1002/ecy.4318.
.

## Abstract

SNAPSHOT USA is a multicontributor, long-term camera trap survey designed tosurvey mammals across the United States. Participants are recruited through com-munity networks and directly through a website application (https://www.snapshot-usa.org/). The growing Snapshot dataset is useful, for example, for track-ing wildlife population responses to land use, land cover, and climate changesacross spatial and temporal scales. Here we present the SNAPSHOT USA 2021dataset, the third national camera trap survey across the US. Data were collectedacross 109 camera trap arrays and included 1711 camera sites. The total effortequaled 71,519 camera trap nights and resulted in 172,507 sequences of animalobservations. Sampling effort varied among camera trap arrays, with a minimumof 126 camera trap nights, a maximum of 3355 nights, a median 546 nights, and amean 656 ± 431 nights. This third dataset comprises 51 camera trap arrays thatwere surveyed during 2019, 2020, and 2021, along with 71 camera trap arrays thatwere surveyed in 2020 and 2021. All raw data and accompanying metadata arestored on Wildlife Insights (https://www.wildlifeinsights.org/), and are publicly avail-able upon acceptance of the data papers. SNAPSHOT USA aims to sample multipleecoregions in the United States with adequate representation of each ecoregionaccording to its relative size. Currently, the relative density of camera trap arraysvaries by an order of magnitude for the various ecoregions (0.22–5.9 arrays per100,000 km2), emphasizing the need to increase sampling effort by further recruitingand retaining contributors. There are no copyright restrictions on these data. We2 of 6 SHAMON ET AL .request that authors cite this paper when using these data, or a subset of these data,for publication. Any use of trade, firm, or product names is for descriptive purposesonly and does not imply endorsement by the US Government.