---
title: "SNAPSHOT USA 2019: a coordinated national camera trap survey of the United States"
type: "article"
author: "Michael V Cove, Roland Kays, et al."
year: "2021"
publication: "Ecology"
doi: "https://doi.org/10.1002/ecy.3353"
download: "../publications/Cove et al. 2021.pdf"
toc: false
categories:
  - data
  - camera trapping
  - mammal
  - journal article
---

## Citation 

> Cove, M. V., et al. 2021. SNAPSHOT USA 2019: a coordinated national camera trap survey of the United States. *Ecology* 102(6):e03353. 10.1002/ecy.3353

## Abstract

With the accelerating pace of global change, it is imperative that we obtain rapid inventories of the status and distribution of wildlife for ecological inferences and conservation planning. To address this challenge, we launched the SNAPSHOT USA project, a collaborative survey of terrestrial wildlife populations using camera traps across the United States. For our first annual survey, we compiled data across all 50 states during a 14-week period (17 August–24 November of 2019). We sampled wildlife at 1,509 camera trap sites from 110 camera trap arrays covering 12 different ecoregions across four development zones. This effort resulted in 166,036 unique detections of 83 species of mammals and 17 species of birds. All images were processed through the Smithsonian’s eMammal camera trap data repository and included an expert review phase to ensure taxonomic accuracy of data, resulting in each picture being reviewed at least twice. The results represent a timely and standardized camera trap survey of the United States. All of the 2019 survey data are made available herein. We are currently repeating surveys in fall 2020, opening up the opportunity to other institutions and cooperators to expand coverage of all the urban–wild gradients and ecophysiographic regions of the country. Future data will be available as the database is updated at eMammal.si.edu/snapshot-usa, as will future data paper submissions. These data will be useful for local and macroecological research including the examination of community assembly, effects of environmental and anthropogenic landscape variables, effects of fragmentation and extinction debt dynamics, as well as species-specific population dynamics and conservation action plans. There are no copyright restrictions; please cite this paper when using the data for publication.