---
title: "SNAPSHOT USA 2020: A second coordinated national camera trap survey of the United States during the COVID‐19 pandemic"
type: "article"
author: "Roland Kays et al."
year: "2022"
publication: "Ecology"
doi: "https://doi.org/10.1002/ecy.3775"
download: "../publications/Kays et al. 2022.pdf"
toc: false
categories:
  - camera trapping
  - mammal
  - data
  - journal article
---

## Citation 

> Kays, Roland, Michael V. Cove, Jose Diaz, Kimberly Todd, Claire Bresnan, Matt Snider, Thomas E. Lee Jr, et al. 2022. “ SNAPSHOT USA 2020: A Second Coordinated National Camera Trap Survey of the United States during the COVID-19 Pandemic.” *Ecology* 103(10): e3775. https://doi.org/10.1002/ecy.3775

## Abstract

Managing wildlife populations in the face of global change requires regular data on the abundance and distribution of wild animals, but acquiring these over appropriate spatial scales in a sustainable way has proven challenging. Here we present the data from Snapshot USA 2020, a second annual national mammal survey of the USA. This project involved 152 scientists setting camera traps in a standardized protocol at 1485 locations across 103 arrays in 43 states for a total of 52,710 trap-nights of survey effort. Most (58) of these arrays were also sampled during the same months (September and October) in 2019, providing a direct comparison of animal populations in 2 years that includes data from both during and before the COVID-19 pandemic. All data were managed by the eMammal system, with all species identifications checked by at least two reviewers. In total, we recorded 117,415 detections of 78 species of wild mammals, 9236 detections of at least 43 species of birds, 15,851 detections of six domestic animals and 23,825 detections of humans or their vehicles. Spatial differences across arrays explained more variation in the relative abundance than temporal variation across years for all 38 species modeled, although there are examples of significant site-level differences among years for many species. Temporal results show how species allocate their time and can be used to study species interactions, including between humans and wildlife. These data provide a snapshot of the mammal community of the USA for 2020 and will be useful for exploring the drivers of spatial and temporal changes in relative abundance and distribution, and the impacts of species interactions on daily activity patterns. There are no copyright restrictions, and please cite this paper when using these data, or a subset of these data, for publication.