---
title: "Marking power lines to reduce avian collisions near the Audubon National Wildlife Refuge, North Dakota"
type: "article"
author: "Misti K Sporer, James F Dwyer, Brian D Gerber, Richard E Harness, Arun K Pandey"
year: "2014"
publication: "Wildlife Society Bulletin"
doi: "https://doi.org/10.1002/wsb.329"
download: "../publications/Sporer et al 2014.pdf"
toc: false
categories:
  - avian
  - population
  - journal article
---

## Citation 

> Sporer, M.K., Dwyer, J.F., Gerber, B.D., Harness, R.E. and Pandey, A.K. (2013), Marking power lines to reduce avian collisions near the Audubon National Wildlife Refuge, North Dakota. *Wildl. Soc. Bull.*, 37: 796-804. https://doi.org/10.1002/wsb.329

## Abstract

Overhead power lines can pose collision risks to birds. Risks may be mitigated through marking lines with high-visibility devices, but the effectiveness of line marking remains unclear. Effectiveness is particularly poorly described for lines bisecting open water, where detection of carcasses can be difficult. We marked 3 of 9 spans (lines between adjacent structures) along a causeway crossing open water and 2 adjacent spans over lake shores between Lake Sakakawea and Lake Audubon near Audubon National Wildlife Refuge, North Dakota, USA. Over 3 years, we found 1,186 avian carcasses, including 276 attributed to power-line collision. American coots (Fulica americana; n = 83) and double-crested cormorants (Phalacrocorax auritus; n = 27) were the species most commonly associated with power-line collision, but we also found carcasses of 51 other species, including a piping plover (Charadrius melodus; n = 1). Multi-variable modeling indicated line marking over open water reduced predicted collisions per span per season (mid-April through mid-October, 2006–2008) from 10.3 to 5.8. Birds with high-aspect-ratio wings benefitted most from line marking (e.g., shorebirds and gulls). If the 9 open-water spans we studied were unmarked for 30 years, we predicted 2,775 collisions. We predicted only 1,560 collisions if all of these spans were marked. Our data demonstrate that a wide variety of avian species are at risk of collision with lines bisecting open water, marking lines can reduce collision risk, and because collisions persisted and some line markers fell off power lines, improvements to effectively mark lines are needed. © 2013 The Wildlife Society.