---
title: "Risky business: sex differences in mortality and dispersal in a polygynous, monomorphic lemur"
type: "article"
author: "Stacey R Tecot, Brian D Gerber, Stephen J King, Jennifer L Verdolin, Patricia C Wright"
year: "2013"
publication: "Behavioral Ecology"
doi: "https://doi.org/10.1093/beheco/art008"
download: "../publications/Tecot et al_2013_BehavEco"
toc: false
categories:
  - mammal
  - Madagascar
  - survival
  - journal article
---

## Citation 

> Stacey R. Tecot, Brian D. Gerber, Stephen J. King, Jennifer L. Verdolin, Patricia C. Wright, Risky business: sex differences in mortality and dispersal in a polygynous, monomorphic lemur, *Behavioral Ecology*, Volume 24, Issue 4, 2013, 987–996, https://doi.org/10.1093/beheco/art008

## Abstract

Sexually selected traits and the use of strategies to enhance male reproductive success (e.g., competition and dispersal) can yield sex differences in metabolic requirements, rates and durations of growth and maturation, and the propensity for risky behavior, which are suggested to result in age-specific sex differences in mortality and life span. We investigated age-specific sex ratios, mortality, and dispersal in Propithecus edwardsi in Ranomafana National Park, Madagascar. We predicted that, due to similarities in growth rates and body sizes, male and female juvenile mortality rates would be comparable; because both sexes disperse and have intense intersexual competition and aggression, adult mortality would be similar; given similarities in dispersal frequency and distance, the timing of dispersal would not differ. We used 80 group-years births, deaths, and dispersals (Nfemales = 41, Nmales = 34) collected over 23 years to calculate sex ratios and survival curves. Females lived longer than males (maximum 32 and 19 years, respectively). Sex ratios were male biased from sexual maturity through 17 years and female biased at birth and older ages. Infant survival probabilities were similar. Thus, differential development and maturation are unlikely explanations for longer female life span in this species. Males were more likely to survive from 2 to 18 years. However, male annual survival probability declined quickly around 13–18 years; males continued to disperse until their deaths, whereas females generally stopped dispersing after 11 years. We suggest that sex differences in the timing of dispersal and the unique challenges of risky behavior at older ages may be sufficient to yield differences in male and female life span.