---
title: "Using global remote camera data of a solitary species complex to evaluate the drivers of group formation"
type: "article"
author: "Joshua P. Twining, Chris Sutherland, Andrzej Zalewski, Michael V. Cove, Johnny Birks, Oliver R. Wearn, Jessica Haysom,  Anna Wereszczuk, Emiliano Manzo, Paola Bartolommei, Alessio Mortelliti,j, Bryn Evans, Brian D. Gerber, Thomas J. McGreevy Jr.,  Laken S. Ganoe, Juliana Masseloux, Amy E. Mayer, Izabela Wierzbowska, Jan Loch, Jocelyn Akins, Donovan Drummey, William McShea,  Stephanie Manke, Lain Pardo, Andy J. Boyce, Sheng Li, Roslina Binti Ragai, Ronglarp Sukmasuang, Álvaro José Villafañe Trujillo, Carlos López- González, Nalleli Elvira Lara- Díaz, Olivia Cosbyp, Cristian N. Waggershauserz, Jack Bamber, Frances Stewart,  Jason Fisher, Angela K. Fuller, Kelly A. Perkins, and Roger A. Powel"
year: "2020"
publication: "Proceedings of the National Academy of Sciences"
doi: "https://doi.org/10.1073/pnas.2312252121"
download: "../publications/Twining et al 2024.pdf"
toc: false
categories:
  - mammal
  - camera trapping
  - journal article
---

## Citation 

> Twinning et al. (2024). Using global remote camera data of a solitary species complex to evaluate the drivers of group formation. *Proceedings of the National Academy of Sciences*, 121(12) e2312252121.
.

## Abstract

The social system of animals involves a complex interplay between physiology, natural history, and the environment. Long relied upon discrete categorizations of “social” and “solitary” inhibit our capacity to understand species and their interactions with the world around them. Here, we use a globally distributed camera trapping dataset to test the drivers of aggregating into groups in a species complex (martens and relatives, family Mustelidae, Order Carnivora) assumed to be obligately solitary. We use a simple quantification, the probability of being detected in a group, that was applied across our globally derived camera trap dataset. Using a series of binomial generalized mixed-effects models applied to a dataset of 16,483 independent detections across 17 countries on four continents we test explicit hypotheses about potential drivers of group formation. We observe a wide range of probabilities of being detected in groups within the solitary model system, with the probability of aggregating in groups varying by more than an order of magnitude. We demonstrate that a species’ context-dependent proclivity toward aggregating in groups is underpinned by a range of resource-related factors, primarily the distribution of resources, with increasing patchiness of resources facilitating group formation, as well as interactions between environmental conditions (resource constancy/winter severity) and physiology (energy storage capabilities). The wide variation in propensities to aggregate with conspecifics observed here highlights how continued failure to recognize complexities in the social behaviors of apparently solitary species limits our understanding not only of the individual species but also the causes and consequences of group formation.