---
title: "Transboundary cooperation improves endangered species monitoring and conservation actions: A case study of the global population of Amur leopards"
type: "article"
author: "Anna V Vitkalova, Limin Feng, Alexander N Rybin, Brian D Gerber, Dale G Miquelle, Tianming Wang, Haitao Yang, Elena I Shevtsova, Vladimir V Aramilev, Jianping Ge"
year: "2018"
publication: "Conservation Letters"
doi: "https://doi.org/10.1111/conl.12574"
download: "../publications/Vitkalova et al. 2018.pdf"
toc: false
categories:
  - mark recapture
  - survival
  - camera trapping
  - population
  - mammal
  - journal article
  - monitoring
---

## Citation 

> Vitkalova AV, Feng L, Rybin AN, et al. Transboundary cooperation improves endangered species monitoring and conservation actions: A case study of the global population of Amur leopards. *Conservation Letters*. 2018; 11: e12574. https://doi.org/10.1111/conl.12574

## Abstract

Political borders and natural boundaries of wildlife populations seldom coincide, often to the detriment of conservation objectives. Transnational monitoring of endangered carnivores is rare, but is necessary for accurate population monitoring and coordinated conservation policies. We investigate the benefits of collaboratively monitoring the abundance and survival of the critically endangered Amur leopard, which occurs as a single transboundary population across China and Russia. Country-specific results overestimated abundance and were generally less precise compared to integrated monitoring estimates; the global population was similar in both years: 84 (70–108, 95% confidence interval). Uncertainty in country-specific annual survival estimates were approximately twice the integrated estimates of 0.82 (0.69–0.91, 95% confidence limits). This collaborative effort provided a better understanding of Amur leopard population dynamics, represented a first step in building trust, and lead to cooperative agreements to coordinate conservation policies.