---
title: "Madagascar Terrestrial Camera Survey Database 2021: A collation of protected forest camera surveys from 2007–2021"
type: "article"
author: "Erin M Wampole, Brian D Gerber, Zach J Farris et al."
year: "2022"
publication: "Ecology"
doi: "https://doi.org/10.1002/ecy.3687"
download: "../publications/Wampole et al. 2022.pdf"
toc: false
categories:
  - data
  - mammal
  - camera trapping
  - journal article
---

## Citation 

> Wampole, Erin M., Brian D. Gerber, Zach J. Farris, Jean Claude Razafimahaimodison, Mahandry Hugues Andrianarisoa, Claude Jacquot Ralazampirenena, Patricia C. Wright, et al. 2022. “ Madagascar Terrestrial Camera Survey Database 2021: A Collation of Protected Forest Camera Surveys from 2007–2021.” *Ecology* 103(6): e3687. https://doi.org/10.1002/ecy.3687

## Abstract

Madagascar is a threatened global biodiversity hotspot and conservation priority, yet we lack broad-scale surveys to assess biodiversity across space and time. To fill this gap, we collated camera trap surveys, capturing species occurrences within Madagascar into a single standardized database. This data set includes nine distinct protected areas of Madagascar and encompasses 13 subprojects, 38 camera arrays, and 1156 sampling units (independent camera site per survey) within two important biodiversity eco-regions: western dry deciduous forest and eastern humid rainforest. Camera surveys were conducted from June 2007 to January 2021. The final data set includes 17 unique families of mammals (Bovidae, Canidae, Cheirogaleidae, Daubentoniidae, Equidae, Eupleridae, Felidae, Hominidae, Indriidae, Lemuridae, Lepilemuridae, Muridae, Nesomyidae, Pteropodidae, Soricidae, Suidae, Tenrecidae) comprising 45 species and 27 unique families of birds (Accipitridae, Acrocephalidae, Alcedinidae, Bernieridae, Brachypteraciidae, Caprimulgidae, Cisticolidae, Columbidae, Coraciidae, Corvidae, Cuculidae, Dicruridae, Mesitornithidae, Monarchidae, Motacillidae, Muscicapidae, Numididae, Phasianidae, Rallidae, Sarothruridae, Strigidae, Sturnidae, Sulidae, Threskiornithidae, Upupidae, Vangidae, Zosteropidae) comprising 58 species. Images were processed and verified by individual project data set creators and camera operation and species tables were then collated. The final product represents the first broad-scale freely available standardized formal faunal database for Madagascar. Data are available through this publication and at DOI: 10.5281/zenodo.5801806. These data will be useful for examining species-level and community-level trends in occurrence across space or time within Madagascar and globally, evaluating native and invasive species dynamics, and will aid in determining species conservation status and planning for at-risk species. There are no copyright restrictions; please cite this paper when using the data for publication.