---
title: "A synthesis of life‐history traits, functional traits, and consequences of anthropogenic pressures on Madagascar’s threatened carnivorans, Eupleridae"
type: "article"
author: "Erin M Wampole, Zach J Farris, Brian D Gerber"
year: "2021"
publication: "Mammal Review"
doi: "https://doi.org/10.1111/mam.12234"
download: "../publications/Wampole et al. 2021.pdf"
toc: false
categories:
  - review
  - mammal
  - journal article
---

## Citation 

> Wampole, E.M., Farris, Z.J. and Gerber, B.D. (2021), A synthesis of life-history traits, functional traits, and consequences of anthropogenic pressures on Madagascar’s threatened carnivorans, Eupleridae. *Mam Rev*, 51: 402-419. https://doi.org/10.1111/mam.12234

## Abstract

Madagascar’s native carnivorans are an endemic monophyletic group of eight extant species belonging to the family Eupleridae. The International Union for Conservation of Nature (IUCN) currently classifies seven of the species as threatened (Vulnerable or Endangered), as their populations are in decline due to intensifying anthropogenic pressures. However, little is known about these species’ ecology and population trends, precluding forecasts of extinction risk. Life-history and functional traits govern species’ responses to environmental pressure and can be predictive of extinction risk. Incorporating relevant trait information can vastly improve risk assessments. Yet, information on the life-history and functional traits of the Eupleridae has never been compiled into a single framework. Our aims were to: 1) synthesise the current state of knowledge of the life-history and functional traits of euplerid species, 2) review empirical evidence of the effects of anthropogenic pressures on species, and 3) identify knowledge gaps and future research needs. We searched the published literature to compile life-history and functional trait information and known effects of anthropogenic pressures for Eupleridae. Our review indicates that Madagascar’s carnivorans have high-risk life-history and functional traits that increase their vulnerability to anthropogenic pressures. Publications reported negative effects on euplerids from habitat degradation and fragmentation, logging, non-native carnivorans, disease, and hunting and retaliatory killings. However, our synthesis revealed significant knowledge gaps, especially in species’ life-history traits and in the spatial variability in most traits. For most species, we currently do not have the robust data needed to assess trait-based risk dynamics. The culmination of reported traits, negative influence of ongoing anthropogenic pressures, and lack of robust metrics (e.g. population trends and trait variability) indicate that euplerids are at high risk, yet may reach the cusp of extinction without notice due to significant gaps in knowledge. Future research should prioritise filling gaps in knowledge of influential traits, evaluating anthropogenic pressures, and integrating trait information to improve risk assessments and extinction forecasts.