---
title: "Forest carnivores living on the edge with invasive predators"
type: "article"
author: "Erin M Wampole, Zach J Farris, Prisca Razafy, Brian D Gerber"
year: "2023"
publication: "Animal Conservation"
doi: "https://doi.org/10.1111/acv.12926"
download: "../publications/Wampole et al. 2023.pdf"
toc: false
categories:
  - forest management
  - invasive predator
  - mammal
  - occupancy
  - journal article
---

## Citation 

> Wampole, E.M., Farris, Z.J., Razafy, P. and Gerber, B.D. (2023), Forest carnivores living on the edge with invasive predators. *Anim. Conserv.* https://doi.org/10.1111/acv.12926

## Abstract

The proliferation of forest edges and invasive predators have been identified as two primary threats to carnivore populations globally. These threats often occur in unison, facilitated by anthropogenic activities (e.g., fragmentation), and together may pose a greater influence than when they occur separately. Targeted conservation actions for forest carnivores, including Madagascar carnivores, have been hindered by a failure to understand the relative contributions of these factors in driving species declines. To fill this gap, we conducted an extensive camera survey along the edge of intact, continuous protected rainforests in eastern Madagascar to evaluate the extent invasive predators and forest edge separately and in combination affect native carnivore space use. We hypothesized that structural vegetation changes at the forest edge interact with invasive predator trap success and occurrence to reduce native carnivore space use near the forest edge and separately have less influence than when combined. In contrast to findings in fragmented and degraded forests of Madagascar, we found hard forest edge and invasive predators alone do not indiscriminately reduce native carnivore space use in continuous intact forest. Instead, we found free-roaming dogs and cats interact with their surrounding environment (i.e., forest edge) in unique ways that shape species response differently than within interior forest. At the forest edge, vegetational changes of increasing shrub cover and the occurrence of dogs reduce space use of three of four native carnivores. However, we found greater effects of proximity to villages, especially with high invasive predator activity (free-roaming cats). Ultimately, native carnivores showed variable sensitivities to pressures we examined, providing support for species-specific management actions to maximize conservation outcomes. We encourage future studies to consider evaluating the magnitude of separate and combined threats to carnivores. In doing so, conservationists can better identify when threats can be managed in isolation and when they require simultaneous mitigation.