---
title: "Teeth, sex, and testosterone: aging in the world's smallest primate"
type: "article"
author: "Sarah Zohdy, Brian D Gerber, Stacey Tecot, Marina B Blanco, Julia M Winchester, Patricia C Wright, Jukka Jernvall"
year: "2014"
publication: "PLoS One"
doi: "https://doi.org/10.1371/journal.pone.0109528"
download: "../publications/Zohdy et al 2014.pdf"
toc: false
categories:
  - mammal
  - Madagascar
  - survival
  - mark recapture
  - journal article
---

## Citation 

> Zohdy, S., Gerber, B. D., Tecot, S., Blanco, M. B., Winchester, J. M., Wright, P. C., & Jernvall, J. (2014). Teeth, sex, and testosterone: aging in the world's smallest primate. *PLoS One*, 9(10), e109528.

## Abstract

Mouse lemurs (Microcebus spp.) are an exciting new primate model for understanding human aging and disease. In captivity, Microcebus murinus develops human-like ailments of old age after five years (e.g., neurodegeneration analogous to Alzheimer's disease) but can live beyond 12 years. It is believed that wild Microcebus follow a similar pattern of senescence observed in captive animals, but that predation limits their lifespan to four years, thus preventing observance of these diseases in the wild. Testing whether this assumption is true is informative about both Microcebus natural history and environmental influences on senescence, leading to interpretation of findings for models of human aging. Additionally, the study of Microcebus longevity provides an opportunity to better understand mechanisms of sex-biased longevity. Longevity is often shorter in males of species with high male-male competition, such as Microcebus, but mouse lemurs are sexually monomorphic, suggesting similar lifespans. We collected individual-based observations of wild brown mouse lemurs (Microcebus rufus) from 2003–2010 to investigate sex-differences in survival and longevity. Fecal testosterone was measured as a potential mechanism of sex-based differences in survival. We used a combination of high-resolution tooth wear techniques, mark-recapture, and hormone enzyme immunoassays. We found no dental or physical signs of senescence in M. rufus as old as eight years (N = 189, ages 1–8, mean = 2.59±1.63 SE), three years older than captive, senescent congeners (M. murinus). Unlike other polygynandrous vertebrates, we found no sex difference in age-dependent survival, nor sex or age differences in testosterone levels. While elevated male testosterone levels have been implicated in shorter lifespans in several species, this is one of the first studies to show equivalent testosterone levels accompanying equivalent lifespans. Future research on captive aged individuals can determine if senescence is partially a condition of their captive environment, and studies controlling for various environmental factors will further our understanding of senescence.