---
title: "Study Design / Simulation Assignment (Option 2)"
author: "Brian D. Gerber"
date: "2022-09-09"
output: html_document
---

<style type="text/css">
  body{
  font-size: 14pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### **Objective**: To evaluate study design tradeoffs between simple random sampling (SRS) and stratified random sampling (STRS) for a single deer density at two sample sizes. 

Simulate spatially structured deer densities that varies by percent of development. Setup sampling scenarios (SRS and STRS) to evaluate **2** sample sizes (your choice); the STRS should be stratified by percent development. You decide on how many strata, but keep the sample size equal among strata.  Compare and contrast the utility of STRS and SRS. 


All Scenarios: Deer density varies by percent development

-   Simple Random Sampling, sample size of X
-   Simple Random Sampling, sample size of Y
-   Stratified Random Sampling, sample size of X
-   Stratified Random Sampling, sample size of Y


### **Markdown**

Prepare a report (code and findings), using markdown that presents your findings using text and figures. Make a recommendation on the sample size you would suggest to go with and why.

You do not need to show all possible code. Show code that you think is essential for someone to understand your simulation study (e.g. no need to show plotting code). Try to avoid showing the same code in different places to keep the document from getting out of hand (i.e., long).

- **Suggestion 1**: For the markdown file, do not run the simulation every time you create/knit the document. Do the simulation, save the results, and load the results in the markdown file. You can include your code in the outputted markdown file by specifying eval=FALSE and echo=TRUE.

- **Suggestion 2**: Consider making an analysis script that outputs all your results into 1 or multiple files. Then use a plotting script to develop the plots you are interested. Then, start writing the markdown file that loads you results and plots only the things you want to show.

<br>
<br>

