{
  "hash": "af5dd0064988465dae3a20f2b55b42b6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regression Lab\"\nauthor: \"Brian Gerber\"\ndate: \"August 8, 2024\"\noutput: html_document\n---\n\n\n<style type=\"text/css\">\n\nbody, td {\n   font-size: 16px;\n}\ncode.r{\n  font-size: 16px;\n}\npre {\n  font-size: 16px\n}\n</style>\n\n\n\n\n\n\n# Assigment\n\nWrite a report that presents code and results that evaluates the below hypotheses related to African Elephant weight. The data file is `elephant.study.csv`. There are three columns, where each row is an individual sampled elephant, indicating the variables of `weight` (weight in lbs), `age.years` (age of elephant in years), and  `lat` (mean latitude of the elephants home range).\n\n#### Your report should ...\n\n- explore/present the data. use plots/histograms\n- write model notation correctly or use equatiomatic\n- fit the model with lm or glm to get MLEs and CI's. Define Type I error rate\n- interpret results, in relation to hypotheses. Make statements about 'statistical clarity' and support or not for the hypotheses\n- make prediction plots\n- evaluate model assumptions\n- conclusions and caveats (think about what we have not considered)\n- Appendix: present a summary of the R packages you used\n\nThroughout, add text around your code and results to allow the reader to follow your thinking. The text should be minimal.\n\n\n### Hypotheses/Predictions\n\n\n![](elephant.png){width=1000}\n\nI hypothesize that adult African Elephants (*Loxodonta africana*) increase in weight as they age because they are more efficient at conserving energy and acquiring high quality resources. As such, I predict that older elephants will weigh more than younger adult elephants. Further, I hypothesize that there is a latitudinal effect on the weight of elephants across the continent of Africa because of the extreme drought in the southern part of their range. I predict that elephants further north will weigh more than elephants further south. \n\nI evaluated these hypotheses by aggregating data on weights of elephants from collaborators. Each individual elephant was weighed in the same manner while being fit with a GPS collar. Each individual had a known age due to longterm demographic monitoring. I derived the mean latitude of each elephants dry season home range. \n\n### Explore Data\n\nThis data set consists of three columns. The response variable is `weight` and the two independent variables are `age.years` and `lat`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  dat = read.csv(\"elephant.study.csv\")\n  head(dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    weight age.years        lat\n1 12615.13        41   2.690077\n2 12539.55        50   2.974857\n3 13753.97        21  -4.868759\n4 17269.26        50 -28.437431\n5 16945.27        16 -26.414605\n6 14723.24        39 -11.392111\n```\n\n\n:::\n\n```{.r .cell-code}\n  par(mfrow=c(3,1))\n    hist(dat$weight)\n    hist(dat$age.years)\n    hist(dat$lat)\n```\n\n::: {.cell-output-display}\n![](regressionlab_BDG_files/figure-html/data-1.png){width=672}\n:::\n:::\n\n\nLooking at the data, we see a good frequency of weights ranging from  11681 to 17345. The independent variables are also well distributed and with relatively similar frequency. To make statements of statistical clarity when it comes to rejcting or no rejecting a null hypothesis of no difference, I use a Type I error ($\\alpha = 0.05$).\n\n### Define and Fit Model\n\nTo evaluate my hypotheses, I will consider a linear regression model with an additive effect of `age.years` and `lat`. I mean centered the variable `age.years` so that the intercept can be interpreted in relation to the average weight of elephants when at the equator (`lat = 0`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel = lm(weight~I(age.years-mean(age.years))+lat, data=dat)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = weight ~ I(age.years - mean(age.years)) + lat, data = dat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3567.1 -1084.3    44.6   977.9  3467.1 \n\nCoefficients:\n                                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                    13724.967    207.712  66.077  < 2e-16 ***\nI(age.years - mean(age.years))    -8.172     14.431  -0.566    0.572    \nlat                              -79.872     13.833  -5.774 9.31e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1550 on 97 degrees of freedom\nMultiple R-squared:  0.2562,\tAdjusted R-squared:  0.2408 \nF-statistic:  16.7 on 2 and 97 DF,  p-value: 5.842e-07\n```\n\n\n:::\n\n```{.r .cell-code}\nequatiomatic::extract_eq(model)\n```\n\n::: {.cell-output-display}\n$$\n\\operatorname{weight} = \\alpha + \\beta_{1}(\\operatorname{age.years\\ -\\ mean(age.years)}) + \\beta_{2}(\\operatorname{lat}) + \\epsilon\n$$\n\n:::\n:::\n\n\n$$\n\\begin{align} \n\\epsilon \\sim \\text{Normal}(0,\\sigma^2) \n\\end{align}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequatiomatic::extract_eq(model, use_coefs = TRUE)\n```\n\n::: {.cell-output-display}\n$$\n\\operatorname{\\widehat{weight}} = 13724.97 - 8.17(\\operatorname{age.years\\ -\\ mean(age.years)}) - 79.87(\\operatorname{lat})\n$$\n\n:::\n:::\n\n\n**Better Model Notation:**\n\nFor each i$^th$ elephant, we define out model as,\n\n$$\n\\begin{align*}\ny_{i} \\sim& \\text{Normal}(\\mu_{i}, \\sigma)\\\\\n\\mu =& \\beta_{0} + \\beta_1 \\times (\\text{age}_{i}- \\bar{\\text{age}}) + \\beta_2 \\times \\text{latitude}_{i}.\n\\end{align*}\n$$\n\n<br>\n\nI found the average weight of elephants at the equator (`lat = 0`) was 13724 lbs. The effect of age on weight was statistically unclear (p = 0.57), not supporting my hypothesis. The estimated effect was relatively small and negative $\\hat{\\beta_{1}} =$ -8.17, 95% CI = -36.81, 20.47. I found a statistically clear effect of latitude (p = 0) with an estimated effect $\\hat{\\beta_{2}} =$ -79.87, 95% CI = `r `round(confint(model)[3,],digits=2)`. However, this does not support my hypothesis that elephants would weigh more the further north they lived. Instead, we see that weights decreas with increasing latitude. \n\n\n### Predictions\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_predictions(model, condition = list(\"age.years\"))\n```\n\n::: {.cell-output-display}\n![](regressionlab_BDG_files/figure-html/preds-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot_predictions(model, condition = list(\"lat\"))\n```\n\n::: {.cell-output-display}\n![](regressionlab_BDG_files/figure-html/preds-2.png){width=672}\n:::\n:::\n\n\nThe marginal effect plots show the lack of evidence of the effect of age on weight and the support for decreasing weight with latitude. I suggest that this effect is biologically relevant, given that at the extremes in latitudes, we see that the mean weights of elephants is decreased by 18.125%. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_predictions(model, condition = list(\"age.years\",\"lat\"))\n```\n\n::: {.cell-output-display}\n![](regressionlab_BDG_files/figure-html/preds2-1.png){width=672}\n:::\n:::\n\n\nThe joint prediction plot demonstrates the same findings and the assumption of the additive effect between independent variables. \n\n### Model Assumptions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggResidpanel)\nresid_panel(model)\n```\n\n::: {.cell-output-display}\n![](regressionlab_BDG_files/figure-html/assumptions-1.png){width=672}\n:::\n:::\n\n\nThe top-right plot shows that the residuals are equally spaced below and above zero and that the variation within predicted values are relatively similar. The top-right plot shows no departre of the empirical quantiles of the residuals compared to theoretical values. Lastly, the bottom-right plot shows the residuals look symmetric and roughly Normally-distributed. \n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1,2))\nplot(model,4); plot(model,5)\n```\n\n::: {.cell-output-display}\n![](regressionlab_BDG_files/figure-html/assumptions2-1.png){width=672}\n:::\n:::\n\n\nLooking at the leverage of each observation, there appears to be a few potential outliers (measured by Cook's distance), but overall there appears to be little concern. However, to evaluate the effect of the three most extreme values, I will drop these observations and then assess whether the interpretation of the results change. \n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                                  Estimate Std. Error    t value     Pr(>|t|)\n(Intercept)                    13676.98844  199.24863 68.6428229 4.095285e-82\nI(age.years - mean(age.years))   -11.89521   14.25392 -0.8345222 4.061027e-01\nlat                              -88.26940   13.38388 -6.5952033 2.466726e-09\n```\n\n\n:::\n:::\n\n\nWe see that the estimated coefficients change relatively little. My interpretation of the results are the same. \n\n### Conclusions and Caveats\n\nI did not find support of either my hypotheses. Rather, I found evidence of a relevant biological effect where the mean weight of elephants decreased with increasing latitude. The total amount of the data that was explained by this model was relatively weak with an $R^2 =$ 0.26`.\n\nThere are several caveats we need to consider.\n\n- Sex was not controlled for. Males and female elephants are known to have different mean weights\n- The season of when an elephant was weighed is unknown and thus not controlled for\n- I did not consider an interaction between age and latitude\n- The range of ages might have limited our evaluation of the hypothesis. For example, 10 year olds may not be considered adults. \n\n\n\n# **Appendix**\n\n## Software\n\nThis report was generated from the R Statistical Software (v4.2.2; R Core Team 2021) using the [Markdown language](https://www.markdownguide.org/) and [RStudio](https://posit.co/products/open-source/rstudio/). The R packages used are acknowledged below. \n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Package         |Version |Citation                                       |\n|:---------------|:-------|:----------------------------------------------|\n|base            |4.4.1   |@base                                          |\n|equatiomatic    |0.3.3   |@equatiomatic                                  |\n|ggResidpanel    |0.3.0   |@ggResidpanel                                  |\n|knitr           |1.47    |@knitr2014; @knitr2015; @knitr2024             |\n|marginaleffects |0.21.0  |@marginaleffects                               |\n|rmarkdown       |2.27    |@rmarkdown2018; @rmarkdown2020; @rmarkdown2024 |\n\n\n:::\n:::\n",
    "supporting": [
      "regressionlab_BDG_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}