---
format: html
title: "Lab"
---

# Current

- **Dr. Michael Peyton**, Postdoctoral Researcher. Research focused on evaluating study design tradeoffs focused on terrestrial indirect effects (predator --> prey--> mountain shrub communities). 

- **Jonathan Crossley**, MS Candidate. Research focused on identifying areas of avian abundance and richness overlap with renewable energy development in Colorado. 

- **Libby Mojica**, PhD Student. Co-advised with Dr. Liba Pejchar. Researching the spatial ecology of Ferruginous hawk. 

- **Le Tan Quy**, MS Candidate. Researching the spatial ecology of the Silver-backed chevrotain (*Tragulus versicolor*)

# Former

- **Dr. Edwige Bellier**, Postdoctoral Researcher. <br>
Developed hierarchical Bayesian stochastic population reconstruction models to learn about fisher and white-tailed deer population demography. Currently working on evaluating the robustness of spatially explicit encounter models to estimate the population size of New England Cottontails.

- **Amy Mayer**, Research Associate. <br>
Amy does everything.

- **John Crockett**, PhD. Graduated 2025. <br>
Researching the spatial occurence of river otter (*Lontra canadensis*), beaver (*Castor canadensis*), and muksrat (*Ondatra zibethicus*) within Rhode Islands's watershed. Outcomes will inform state harvest decisions and land-management strategies.

- **Nicole Defelice**, MS. Graduated 2024.<br>
 Researching the use of olfactory scents as misinformation to reduce exposure of beach nesting shorebirds to predators. 

- **Laken Ganoe**, PhD. Graduated 2024. <br>
Researching Fisher (*Pekania pennanti*) spatial and population ecology within Rhode Island, USA to inform management strategies. Project details can be found on Laken's [project page](https://www.lakenganoe.com/meet-ri-fishers.html).


- **Dr. Kadambari Devarajan**, Postdoctoral Researcher. 2021-2023. <br>
Led the investigation of the [Global Animal Diel Activity Project](https://diel-project.github.io/)


- **Dylan Ferreira**, MS, Graduated 2022. <br>
Thesis: [Population monitoring of white-tailed deer in Rhode Island](https://digitalcommons.uri.edu/cgi/viewcontent.cgi?article=3117&context=theses).

- **Kylie Rezendes**, BS, Graduated 2022. <br>
Contributed to several research projects and led the camera-trap survey in Rhode Island as part of Snapshot USA.

- **Dr. Wales Carter**, Postdoctoral Researcher. 2020-2023. <br>
Focused on habitat selection and diet of New England Cottontails.


- **Kimberly Rivera**, MS, Graduated 2021. <br>
Thesis: [Rethinking habitat and how we study human-wildlife relationships](https://digitalcommons.uri.edu/cgi/viewcontent.cgi?article=3070&context=theses). 


- **Juliana Massseloux**, MS, Graduated 2021. <br>
Thesis: [Forest structure shapes tropical terrestrial and arboreal mesomammal communities under moderate disturbance](https://digitalcommons.uri.edu/cgi/viewcontent.cgi?article=2941&context=theses)

- **Erin Wampole**, MS, Graduated 2021. <br>
Thesis: [Examining anthropogenic pressures on Madagascar carnivorans](https://digitalcommons.uri.edu/cgi/viewcontent.cgi?article=2899&context=theses)

- **Ruby Nguyen**, BS, Graduated 2021. <br>
Investigated wildlife usage of forest rock walls in New England and coordinated camera-trap deployments as part of Snapshot USA.


- **Jess Burr**, BS, Graduated 2022. <br>
Lab Manager, investigated wildlife usage of forest rock walls in New England, coordinated camera-trap deployments as part of Snapshot USA, and was a research technician in Vietnam studying meso-mammals. 


- **Nicole Keefner**, MS, Graduated 2020. <br>
Thesis: [Temporal effectiveness of biodiversity surrogates in coral reefs in the British Virgin Islands](https://digitalcommons.uri.edu/cgi/viewcontent.cgi?article=2723&context=theses)
